"""Per-robot configuration loader and validator.

This is a pure-Python leaf module with no imports from other robot_radio
modules besides its sibling ``robot_config_generated`` (the generated
shape it composes on top of — see below). It loads and validates
per-robot JSON config files, computes derived encoder fields, and exposes
a cached singleton via get_robot_config().

132-020: the per-group ``BaseModel`` classes are no longer hand-declared
here. The groups ``robot_config.proto`` defines — three host-only
(Identity/Connection/Vision) plus eight robot-config groups consumed by
firmware (Geometry/Motors/Drive/WheelControl/Planner/Otos/Estimator) — are
generated by ``scripts/gen_messages.py`` into ``robot_config_generated.py``
(ticket 002) and imported below; this module composes them into
``RobotConfig`` and keeps only the behaviour a generated shape struct
cannot express: caching, env-var/pointer-file resolution, derived-field
computation (``mm_per_tick``), and the one cross-field validator no
``(min)``/``(max)``/``(abs_max)`` proto option pair can encode
(``rotational_slip``'s non-contiguous domain — see ``GeometryConfig``
below, and ``robot_config.proto``'s own header comment, which names this
exact module as that validator's home). Four sections the generator
excludes entirely, because no ``gen_boot_config.py`` ``_require()``/
``_get()`` call reads them — ``wheels``/``encoders``/``gripper``/
``peripherals`` — stay hand-declared here for that same reason (this
module's own derived ``mm_per_tick`` computation is wheels/encoders' one
real consumer).

KNOWN GAP, mid-sprint (sprint 132 "the configuration object"): today's
``data/robots/*.json`` files are still in the OLD 13-section shape
(``calibration``/``control`` as flat dumping grounds feeding five
firmware destinations) — the JSON reshape to match the new
consumer-grouped shape is ticket 017, scheduled deliberately last.

UPDATED by ticket 016: every group model (generated and hand-declared
alike) plus ``RobotConfig`` itself now sets ``model_config =
ConfigDict(extra="forbid")``. An unrecognized key anywhere in a robot
JSON now raises ``pydantic.ValidationError`` LOUDLY instead of pydantic's
former default ``extra='ignore'`` silently dropping it — closing the
measured gap that cost 18 ``control.*`` keys (including
``output_deadband``/``reversal_dwell``, which ``gen_boot_config.py``
REQUIRES and refuses to build without) with no observable symptom on the
host. The direct consequence, chosen and accepted deliberately (not a bug
to work around here): because ``data/robots/*.json`` are still OLD-shaped,
``load_robot_config()``/``get_robot_config()`` now RAISE for every real,
on-disk robot profile — the old ``calibration``/``control`` top-level
sections have no matching ``RobotConfig`` field at all, and several
reshaped groups (``connection``, ``vision``, ``geometry``) carry old-shape
keys the new schema doesn't recognize either. ``list_robots()`` degrades
gracefully (its existing try/except skips unreadable files, logging a
warning), so it returns an empty list for the real ``data/robots/``
directory until 017 lands, rather than crashing. This is expected and
accepted mid-sprint breakage — ticket 017's JSON reshape is the fix, not a
gate on this ticket. Callers that need a REAL RobotConfig today (e.g. sim
system tests exercising ``tovez_nocal.json``) will see their loads start
raising too; see each affected test file's own note if updated for this
ticket, or ticket 017's own report for what it re-greened.

Resolution order for get_robot_config():
1. ROBOT_CONFIG env var — full path to a JSON config file.
2. data/robots/active_robot.json — either a full config (has 'identity' key),
   a symlink to one, or a pointer file with a path key.
3. Returns None with a logged WARNING if neither is found.
"""

import logging
import math
import os
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from robot_radio.config.robot_config_generated import (
    Connection,
    Drive,
    Estimator,
    Geometry,
    Identity,
    Motors,
    Navigator,
    Otos,
    Planner,
    PlannerShaper,
    Vision,
    WheelControl,
)

logger = logging.getLogger(__name__)

# This file: src/host/robot_radio/config/robot_config.py -- parent(config)/
# parent(robot_radio)/parent(host)/parent(src)/parent(repo root) = FIVE hops
# from __file__, not four. 109-002 fix: the "unify all source trees under
# src/" refactor (commit 575ef391) added one path-depth level under every
# package without updating this constant, so it silently pointed at
# src/ instead of the repo root (list_robots()'s own _ROBOTS_DIR glob then
# found nothing -- surfaced by src/tests/testgui/test_calibration_push_on_connect.py's
# robot-combo test, which is the one caller that actually lists
# data/robots/*.json rather than pointing ROBOT_CONFIG at a temp file
# directly). See testgui/canvas.py's own _HERE/_SRC/_REPO constants (fixed
# for this identical off-by-one by ticket 107-004) for the same reasoning
# spelled out per path segment.
_PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent


# ---------------------------------------------------------------------------
# Host-only groups -- 1:1 identical to their robot_config_generated.py
# counterpart (Identity/Connection/Vision), so no hand-written subclass is
# needed here. Plain aliases, kept for backward-compatible imports --
# NOT a "hand-written BaseModel class": no field is re-declared, this is a
# name binding only.
# ---------------------------------------------------------------------------

IdentityConfig = Identity
ConnectionConfig = Connection
VisionConfig = Vision


# ---------------------------------------------------------------------------
# Host-only sections with NO generated counterpart. robot_config.proto
# excludes these entirely (its own header comment: every key under
# wheels/encoders/gripper/peripherals is "read by no firmware code" --
# "stay in the file under the one-file rule but never cross the wire").
# Stay hand-declared for that reason; this module's own derived
# mm_per_tick computation is wheels/encoders' one real consumer.
#
# 132-016: extra='forbid' here too -- these sections are as much a part of
# "an unrecognized key in a robot JSON fails loudly" as the generated
# groups; excluding them from the generator's own schema (dead to
# firmware) is not a reason to let a typo inside them vanish silently.
# ---------------------------------------------------------------------------

class OffsetXY(BaseModel):
    model_config = ConfigDict(extra="forbid")

    x: float = 0.0
    y: float = 0.0


class WheelsConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    wheel_diameter_mm: Optional[float] = None
    ticks_per_rev: Optional[float] = None
    ticks_per_mm: Optional[float] = None


class EncodersConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    has_encoders: bool = False
    encoder_count: int = 0


class GripperConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    has_gripper: bool = False
    gripper_offset_mm: Optional[OffsetXY] = None


class PeripheralsConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Digital port (J1..J4) the line laser is wired to. None = no laser
    # wired (fail-closed default -- a robot that doesn't set this explicitly
    # in its data/robots/*.json should not silently assume port 4 is wired).
    laser_port: Optional[int] = None


# ---------------------------------------------------------------------------
# Geometry -- a thin hand-written extension of the generated group: every
# generated field (trackwidth/rotational_slip/rotation_gain_pos/
# rotation_offset/rotation_gain_neg/rotation_offset_neg) is inherited
# unchanged; only otos_untrusted and the rotational_slip domain validator
# are hand-added here.
# ---------------------------------------------------------------------------

class GeometryConfig(Geometry):
    """``robot_config_generated.Geometry`` plus the one field and the one
    validator the generated shape does not carry.

    ``otos_untrusted`` -- ``robot_config.proto`` deliberately excludes this
    field (its own header comment: "none is read by any _require()/_get()
    call in gen_boot_config.py today ... dead data"), but that audit only
    checked FIRMWARE consumers. ``robot_radio.planner.heading.
    HeadingCorrector`` reads ``geometry.otos_untrusted`` HOST-side (via
    ``getattr(geometry, "otos_untrusted", False)``) to choose encoder-
    derived pose over raw OTOS pose for a rig whose chip is mechanically
    decoupled from the wheels (see that module's own docstring, and
    ``clasi/issues/rig-persistent-otos-distrust.md``). Dropping the field
    here would not raise -- ``getattr``'s own fallback swallows it -- it
    would silently flip both ``tovez.json``/``tovez_nocal.json`` back to
    trusting OTOS, exactly the "silent no-op" class of bug this sprint
    exists to eliminate. Kept here, at the SAME JSON path
    (``geometry.otos_untrusted``) it already occupied, pending a decision
    on whether it belongs in the generated schema (flagged, not silently
    reconciled -- see ticket 132-020's own completion report for the
    follow-up).

    ``model_config`` is INHERITED from ``Geometry`` (``extra="forbid"``,
    132-016) -- pydantic v2 merges a subclass's own ``model_config`` with
    every base's, so a plain, unconfigured subclass keeps the parent's
    settings without redeclaring them (confirmed empirically). Restated
    explicitly below anyway, for the same reason every other group in this
    file states it explicitly: a reader scanning this file for "does this
    forbid extra keys" should not have to check the generated module too.
    """
    model_config = ConfigDict(extra="forbid")

    otos_untrusted: bool = False

    @field_validator("rotational_slip")
    @classmethod
    def _validate_rotational_slip_domain(cls, v: float) -> float:
        """Domain {0} u [0.5, 1.0], non-contiguous -- 0 is the uncalibrated
        sentinel (``effectiveTrackWidth()``'s own "0 == uncalibrated
        sentinel" contract), not a divide-by-zero. No (min)/(max)/
        (abs_max) proto option pair can express a non-contiguous domain --
        robot_config.proto's own header comment names this exact "thin
        hand-written validation layer around the generated pydantic model"
        as this check's home.
        """
        if v != 0.0 and not (0.5 <= v <= 1.0):
            raise ValueError(
                f"rotational_slip must be 0 (uncalibrated sentinel) or in "
                f"[0.5, 1.0]; got {v}"
            )
        return v


# ---------------------------------------------------------------------------
# Root config model
# ---------------------------------------------------------------------------

class RobotConfig(BaseModel):
    """The whole robot JSON, one field per top-level section.

    ``extra="forbid"`` (132-016) catches an unrecognized TOP-LEVEL section
    name too, not just an unrecognized key inside a known one -- e.g. the
    OLD-shape file's own ``calibration``/``control`` sections (no matching
    field here at all as of ticket 020's grouped-shape rewiring) now raise
    at this level, before pydantic even descends into a sub-group's own
    ``extra="forbid"``.
    """
    model_config = ConfigDict(extra="forbid")

    schema_version: int = 1

    # -- robot_config.proto's groups (132-020, +navigator 135-004) ----------
    identity: IdentityConfig
    connection: ConnectionConfig = ConnectionConfig()
    vision: VisionConfig = VisionConfig()
    geometry: GeometryConfig = GeometryConfig()
    motors: Motors = Motors()
    drive: Drive = Drive()
    wheel_control: WheelControl = WheelControl()
    planner: Planner = Planner()
    # planner_shaper (132-017): split out of Planner, stakeholder-sanctioned
    # mid-sprint scope addition -- the six shaper-ceiling fields
    # (a_max/a_decel/alpha_max/alpha_decel/jerk_max/yaw_jerk_max) now carry
    # their own ConfigGroupTarget (PLANNER_SHAPER, LIVE) because they have
    # their own re-appliable setter (Motion::Planner::applyShaperLimits()),
    # unlike the rest of Planner. See robot_config.proto's PlannerShaper
    # message header comment for the full rationale.
    planner_shaper: PlannerShaper = PlannerShaper()
    otos: Otos = Otos()
    estimator: Estimator = Estimator()
    # navigator (135-004): Motion::NavigatorLimits' own group (robot_config.
    # proto's Navigator message) -- LIVE, sourced through the same
    # Configurator::install(NAVIGATOR)/applyGroup()/applyField() path every
    # other live group already uses.
    navigator: Navigator = Navigator()

    # -- host-only sections with no generated counterpart --------------------
    wheels: WheelsConfig = WheelsConfig()
    encoders: EncodersConfig = EncodersConfig()
    gripper: GripperConfig = GripperConfig()
    peripherals: PeripheralsConfig = PeripheralsConfig()

    # Derived field — not stored in JSON, computed after load
    mm_per_tick: Optional[float] = None

    @model_validator(mode="before")
    @classmethod
    def _strip_underscore_documentation_keys(cls, data):
        """Strip every leading-underscore key, recursively, from the raw
        JSON dict BEFORE pydantic validates it (132-017, JSON reshape).

        Established project convention (pre-dating this ticket, e.g.
        tovez.json's own ``_otos_linear_scale_note``/``_rotational_slip_
        note``/``_vel_gains_domain``): a leading-underscore key anywhere in
        a robot JSON is documentation/provenance, never live data — a
        long-form measurement writeup, a domain note, or a recorded-but-
        currently-unconsumed value (e.g. ``planner._plant_gain``, a
        recorded plant-ID measurement no `_require()` call reads any
        more). ``extra="forbid"`` (132-016) is exactly right for catching
        a genuinely unrecognized or misspelled REAL field name, but would
        otherwise also reject every one of these documentation keys the
        moment they sit inside a group this generator's own schema
        validates strictly (Geometry/Motors/Drive/WheelControl/Planner/
        PlannerShaper/Otos/Estimator, and even the hand-declared host-only
        sections) — since none of them, by design, declares an
        ``Optional[str]`` field for a note nobody consumes.

        Stripping happens HERE, on the raw dict, before any nested
        ``BaseModel`` is constructed — a ``model_validator(mode="before")``
        on the ROOT model receives the whole not-yet-parsed JSON tree, so
        by the time pydantic descends into ``geometry``/``otos``/etc. the
        underscore keys are already gone from those nested dicts too, and
        every sub-model's own ``extra="forbid"`` never even sees them.
        This does NOT touch the JSON FILE on disk — the notes stay
        exactly where the migration script placed them, physically
        alongside the field they document; this only shrinks what
        pydantic is asked to validate.
        """
        if not isinstance(data, dict):
            return data

        def strip(obj):
            if isinstance(obj, dict):
                return {k: strip(v) for k, v in obj.items() if not k.startswith("_")}
            if isinstance(obj, list):
                return [strip(v) for v in obj]
            return obj

        return strip(data)

    @model_validator(mode="after")
    def _resolve_encoder_fields(self) -> "RobotConfig":
        if not self.encoders.has_encoders:
            return self
        w = self.wheels
        wd, tpr, tpm = w.wheel_diameter_mm, w.ticks_per_rev, w.ticks_per_mm
        present = sum(v is not None for v in (wd, tpr, tpm))

        if present == 3:
            assert wd and tpr and tpm
            expected = tpr / (math.pi * wd)
            if abs(expected - tpm) / tpm > 0.01:
                raise ValueError(
                    f"Encoder fields inconsistent: wheel_diameter_mm={wd}, "
                    f"ticks_per_rev={tpr}, ticks_per_mm={tpm} (given) vs "
                    f"{expected:.6f} (computed). Exceeds 1% tolerance."
                )
            self.mm_per_tick = 1.0 / tpm

        elif present == 2:
            if wd is None:
                assert tpr and tpm
                w.wheel_diameter_mm = tpr / (math.pi * tpm)
            elif tpr is None:
                assert tpm and wd
                w.ticks_per_rev = tpm * math.pi * wd
            else:
                assert wd and tpr
                w.ticks_per_mm = tpr / (math.pi * wd)
            if w.ticks_per_mm is not None:
                self.mm_per_tick = 1.0 / w.ticks_per_mm

        elif w.ticks_per_mm is not None:
            self.mm_per_tick = 1.0 / w.ticks_per_mm

        return self

    # ------------------------------------------------------------------
    # Convenience flat accessors (avoids updating all call sites)
    # ------------------------------------------------------------------

    @property
    def robot_name(self) -> str:
        return self.identity.robot_name

    @property
    def uid(self) -> str:
        return self.identity.uid

    @property
    def hardware_model(self) -> str:
        return self.identity.hardware_model

    @property
    def common_name(self) -> str:
        return self.identity.common_name

    @property
    def robot_tag_id(self) -> int:
        return self.vision.robot_tag_id

    # 132-020: ``tag_offset_mm`` (nested OffsetXYYaw) and ``motor_deadband``
    # are deliberately DROPPED, not ported. ``tag_offset_mm`` -- the
    # generated ``Vision`` group flattens this into
    # tag_offset_x/y/z/yaw (no nested-offset home left to point at); its
    # one caller (``src/tests/playfield/pose_fix_convergence.py``) is an
    # HITL playfield tool, not pytest-collected. ``motor_deadband`` sourced
    # from the OLD JSON's own confusingly-named top-level "drive" section
    # (motor_deadband/max_cmd/...), which robot_config.proto's own header
    # comment calls out as "read by no firmware code" and excludes
    # entirely -- its one caller (``robot_radio.nav.navigator.
    # _load_motor_deadband()``) already wraps the read in
    # ``try/except Exception: pass`` with a literal ``35`` fallback, so
    # this is a silent, harmless degrade, not a crash.

    @property
    def trackwidth(self) -> float:
        return self.geometry.trackwidth

    @property
    def has_gripper(self) -> bool:
        return self.gripper.has_gripper

    @property
    def gripper_offset_mm(self) -> Optional[OffsetXY]:
        return self.gripper.gripper_offset_mm

    @property
    def laser_port(self) -> Optional[int]:
        return self.peripherals.laser_port

    @property
    def device_announcement_name(self) -> str:
        return self.connection.device_announcement_name

    @property
    def serial_last_6(self) -> str:
        return self.connection.serial_last_6

    @property
    def has_encoders(self) -> bool:
        return self.encoders.has_encoders

    @property
    def otos_angular_scale(self) -> float:
        return self.otos.angular_scale

    @property
    def otos_angular_scalar(self) -> int:
        return max(-128, min(127, round((self.otos.angular_scale - 1.0) / 0.001)))

    @property
    def otos_linear_scale(self) -> float:
        return self.otos.linear_scale

    @property
    def otos_linear_scalar(self) -> int:
        return max(-128, min(127, round((self.otos.linear_scale - 1.0) / 0.001)))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_robot_config(path: "str | Path") -> RobotConfig:
    """Load and validate a robot config JSON file.

    Raises:
        FileNotFoundError: if the file does not exist.
        pydantic.ValidationError: if the file fails schema validation.
        json.JSONDecodeError: if the file is not valid JSON.
    """
    path = Path(path)
    cfg = RobotConfig.model_validate_json(path.read_text())
    logger.info("Loaded robot config: robot_name=%r path=%s", cfg.robot_name, path)
    return cfg


# ---------------------------------------------------------------------------
# Cached singleton
# ---------------------------------------------------------------------------

_config_cache: Optional[RobotConfig] = None
_cache_loaded: bool = False

_ROBOTS_DIR = _PROJECT_ROOT / "data" / "robots"
_ACTIVE_ROBOT_POINTER = _ROBOTS_DIR / "active_robot.json"


def _reset_robot_config() -> None:
    """Clear the cached singleton. Intended for testing only."""
    global _config_cache, _cache_loaded
    _config_cache = None
    _cache_loaded = False


def list_robots() -> "list[tuple[str, Path]]":
    """List selectable robot configs as ``(robot_name, path)`` pairs.

    Scans ``data/robots/*.json``, skipping the ``active_robot.json`` pointer and
    the ``*.schema.json`` schema.  Sorted by robot name.  Entries that fail to
    load are silently skipped.
    """
    out: list[tuple[str, Path]] = []
    if not _ROBOTS_DIR.is_dir():
        return out
    for path in sorted(_ROBOTS_DIR.glob("*.json")):
        if path.name == "active_robot.json" or path.name.endswith(".schema.json"):
            continue
        try:
            cfg = load_robot_config(path)
        except Exception as e:  # noqa: BLE001 — a bad file shouldn't hide the rest
            logger.warning("Skipping unreadable robot config %s: %s", path, e)
            continue
        out.append((cfg.robot_name, path))
    out.sort(key=lambda pair: pair[0].lower())
    return out


def set_active_robot(path: "str | Path") -> RobotConfig:
    """Point ``active_robot.json`` at *path*, reset the cache, and load it.

    Writes the pointer file ``{"path": "data/robots/<name>.json"}`` (repo-root
    relative when possible), clears the cached singleton so ``get_robot_config``
    re-reads, and returns the freshly loaded config.
    """
    import json

    path = Path(path)
    cfg = load_robot_config(path)  # validate before writing the pointer
    try:
        rel = path.resolve().relative_to(_PROJECT_ROOT.resolve())
        pointer_path = rel.as_posix()
    except ValueError:
        pointer_path = str(path)
    _ACTIVE_ROBOT_POINTER.write_text(json.dumps({"path": pointer_path}) + "\n")
    _reset_robot_config()
    logger.info("Active robot set to %r (%s)", cfg.robot_name, pointer_path)
    return cfg


def get_robot_config() -> Optional[RobotConfig]:
    """Return the cached RobotConfig singleton.

    Resolution order:
    1. ROBOT_CONFIG env var — treated as a full path to the JSON file.
    2. data/robots/active_robot.json — full config, symlink, or pointer file.
    3. Returns None with a logged WARNING if neither is found.
    """
    global _config_cache, _cache_loaded
    if _cache_loaded:
        return _config_cache

    _cache_loaded = True

    # 1. ROBOT_CONFIG env var
    env_path = os.environ.get("ROBOT_CONFIG")
    if env_path:
        config_path = Path(env_path)
        if not config_path.is_absolute():
            config_path = _PROJECT_ROOT / config_path
        try:
            _config_cache = load_robot_config(config_path)
            return _config_cache
        except FileNotFoundError:
            logger.warning("ROBOT_CONFIG env var points to missing file: %s", config_path)
            return None

    # 2. data/robots/active_robot.json
    active_path = _PROJECT_ROOT / "data" / "robots" / "active_robot.json"
    if active_path.exists():
        try:
            import json
            pointer = json.loads(active_path.read_text())
        except Exception as e:
            logger.warning("Failed to read active_robot.json: %s", e)
            return None

        if "identity" in pointer or "schema_version" in pointer:
            # Full config (or symlink target)
            try:
                _config_cache = load_robot_config(active_path)
                return _config_cache
            except Exception as e:
                logger.warning("Failed to load active_robot.json as config: %s", e)
                return None

        if "path" in pointer:
            target = _PROJECT_ROOT / pointer["path"]
            try:
                _config_cache = load_robot_config(target)
                return _config_cache
            except FileNotFoundError:
                logger.warning(
                    "active_robot.json path pointer points to missing file: %s", target
                )
                return None

        logger.warning(
            "active_robot.json has neither 'identity' nor 'path' key — "
            "cannot resolve robot config"
        )
        return None

    logger.warning(
        "No robot config found. Set ROBOT_CONFIG env var or create "
        "data/robots/active_robot.json"
    )
    return None


# ---------------------------------------------------------------------------
# Robot matching by v2 ID response
# ---------------------------------------------------------------------------

def match_robot_by_id(id_response: str) -> Optional[RobotConfig]:
    """Return the RobotConfig whose device_announcement_name matches the v2 ID reply.

    Parses the firmware's v2 ``ID`` response line, e.g.:
        ``ID model=Nezha2 name=TOVEZ serial=89f137c0``

    Matching is case-insensitive on the ``name=`` field against
    ``connection.device_announcement_name`` in every JSON file found in
    ``data/robots/`` (excluding ``active_robot.json``).

    Several configs may legitimately share one announcement name — e.g.
    ``tovez.json`` and ``tovez_nocal.json`` (a calibration-stripped variant
    of the same physical robot) both announce ``tovez``.  Among the
    announcement-name matches, the config whose ``identity.robot_name``
    ALSO equals the announced name wins (exact-name preference); otherwise
    the first match in sorted-filename order is used, so the choice is
    deterministic rather than filesystem-glob-order dependent.  This keeps
    a real robot announcing ``name=tovez`` on the calibrated config instead
    of silently loading an uncalibrated variant.

    Falls back to ``get_robot_config()`` when:
    - No ``name=`` field is present in the response.
    - No config file's announcement name matches.

    Args:
        id_response: Raw ID response line from firmware (with or without
            the leading ``ID`` tag).

    Returns:
        The matching ``RobotConfig``, or ``None`` if nothing matches and
        the fallback also finds nothing.
    """
    import json
    import re

    # Extract name= from the ID response (may include "ID " prefix or not)
    m = re.search(r"\bname=(\S+)", id_response, re.IGNORECASE)
    if not m:
        logger.warning("match_robot_by_id: no name= field in ID response: %r", id_response)
        return get_robot_config()

    announced_name = m.group(1).lower()

    # Scan data/robots/ for candidate config files
    robots_dir = _PROJECT_ROOT / "data" / "robots"
    if not robots_dir.is_dir():
        logger.warning("match_robot_by_id: robots dir not found: %s", robots_dir)
        return get_robot_config()

    candidates = sorted(
        p for p in robots_dir.glob("*.json")
        if p.name not in ("active_robot.json", "robot_config.schema.json")
           and not p.name.startswith("_")
    )

    # Collect ALL announcement-name matches, then prefer the one whose
    # identity.robot_name also equals the announced name (see docstring).
    matches: list[tuple[Path, str]] = []  # (path, robot_name.lower())
    for candidate in candidates:
        try:
            data = json.loads(candidate.read_text())
            conn = data.get("connection", {})
            dan = (conn.get("device_announcement_name") or "").lower()
            if dan == announced_name:
                rn = ((data.get("identity") or {}).get("robot_name") or "").lower()
                matches.append((candidate, rn))
        except Exception as exc:
            logger.warning("match_robot_by_id: skipping %s: %s", candidate.name, exc)

    if matches:
        exact = [m for m in matches if m[1] == announced_name]
        chosen = (exact or matches)[0][0]
        if len(matches) > 1:
            logger.info(
                "match_robot_by_id: %d configs announce %r (%s); chose %s "
                "(%s)", len(matches), announced_name,
                ", ".join(p.name for p, _ in matches), chosen.name,
                "exact robot_name match" if exact else "first in sorted order",
            )
        try:
            cfg = load_robot_config(chosen)
            logger.info(
                "match_robot_by_id: matched %r -> %s", announced_name, chosen.name
            )
            return cfg
        except Exception as exc:
            logger.warning("match_robot_by_id: failed to load %s: %s", chosen.name, exc)

    logger.warning(
        "match_robot_by_id: no config matched name=%r; falling back to get_robot_config()",
        announced_name,
    )
    return get_robot_config()
