"""robot_config_generated.py -- GENERATED pydantic BaseModel hierarchy (132-002).

AUTO-GENERATED by scripts/gen_messages.py -- do not edit by hand.
Source: protos/robot_config.proto -- Config::Robot's end-state 10-group
schema (3 host-only: Identity/Connection/Vision; 7 robot-config: Geometry/
Motors/Drive/WheelControl/Planner/Otos/Estimator), walked by the SAME
field-descriptor pass that emits src/firm/messages/robot_config.h's C++
group structs (host-only groups excluded there, included here — see
options.proto's own (host_only) doc comment) and
data/robots/robot_config.schema.json's JSON Schema document.

One flat BaseModel class per group, field-for-field, no cross-field
validation and no derived quantities (sprint 132 issue "the-configuration-
object.md": "the object holds RAW file values" -- Config::Robot's own C++
struct carries the identical constraint; derived quantities are Config::
Robot METHODS, not schema fields).

Every class sets ``model_config = ConfigDict(extra="forbid")`` (132-016,
"the configuration object" issue's own Sequencing step 6: "extra='forbid'
on the host model") -- an unrecognized JSON key under any group now raises
``pydantic.ValidationError`` instead of pydantic's default ``extra=
'ignore'`` silently dropping it. This is the fix for the issue's own
measured cost: the old hand-written host model had 36 ``control`` fields
where the robot JSON had 53, silently dropping 18 keys including
``output_deadband``/``reversal_dwell`` (JSON: ``reversal_dwell_ms``),
which ``gen_boot_config.py`` REQUIRES and refuses to build without.

Wired into src/host/robot_radio/config/robot_config.py's actual loader/
validator (get_robot_config()/list_robots()/derived-field computation) as
of sprint 132 ticket 020 (see that module's own header for the
composition). NOTE (132-016): ``data/robots/*.json`` are still in the OLD
13-section shape as of this generation -- ticket 017's JSON reshape has
not landed -- so ``extra='forbid'`` makes loading any CURRENT real robot
JSON raise ``ValidationError`` until 017 lands. Expected and accepted
mid-sprint breakage (see robot_config.py's own KNOWN GAP note); not a bug
in this generator.

Regenerate: python3 src/scripts/gen_messages.py
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

class Identity(BaseModel):
    model_config = ConfigDict(extra="forbid")
    robot_name: str = ""
    uid: str = ""
    hardware_model: str = ""
    common_name: str = ""
    drivetrain_type: str = ""

class Connection(BaseModel):
    model_config = ConfigDict(extra="forbid")
    device_announcement_name: str = ""
    serial_last_6: str = ""
    radio_channel: int = 0
    wifi_ip: str = ""

class Vision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    robot_tag_id: int = 0
    tag_offset_x: float = 0.0
    tag_offset_y: float = 0.0
    tag_offset_z: float = 0.0
    tag_offset_yaw: float = 0.0
    camera_distance_scale: float = 0.0

class Geometry(BaseModel):
    model_config = ConfigDict(extra="forbid")
    trackwidth: float = 0.0
    rotational_slip: float = 0.0
    rotation_gain_pos: float = 0.0
    rotation_offset: float = 0.0
    rotation_gain_neg: float = 0.0
    rotation_offset_neg: float = 0.0

class Motors(BaseModel):
    model_config = ConfigDict(extra="forbid")
    left_port: int = 0
    right_port: int = 0
    travel_calib_left: float = 0.0
    travel_calib_right: float = 0.0
    fwd_sign_left: int = 0
    fwd_sign_right: int = 0
    output_deadband: float = 0.0
    reversal_dwell: float = 0.0
    vel_kp: float = 0.0
    vel_ki: float = 0.0
    vel_kff: float = 0.0
    vel_i_max: float = 0.0
    vel_kaw: float = 0.0
    vel_filt_alpha: float = 0.0

class Drive(BaseModel):
    model_config = ConfigDict(extra="forbid")
    duty_per_speed_left: float = 0.0
    duty_per_speed_right: float = 0.0
    crawl_pulse: float = 0.0
    wheel_gain_left_accel: float = 0.0
    wheel_intercept_left_accel: float = 0.0
    wheel_gain_left_decel: float = 0.0
    wheel_intercept_left_decel: float = 0.0
    wheel_gain_right_accel: float = 0.0
    wheel_intercept_right_accel: float = 0.0
    wheel_gain_right_decel: float = 0.0
    wheel_intercept_right_decel: float = 0.0

class WheelControl(BaseModel):
    model_config = ConfigDict(extra="forbid")
    v_min: float = 0.0
    bias_max: float = 0.0
    tau_adapt: float = 0.0
    a_steady: float = 0.0
    deficit_threshold: float = 0.0
    deficit_window: float = 0.0
    pid_kp: float = 0.0
    pid_ki: float = 0.0
    pid_i_max: float = 0.0
    pid_kaff: float = 0.0
    pid_max: float = 0.0
    pos_err_max: float = 0.0
    stall_speed: float = 0.0
    stall_demand: float = 0.0
    stall_window: float = 0.0

class Planner(BaseModel):
    model_config = ConfigDict(extra="forbid")
    v_max: float = 0.0
    omega_max: float = 0.0
    control_period: float = 0.0
    actuation_delay: float = 0.0
    settle_rest_velocity: float = 0.0
    settle_rest_omega: float = 0.0
    settle_epsilon_linear: float = 0.0
    settle_epsilon_angular: float = 0.0
    heading_hold_gain: float = 0.0
    decel_plan_fraction: float = 0.0
    align_tol: float = 0.0
    align_max_nudges: int = 0

class PlannerShaper(BaseModel):
    model_config = ConfigDict(extra="forbid")
    a_max: float = 0.0
    a_decel: float = 0.0
    alpha_max: float = 0.0
    alpha_decel: float = 0.0
    jerk_max: float = 0.0
    yaw_jerk_max: float = 0.0

class Navigator(BaseModel):
    model_config = ConfigDict(extra="forbid")
    speed: float = 0.0
    max_wheel_step: float = 0.0
    behind_angle: float = 0.0
    turn_first_angle: float = 0.0
    approach_radius: float = 0.0
    approach_speed: float = 0.0
    default_arrival_tolerance: float = 0.0
    yaw_sign: float = 0.0

class Otos(BaseModel):
    model_config = ConfigDict(extra="forbid")
    offset_x: float = 0.0
    offset_y: float = 0.0
    offset_yaw: float = 0.0
    linear_scale: float = 0.0
    angular_scale: float = 0.0

class Estimator(BaseModel):
    model_config = ConfigDict(extra="forbid")
    weight_heading_otos: float = 0.0
    weight_omega_otos: float = 0.0
    staleness: int = 0
