// wire_codec_harness.cpp -- off-hardware acceptance harness for ticket
// 095-005 (SUC-004, architecture-update.md M4 "Generated Envelope Codec"):
// exercises msg::wire::decode()/encode() (source/messages/wire.{h,cpp},
// GENERATED by scripts/gen_messages.py) directly against every implemented
// CommandEnvelope/ReplyEnvelope arm this sprint declares, plus a
// representative declared-only arm, covering: round-trip, missing-`req`
// reject, out-of-min/max/abs_max reject, unknown-field skip,
// oversized-buffer encode() rejection, and repeated-field max_count clamp.
//
// This is DISTINCT from ticket 006's differential-against-google.protobuf
// suite (not yet written) -- this harness checks the generic engine's OWN
// behavior in isolation, by hand-building wire bytes with WireRuntime's own
// primitives (the same primitives wire.cpp's generated decode()/encode()
// are built on) and asserting msg::wire::decode()'s resulting struct
// fields, or by hand-parsing msg::wire::encode()'s output.
//
// Mirrors wire_runtime_harness.cpp's exact pattern (see that file's header
// for the shape this follows): hand-rolled assertions, prints PASS/FAIL,
// exits nonzero on any failure. Run by test_wire_codec.py via subprocess.
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>

#include "messages/envelope.h"
#include "messages/wire.h"
#include "messages/wire_runtime.h"

namespace {

using WireRuntime::WireType;

// --- Hand-rolled assertion plumbing (same tiny shape as
// wire_runtime_harness.cpp / runtime_blackboard_harness.cpp). ---

int g_failureCount = 0;
std::string g_scenarioName;

void beginScenario(const std::string& name) {
  g_scenarioName = name;
  std::printf("--- %s\n", name.c_str());
}

void fail(const std::string& what) {
  ++g_failureCount;
  std::printf("  FAIL [%s]: %s\n", g_scenarioName.c_str(), what.c_str());
}

void checkTrue(bool condition, const std::string& what) {
  if (!condition) fail(what + " -- expected true, got false");
}

void checkFalse(bool condition, const std::string& what) {
  if (condition) fail(what + " -- expected false, got true");
}

void checkU64Eq(uint64_t actual, uint64_t expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %llu, got %llu", what.c_str(),
                  static_cast<unsigned long long>(expected), static_cast<unsigned long long>(actual));
    fail(buf);
  }
}

void checkFloatEq(float actual, float expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %g, got %g", what.c_str(), static_cast<double>(expected),
                  static_cast<double>(actual));
    fail(buf);
  }
}

void checkStrEq(const char* actual, const char* expected, const std::string& what) {
  if (std::strcmp(actual, expected) != 0) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected \"%s\", got \"%s\"", what.c_str(), expected, actual);
    fail(buf);
  }
}

// --- Hand-rolled wire-byte builder (a tiny buffer + cursor, composed with
// WireRuntime's own primitives -- the SAME primitives wire.cpp's generated
// decode()/encode() are built on) -- lets this harness construct arbitrary
// CommandEnvelope payloads without depending on msg::wire::encode() (which
// only exists for ReplyEnvelope this sprint, per Decision 4/architecture-
// update.md's own asymmetric decode(Command)/encode(Reply) API shape). ---

struct Buf {
  uint8_t data[256] = {};
  size_t len = 0;
};

bool putVarintField(Buf& b, uint32_t number, uint64_t v) {
  return WireRuntime::encodeTag(number, WireType::kVarint, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeVarint(v, b.data, sizeof(b.data), &b.len);
}

bool putFloatField(Buf& b, uint32_t number, float v) {
  return WireRuntime::encodeTag(number, WireType::kFixed32, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeFloat(v, b.data, sizeof(b.data), &b.len);
}

bool putBytesField(Buf& b, uint32_t number, const uint8_t* payload, size_t payloadLen) {
  if (!WireRuntime::encodeTag(number, WireType::kLengthDelimited, b.data, sizeof(b.data), &b.len)) return false;
  if (!WireRuntime::encodeVarint(payloadLen, b.data, sizeof(b.data), &b.len)) return false;
  if (b.len + payloadLen > sizeof(b.data)) return false;
  std::memcpy(b.data + b.len, payload, payloadLen);
  b.len += payloadLen;
  return true;
}

bool putMessageField(Buf& b, uint32_t number, const Buf& nested) {
  return putBytesField(b, number, nested.data, nested.len);
}

// --- Scenario builders for a few reusable nested payloads -----------------

Buf buildBodyTwist3(float vx, float vy, float omega) {
  Buf b;
  putFloatField(b, 1, vx);
  putFloatField(b, 2, vy);
  putFloatField(b, 3, omega);
  return b;
}

Buf buildWheelTarget(float speed) {
  Buf b;
  putFloatField(b, 1, speed);  // speed (Opt<float>)
  return b;
}

Buf buildWheelTargets(int count, float baseSpeed) {
  Buf wheels;
  for (int i = 0; i < count; ++i) {
    Buf w = buildWheelTarget(baseSpeed + static_cast<float>(i));
    putMessageField(wheels, 1, w);  // WheelTargets.w, repeated field 1 -- each occurrence separately tagged
  }
  return wheels;
}

Buf buildMotionSegment(float distance, float speedMax) {
  Buf b;
  putFloatField(b, 1, distance);   // distance (abs_max=10000)
  putFloatField(b, 4, speedMax);   // speed_max (min=0, max=3000)
  return b;
}

// ===========================================================================
// 1. Round-trip -- every IMPLEMENTED CommandEnvelope arm (drive, segment,
//    replace, stop, ping, echo, id), plus a repeated-message field
//    (WheelTargets.w via drive/wheels) and a 2-level-nested declared-only
//    arm (otos/OdometerCommand.set_pose).
// ===========================================================================

void scenarioRoundTripDrive() {
  beginScenario("decode(): round-trip drive arm (DrivetrainCommand.control.twist)");
  Buf twist = buildBodyTwist3(111.0f, -22.5f, 3.0f);
  Buf drive;
  putMessageField(drive, 1, twist);  // DrivetrainCommand.control.twist, field 1

  Buf env;
  putVarintField(env, 1, 7);          // corr_id
  putMessageField(env, 2, drive);     // CommandEnvelope.cmd.drive, field 2

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkU64Eq(out.corr_id, 7, "corr_id round-trips");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::DRIVE, "cmd_kind == DRIVE");
  checkTrue(out.cmd.drive.control_kind == msg::DrivetrainCommand::ControlKind::TWIST, "control_kind == TWIST");
  checkFloatEq(out.cmd.drive.control.twist.v_x, 111.0f, "twist.v_x round-trips");
  checkFloatEq(out.cmd.drive.control.twist.v_y, -22.5f, "twist.v_y round-trips");
  checkFloatEq(out.cmd.drive.control.twist.omega, 3.0f, "twist.omega round-trips");
}

void scenarioRoundTripDriveWheelsRepeated() {
  beginScenario("decode(): round-trip drive/wheels -- repeated-message field (WheelTargets.w)");
  Buf wheels = buildWheelTargets(3, 100.0f);  // 3 elements, well under max_count=4
  Buf drive;
  putMessageField(drive, 2, wheels);  // DrivetrainCommand.control.wheels, field 2

  Buf env;
  putMessageField(env, 2, drive);

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd.drive.control_kind == msg::DrivetrainCommand::ControlKind::WHEELS, "control_kind == WHEELS");
  checkU64Eq(out.cmd.drive.control.wheels.w_count, 3, "w_count == 3");
  checkFloatEq(out.cmd.drive.control.wheels.w_[0].speed.val, 100.0f, "w[0].speed round-trips");
  checkTrue(out.cmd.drive.control.wheels.w_[0].speed.has, "w[0].speed.has == true");
  checkFloatEq(out.cmd.drive.control.wheels.w_[1].speed.val, 101.0f, "w[1].speed round-trips");
  checkFloatEq(out.cmd.drive.control.wheels.w_[2].speed.val, 102.0f, "w[2].speed round-trips");
}

void scenarioRepeatedFieldMaxCountClamp() {
  beginScenario("decode(): repeated-message field clamps at max_count (WheelTargets.w, cap=4)");
  Buf wheels = buildWheelTargets(6, 500.0f);  // 6 elements, over max_count=4 -- must clamp, not overflow
  Buf drive;
  putMessageField(drive, 2, wheels);
  Buf env;
  putMessageField(env, 2, drive);

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds (clamping is silent, not a decode failure)");
  checkU64Eq(out.cmd.drive.control.wheels.w_count, 4, "w_count clamps to max_count (4), not the 6 elements sent");
  checkFloatEq(out.cmd.drive.control.wheels.w_[0].speed.val, 500.0f, "w[0] retains the first element");
  checkFloatEq(out.cmd.drive.control.wheels.w_[3].speed.val, 503.0f, "w[3] retains the fourth element (5th/6th dropped, not overflowed)");
}

void scenarioRoundTripSegmentAndReplace() {
  beginScenario("decode(): round-trip segment/replace arms (MotionSegment)");
  {
    Buf seg = buildMotionSegment(-1500.0f, 800.0f);
    Buf env;
    putMessageField(env, 3, seg);  // CommandEnvelope.cmd.segment, field 3
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "segment decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::SEGMENT, "cmd_kind == SEGMENT");
    checkFloatEq(out.cmd.segment.distance, -1500.0f, "segment.distance round-trips");
    checkFloatEq(out.cmd.segment.speed_max, 800.0f, "segment.speed_max round-trips");
  }
  {
    Buf seg = buildMotionSegment(2000.0f, 1200.0f);
    Buf env;
    putMessageField(env, 4, seg);  // CommandEnvelope.cmd.replace, field 4
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "replace decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::REPLACE, "cmd_kind == REPLACE");
    checkFloatEq(out.cmd.replace.distance, 2000.0f, "replace.distance round-trips");
  }
}

void scenarioRoundTripStopPingEcho() {
  beginScenario("decode(): round-trip stop/ping (zero-field) and echo (bytes) arms");
  {
    Buf env;
    putMessageField(env, 13, Buf{});  // CommandEnvelope.cmd.stop, field 13, empty payload
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "stop decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::STOP, "cmd_kind == STOP");
  }
  {
    Buf env;
    putMessageField(env, 9, Buf{});  // CommandEnvelope.cmd.ping, field 9, empty payload
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "ping decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::PING, "cmd_kind == PING");
  }
  {
    const uint8_t payload[5] = {'h', 'e', 'l', 'l', 'o'};
    Buf echo;
    putBytesField(echo, 1, payload, sizeof(payload));  // Echo.payload, field 1
    Buf env;
    putMessageField(env, 10, echo);  // CommandEnvelope.cmd.echo, field 10
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "echo decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::ECHO, "cmd_kind == ECHO");
    checkU64Eq(out.cmd.echo.payload_count, 5, "echo.payload_count == 5");
    checkTrue(std::memcmp(out.cmd.echo.payload_, payload, sizeof(payload)) == 0, "echo.payload bytes round-trip");
  }
}

void scenarioRoundTripId() {
  beginScenario("decode(): round-trip id arm -- empty REQUEST payload (Decision 4)");
  Buf env;
  putMessageField(env, 14, Buf{});  // CommandEnvelope.cmd.id, field 14, empty request payload
  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "id (empty request) decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::ID, "cmd_kind == ID");
  checkStrEq(out.cmd.id.model, "", "id.model stays at zero-value default");
}

void scenarioRoundTripDeclaredOnlyPoseAndOtos() {
  beginScenario("decode(): round-trip pose_fix (PoseFix, 099-004) and otos (declared-only, 2-level nested Pose2D)");
  {
    Buf pose;
    putFloatField(pose, 1, 10.0f);    // x
    putFloatField(pose, 2, -20.0f);   // y
    putFloatField(pose, 3, 1.57f);    // h
    putVarintField(pose, 4, 4242);    // t [ms]
    putVarintField(pose, 5, 1);       // reset = true
    Buf env;
    putMessageField(env, 7, pose);  // CommandEnvelope.cmd.pose_fix, field 7
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "pose_fix decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::POSE_FIX, "cmd_kind == POSE_FIX");
    checkFloatEq(out.cmd.pose_fix.x, 10.0f, "pose_fix.x round-trips");
    checkFloatEq(out.cmd.pose_fix.h, 1.57f, "pose_fix.h round-trips");
    checkU64Eq(out.cmd.pose_fix.t, 4242, "pose_fix.t round-trips");
    checkTrue(out.cmd.pose_fix.reset, "pose_fix.reset round-trips");
    checkFalse(out.cmd.pose_fix.zero_encoders, "pose_fix.zero_encoders stays at zero-value default");
  }
  {
    // otos -> OdometerCommand.action.set_pose -> Pose2D: exercises TWO
    // levels of nested-message recursion (CommandEnvelope -> OdometerCommand
    // -> Pose2D), not just one.
    Buf pose2d;
    putFloatField(pose2d, 1, 5.0f);
    putFloatField(pose2d, 2, 6.0f);
    putFloatField(pose2d, 3, 0.5f);
    Buf otos;
    putMessageField(otos, 4, pose2d);  // OdometerCommand.action.set_pose, field 4
    Buf env;
    putMessageField(env, 8, otos);  // CommandEnvelope.cmd.otos, field 8
    msg::CommandEnvelope out;
    msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
    checkTrue(r.ok, "otos (2-level nested) decode succeeds");
    checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::OTOS, "cmd_kind == OTOS");
    checkTrue(out.cmd.otos.action_kind == msg::OdometerCommand::ActionKind::SET_POSE, "action_kind == SET_POSE");
    checkFloatEq(out.cmd.otos.action.set_pose.x, 5.0f, "otos.set_pose.x round-trips");
    checkFloatEq(out.cmd.otos.action.set_pose.y, 6.0f, "otos.set_pose.y round-trips");
  }
}

// ===========================================================================
// 2. req/min/max/abs_max validation -- one field of each validated kind.
// ===========================================================================

void scenarioMissingReqRejected() {
  beginScenario("decode(): missing (req) field rejected -- ConfigGet.target");
  Buf getArm;  // deliberately EMPTY -- target's tag never appears
  Buf env;
  putMessageField(env, 11, getArm);  // CommandEnvelope.cmd.get, field 11

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkFalse(r.ok, "decode rejects a get arm missing its (req) target field");
  checkU64Eq(r.field, 1, "reported field number is ConfigGet.target's (1)");
  checkTrue(r.code == msg::ErrCode::ERR_BADARG, "ErrCode is ERR_BADARG for a missing (req) field");

  // Control: WITH target present, decode succeeds.
  Buf getArmOk;
  putVarintField(getArmOk, 1, 42);
  Buf envOk;
  putMessageField(envOk, 11, getArmOk);
  msg::CommandEnvelope outOk;
  msg::wire::Result rOk = msg::wire::decode(outOk, envOk.data, static_cast<uint16_t>(envOk.len));
  checkTrue(rOk.ok, "decode succeeds once (req) target is present");
  checkTrue(outOk.cmd.get.target.has, "target.has == true");
  // 096-001: ConfigGet.target retyped uint32 -> ConfigTarget; .val is now
  // msg::ConfigTarget, cast the same way scenarioEncodeErr() already casts
  // msg::ErrCode below.
  checkU64Eq(static_cast<uint64_t>(outOk.cmd.get.target.val), 42, "target.val round-trips");
}

void scenarioMinMaxRejected() {
  beginScenario("decode(): out-of-(min)/(max) field rejected -- MotionSegment.speed_max [0, 3000]");
  Buf seg = buildMotionSegment(0.0f, 5000.0f);  // speed_max over max=3000
  Buf env;
  putMessageField(env, 3, seg);  // segment arm

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkFalse(r.ok, "decode rejects speed_max=5000 (over max=3000)");
  checkU64Eq(r.field, 4, "reported field number is MotionSegment.speed_max's (4)");
  checkTrue(r.code == msg::ErrCode::ERR_RANGE, "ErrCode is ERR_RANGE for an out-of-max field");
}

void scenarioAbsMaxRejected() {
  beginScenario("decode(): out-of-(abs_max) field rejected -- MotionSegment.distance [-10000, 10000]");
  Buf seg = buildMotionSegment(-20000.0f, 500.0f);  // |distance| over abs_max=10000
  Buf env;
  putMessageField(env, 3, seg);

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkFalse(r.ok, "decode rejects distance=-20000 (|v| over abs_max=10000)");
  checkU64Eq(r.field, 1, "reported field number is MotionSegment.distance's (1)");
  checkTrue(r.code == msg::ErrCode::ERR_RANGE, "ErrCode is ERR_RANGE for an out-of-abs_max field");
}

// ===========================================================================
// 3. Unknown-field skip -- forward compatibility.
// ===========================================================================

void scenarioUnknownFieldSkipped() {
  beginScenario("decode(): unknown top-level field number is skipped, not rejected");
  Buf env;
  putVarintField(env, 1, 3);                 // corr_id (known)
  putVarintField(env, 99, 123456);            // unknown field number 99 (varint) -- must be skipped
  Buf getArm;
  putVarintField(getArm, 1, 7);
  putMessageField(env, 11, getArm);           // get arm (known), AFTER the unknown field

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds despite the unknown field 99");
  checkU64Eq(out.corr_id, 3, "corr_id (before the unknown field) is unaffected");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::GET, "cmd_kind == GET (after the unknown field) is unaffected");
  // 096-001: ConfigGet.target retyped uint32 -> ConfigTarget; see the cast
  // note in scenarioMissingReqRejected() above.
  checkU64Eq(static_cast<uint64_t>(out.cmd.get.target.val), 7, "get.target (after the unknown field) round-trips correctly");
}

// ===========================================================================
// 4. encode() -- ReplyEnvelope, oversized-buffer rejection, and content
//    correctness (hand-parsed with WireRuntime's own primitives, plus a
//    round-trip-via-CommandEnvelope.id trick for the string-bearing
//    DeviceId body, since no generic decode(ReplyEnvelope) exists this
//    sprint -- decode() is CommandEnvelope-only, encode() is
//    ReplyEnvelope-only, per Decision 4/wire.h's own asymmetric API).
// ===========================================================================

void scenarioEncodeAckHandParsed() {
  beginScenario("encode(): ReplyEnvelope{ok=Ack{q,rem}} -- hand-parsed byte-for-byte");
  msg::ReplyEnvelope reply;
  reply.corr_id = 9;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::OK;
  reply.body.ok.q = 5;
  reply.body.ok.rem = 12.5f;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds (n > 0)");

  // Hand-parse: corr_id (field 1, varint), then the `ok` oneof arm
  // (field 2, length-delimited -> Ack{q (field 1, varint), rem (field 2, fixed32)}).
  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "corr_id tag decodes");
  checkU64Eq(fieldNumber, 1, "first field is corr_id (1)");
  uint64_t corrId = 0;
  checkTrue(WireRuntime::decodeVarint(buf, n, &pos, &corrId), "corr_id value decodes");
  checkU64Eq(corrId, 9, "corr_id round-trips");

  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "ok-arm tag decodes");
  checkU64Eq(fieldNumber, 2, "second field is the `ok` oneof arm (2)");
  checkTrue(wt == WireType::kLengthDelimited, "ok arm is length-delimited");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "ok-arm payload length decodes");

  size_t innerPos = 0;
  const uint8_t* inner = buf + pos;
  checkTrue(WireRuntime::decodeTag(inner, payloadLen, &innerPos, &fieldNumber, &wt), "Ack.q tag decodes");
  checkU64Eq(fieldNumber, 1, "Ack.q field number is 1");
  uint64_t q = 0;
  checkTrue(WireRuntime::decodeVarint(inner, payloadLen, &innerPos, &q), "Ack.q value decodes");
  checkU64Eq(q, 5, "Ack.q round-trips");

  checkTrue(WireRuntime::decodeTag(inner, payloadLen, &innerPos, &fieldNumber, &wt), "Ack.rem tag decodes");
  checkU64Eq(fieldNumber, 2, "Ack.rem field number is 2");
  float rem = 0.0f;
  checkTrue(WireRuntime::decodeFloat(inner, payloadLen, &innerPos, &rem), "Ack.rem value decodes");
  checkFloatEq(rem, 12.5f, "Ack.rem round-trips");
  checkU64Eq(innerPos, payloadLen, "Ack payload fully consumed (no trailing garbage)");
}

void scenarioEncodeErrorHandParsed() {
  beginScenario("encode(): ReplyEnvelope{err=Error{code,field}} -- hand-parsed");
  msg::ReplyEnvelope reply;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::ERR;
  reply.body.err.code = msg::ErrCode::ERR_RANGE;
  reply.body.err.field = 4;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");

  // corr_id == 0 -- implicit presence omits it, so the FIRST field on the
  // wire is the `err` oneof arm (field 3) directly.
  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "err-arm tag decodes");
  checkU64Eq(fieldNumber, 3, "first field is the `err` oneof arm (3) -- corr_id==0 correctly omitted");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "err-arm payload length decodes");

  size_t innerPos = 0;
  const uint8_t* inner = buf + pos;
  checkTrue(WireRuntime::decodeTag(inner, payloadLen, &innerPos, &fieldNumber, &wt), "Error.code tag decodes");
  checkU64Eq(fieldNumber, 1, "Error.code field number is 1");
  uint64_t code = 0;
  checkTrue(WireRuntime::decodeVarint(inner, payloadLen, &innerPos, &code), "Error.code value decodes");
  checkU64Eq(code, static_cast<uint64_t>(msg::ErrCode::ERR_RANGE), "Error.code round-trips");

  checkTrue(WireRuntime::decodeTag(inner, payloadLen, &innerPos, &fieldNumber, &wt), "Error.field tag decodes");
  uint64_t fieldVal = 0;
  checkTrue(WireRuntime::decodeVarint(inner, payloadLen, &innerPos, &fieldVal), "Error.field value decodes");
  checkU64Eq(fieldVal, 4, "Error.field round-trips");
}

void scenarioEncodeDeviceIdStringRoundTrip() {
  beginScenario("encode(): ReplyEnvelope{id=DeviceId{...}} strings round-trip (cross-checked via decode())");
  msg::ReplyEnvelope reply;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::ID;
  std::strncpy(reply.body.id.model, "NEZHA2", sizeof(reply.body.id.model));
  std::strncpy(reply.body.id.name, "bot1", sizeof(reply.body.id.name));
  reply.body.id.serial = 424242;
  std::strncpy(reply.body.id.fw_version, "1.2.3", sizeof(reply.body.id.fw_version));
  reply.body.id.proto_version = 3;

  uint8_t buf[220] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");
  checkTrue(n <= msg::wire::kReplyEnvelopeMaxEncodedSize, "encoded length stays within kReplyEnvelopeMaxEncodedSize");

  // Extract the `id` oneof arm's inner DeviceId payload bytes (field 7,
  // length-delimited), then re-wrap those SAME bytes as CommandEnvelope's
  // OWN `id` arm (field 14 -- both arms share kTable_DeviceId, so a
  // standalone DeviceId payload's bytes are identical regardless of which
  // parent field number wraps it) and decode() it -- this proves the
  // ENCODE-side string/scalar handling round-trips through the
  // already-verified DECODE path, without needing a second, redundant
  // hand-rolled reference decoder for every DeviceId field.
  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "id-arm tag decodes");
  checkU64Eq(fieldNumber, 7, "first field is the `id` oneof arm (7) -- corr_id==0 correctly omitted");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "id-arm payload length decodes");

  Buf deviceIdPayload;
  std::memcpy(deviceIdPayload.data, buf + pos, payloadLen);
  deviceIdPayload.len = payloadLen;

  Buf env;
  putMessageField(env, 14, deviceIdPayload);  // CommandEnvelope.cmd.id, field 14

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "re-wrapped DeviceId payload decodes cleanly");
  checkStrEq(out.cmd.id.model, "NEZHA2", "DeviceId.model round-trips through encode()+decode()");
  checkStrEq(out.cmd.id.name, "bot1", "DeviceId.name round-trips");
  checkU64Eq(out.cmd.id.serial, 424242, "DeviceId.serial round-trips");
  checkStrEq(out.cmd.id.fw_version, "1.2.3", "DeviceId.fw_version round-trips");
  checkU64Eq(out.cmd.id.proto_version, 3, "DeviceId.proto_version round-trips");
}

void scenarioEncodeOversizedBufferReturnsZero() {
  beginScenario("encode(): returns 0 (not a truncated buffer) when cap is too small");
  msg::ReplyEnvelope reply;
  reply.corr_id = 1;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::ID;
  std::strncpy(reply.body.id.model, "NEZHA2", sizeof(reply.body.id.model));
  std::strncpy(reply.body.id.name, "bot1", sizeof(reply.body.id.name));
  reply.body.id.serial = 1;
  std::strncpy(reply.body.id.fw_version, "1.2.3", sizeof(reply.body.id.fw_version));

  // A DeviceId-bearing reply needs well over a handful of bytes -- 4 is
  // nowhere near enough.
  uint8_t tinyBuf[4] = {0xAA, 0xAA, 0xAA, 0xAA};
  uint16_t n = msg::wire::encode(reply, tinyBuf, sizeof(tinyBuf));
  checkU64Eq(n, 0, "encode returns 0 for a too-small destination buffer");

  // Zero-capacity buffer, as a boundary case.
  uint16_t n0 = msg::wire::encode(reply, tinyBuf, 0);
  checkU64Eq(n0, 0, "encode returns 0 for cap==0");
}

}  // namespace

int main() {
  scenarioRoundTripDrive();
  scenarioRoundTripDriveWheelsRepeated();
  scenarioRepeatedFieldMaxCountClamp();
  scenarioRoundTripSegmentAndReplace();
  scenarioRoundTripStopPingEcho();
  scenarioRoundTripId();
  scenarioRoundTripDeclaredOnlyPoseAndOtos();
  scenarioMissingReqRejected();
  scenarioMinMaxRejected();
  scenarioAbsMaxRejected();
  scenarioUnknownFieldSkipped();
  scenarioEncodeAckHandParsed();
  scenarioEncodeErrorHandParsed();
  scenarioEncodeDeviceIdStringRoundTrip();
  scenarioEncodeOversizedBufferReturnsZero();

  if (g_failureCount == 0) {
    std::printf("OK: all wire codec scenarios passed\n");
    return 0;
  }
  std::printf("FAILED: %d assertion(s) across the wire codec scenarios\n", g_failureCount);
  return 1;
}
