// wire_codec_harness.cpp -- off-hardware acceptance harness for
// msg::wire::decode()/encode() (source/messages/wire.{h,cpp}, GENERATED by
// scripts/gen_messages.py from the P4-pruned protos/envelope.proto +
// protos/telemetry.proto -- 103-001, SUC-001, architecture-update.md (103)
// Decisions 2/3). Rewritten this ticket against the pruned arm set:
// CommandEnvelope.cmd is exactly {twist, config, stop}; ReplyEnvelope.body
// is exactly {ok, err, tlm}; Telemetry carries the depth-3 ack ring +
// fault_bits/event_bits; TelemetrySecondary rides its own independently-
// armored `*B` line (its own `msg::wire::encode()` overload, not a
// ReplyEnvelope oneof arm -- Decision 3).
//
// Every pre-103 arm (drive/segment/replace/pose_fix/otos/ping/echo/get/
// stream/id/hello/ver/help/plan_dump) is GONE from the schema -- scenarios
// that exercised them (and the (req)/(min)/(max)/(abs_max)-validated
// fields that lived only on those removed arms, e.g. ConfigGet.target's
// (req) and MotionSegment's (min)/(max)/(abs_max)) have no field left to
// exercise in the pruned reachable set and are dropped, not ported. The
// generic decodeInto()/encodeInto() engine still supports those flags
// generically (untouched by this prune); this ticket's own real-bytes
// coverage below is the malformed-buffer/unknown-field-skip scenarios
// plus round-trip/encode coverage of every live arm.
//
// This is DISTINCT from the differential-against-google.protobuf suite
// (test_wire_differential.py/_wire_diff_driver.py) -- this harness checks
// the generic engine's OWN behavior in isolation, by hand-building wire
// bytes with WireRuntime's own primitives (the same primitives wire.cpp's
// generated decode()/encode() are built on) and asserting
// msg::wire::decode()'s resulting struct fields, or by hand-parsing
// msg::wire::encode()'s output.
//
// Mirrors wire_runtime_harness.cpp's exact pattern: hand-rolled assertions,
// prints PASS/FAIL, exits nonzero on any failure. Run by test_wire_codec.py
// via subprocess.
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "messages/envelope.h"
#include "messages/wire.h"
#include "messages/wire_runtime.h"

namespace {

using WireRuntime::WireType;

// --- Hand-rolled assertion plumbing (same tiny shape as
// wire_runtime_harness.cpp / runtime_blackboard_harness.cpp). ---

int g_failureCount = 0;
std::string g_scenarioName;

void beginScenario(const std::string& name) {
  g_scenarioName = name;
  std::printf("--- %s\n", name.c_str());
}

void fail(const std::string& what) {
  ++g_failureCount;
  std::printf("  FAIL [%s]: %s\n", g_scenarioName.c_str(), what.c_str());
}

void checkTrue(bool condition, const std::string& what) {
  if (!condition) fail(what + " -- expected true, got false");
}

void checkFalse(bool condition, const std::string& what) {
  if (condition) fail(what + " -- expected false, got true");
}

void checkU64Eq(uint64_t actual, uint64_t expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %llu, got %llu", what.c_str(),
                  static_cast<unsigned long long>(expected), static_cast<unsigned long long>(actual));
    fail(buf);
  }
}

void checkFloatEq(float actual, float expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %g, got %g", what.c_str(), static_cast<double>(expected),
                  static_cast<double>(actual));
    fail(buf);
  }
}

// --- Hand-rolled wire-byte builder (a tiny buffer + cursor, composed with
// WireRuntime's own primitives -- the SAME primitives wire.cpp's generated
// decode()/encode() are built on) -- lets this harness construct arbitrary
// CommandEnvelope payloads without depending on a generic decode(). ---

struct Buf {
  uint8_t data[256] = {};
  size_t len = 0;
};

bool putVarintField(Buf& b, uint32_t number, uint64_t v) {
  return WireRuntime::encodeTag(number, WireType::kVarint, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeVarint(v, b.data, sizeof(b.data), &b.len);
}

bool putFloatField(Buf& b, uint32_t number, float v) {
  return WireRuntime::encodeTag(number, WireType::kFixed32, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeFloat(v, b.data, sizeof(b.data), &b.len);
}

bool putBytesField(Buf& b, uint32_t number, const uint8_t* payload, size_t payloadLen) {
  if (!WireRuntime::encodeTag(number, WireType::kLengthDelimited, b.data, sizeof(b.data), &b.len)) return false;
  if (!WireRuntime::encodeVarint(payloadLen, b.data, sizeof(b.data), &b.len)) return false;
  if (b.len + payloadLen > sizeof(b.data)) return false;
  std::memcpy(b.data + b.len, payload, payloadLen);
  b.len += payloadLen;
  return true;
}

bool putMessageField(Buf& b, uint32_t number, const Buf& nested) {
  return putBytesField(b, number, nested.data, nested.len);
}

// --- Generic top-level field scanner for the ENCODE-side scenarios below --
// (no generic decode(ReplyEnvelope)/decode(Telemetry) exists this sprint --
// decode() is CommandEnvelope-only, encode() is ReplyEnvelope/
// TelemetrySecondary-only, per wire.h's own asymmetric API). Walks every
// top-level field of a length-delimited buffer into a flat list, tolerant
// of field order (the generator's own FieldDesc table order matches proto
// declaration order today, but this scanner does not assume that).

struct ParsedField {
  uint32_t number = 0;
  WireType type = WireType::kVarint;
  uint64_t varintVal = 0;
  float floatVal = 0.0f;
  const uint8_t* bytes = nullptr;
  size_t bytesLen = 0;
};

std::vector<ParsedField> parseFields(const uint8_t* buf, size_t len) {
  std::vector<ParsedField> out;
  size_t pos = 0;
  while (pos < len) {
    ParsedField pf;
    if (!WireRuntime::decodeTag(buf, len, &pos, &pf.number, &pf.type)) break;
    if (pf.type == WireType::kVarint) {
      if (!WireRuntime::decodeVarint(buf, len, &pos, &pf.varintVal)) break;
    } else if (pf.type == WireType::kFixed32) {
      if (!WireRuntime::decodeFloat(buf, len, &pos, &pf.floatVal)) break;
    } else if (pf.type == WireType::kLengthDelimited) {
      size_t plen = 0;
      if (!WireRuntime::beginLengthDelimited(buf, len, &pos, 0, &plen)) break;
      pf.bytes = buf + pos;
      pf.bytesLen = plen;
      pos += plen;
    } else {
      break;  // kFixed64 unreached by this schema
    }
    out.push_back(pf);
  }
  return out;
}

std::vector<ParsedField> fieldsWithNumber(const std::vector<ParsedField>& fields, uint32_t number) {
  std::vector<ParsedField> out;
  for (const auto& f : fields) {
    if (f.number == number) out.push_back(f);
  }
  return out;
}

// ===========================================================================
// 1. decode() round-trip -- every live CommandEnvelope arm (twist, config,
//    stop).
// ===========================================================================

void scenarioRoundTripTwist() {
  beginScenario("decode(): round-trip twist arm (Twist{v_x, omega, duration})");
  Buf twist;
  putFloatField(twist, 1, 150.0f);   // v_x
  putFloatField(twist, 2, -0.75f);   // omega
  putFloatField(twist, 3, 250.0f);   // duration

  Buf env;
  putVarintField(env, 1, 7);            // corr_id
  putMessageField(env, 19, twist);      // CommandEnvelope.cmd.twist, field 19

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkU64Eq(out.corr_id, 7, "corr_id round-trips");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::TWIST, "cmd_kind == TWIST");
  checkFloatEq(out.cmd.twist.v_x, 150.0f, "twist.v_x round-trips");
  checkFloatEq(out.cmd.twist.omega, -0.75f, "twist.omega round-trips");
  checkFloatEq(out.cmd.twist.duration, 250.0f, "twist.duration round-trips");
}

void scenarioRoundTripStop() {
  beginScenario("decode(): round-trip stop arm (zero-field)");
  Buf env;
  putVarintField(env, 1, 4);        // corr_id
  putMessageField(env, 13, Buf{});  // CommandEnvelope.cmd.stop, field 13, empty payload

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "stop decode succeeds");
  checkU64Eq(out.corr_id, 4, "corr_id round-trips");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::STOP, "cmd_kind == STOP");
}

void scenarioRoundTripConfigDrivetrainPatch() {
  beginScenario("decode(): round-trip config arm -- ConfigDelta{drivetrain=DrivetrainConfigPatch} (2-level nested)");
  Buf patch;
  putFloatField(patch, 1, 150.0f);  // trackwidth
  putFloatField(patch, 2, 0.9f);    // rotational_slip
  Buf config;
  putMessageField(config, 1, patch);  // ConfigDelta.patch.drivetrain, field 1
  Buf env;
  putMessageField(env, 6, config);    // CommandEnvelope.cmd.config, field 6

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "config (2-level nested) decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::CONFIG, "cmd_kind == CONFIG");
  checkTrue(out.cmd.config.patch_kind == msg::ConfigDelta::PatchKind::DRIVETRAIN, "patch_kind == DRIVETRAIN");
  checkTrue(out.cmd.config.patch.drivetrain.trackwidth.has, "trackwidth.has == true");
  checkFloatEq(out.cmd.config.patch.drivetrain.trackwidth.val, 150.0f, "trackwidth round-trips");
  checkTrue(out.cmd.config.patch.drivetrain.rotational_slip.has, "rotational_slip.has == true");
  checkFloatEq(out.cmd.config.patch.drivetrain.rotational_slip.val, 0.9f, "rotational_slip round-trips");
  checkFalse(out.cmd.config.patch.drivetrain.ekf_q_xy.has, "ekf_q_xy.has stays false (never sent)");
}

void scenarioRoundTripConfigWatchdog() {
  beginScenario("decode(): round-trip config arm -- ConfigDelta{watchdog} (scalar oneof arm)");
  Buf config;
  putVarintField(config, 4, 5000);  // ConfigDelta.patch.watchdog, field 4
  Buf env;
  putMessageField(env, 6, config);  // CommandEnvelope.cmd.config, field 6

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "config watchdog decode succeeds");
  checkTrue(out.cmd.config.patch_kind == msg::ConfigDelta::PatchKind::WATCHDOG, "patch_kind == WATCHDOG");
  checkU64Eq(out.cmd.config.patch.watchdog, 5000, "watchdog round-trips");
}

// ===========================================================================
// 2. Unknown-field skip -- forward compatibility (still relevant post-prune:
//    a future arm addition must be skippable by an older build).
// ===========================================================================

void scenarioUnknownFieldSkipped() {
  beginScenario("decode(): unknown top-level field number is skipped, not rejected");
  Buf env;
  putVarintField(env, 1, 3);          // corr_id (known)
  putVarintField(env, 99, 123456);    // unknown field number 99 (varint) -- must be skipped
  putMessageField(env, 13, Buf{});    // stop arm (known), AFTER the unknown field

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds despite the unknown field 99");
  checkU64Eq(out.corr_id, 3, "corr_id (before the unknown field) is unaffected");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::STOP, "cmd_kind == STOP (after the unknown field) is unaffected");
}

// ===========================================================================
// 3. Malformed wire bytes -- decode()'s generic ERR_DECODE path (no
//    (req)/(min)/(max)/(abs_max)-validated field survives the P4 prune to
//    exercise those specific codes; this proves the codec's baseline
//    malformed-input rejection is still intact).
// ===========================================================================

void scenarioMalformedBufferRejected() {
  beginScenario("decode(): truncated wire tag rejected as ERR_DECODE");
  Buf env;
  putVarintField(env, 1, 3);   // corr_id, well-formed
  // Append a truncated varint: the continuation bit (0x80) is set with no
  // following byte, so decodeTag()'s own varint read runs off the buffer.
  env.data[env.len++] = 0x80;

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkFalse(r.ok, "decode rejects a truncated wire tag");
  checkTrue(r.code == msg::ErrCode::ERR_DECODE, "ErrCode is ERR_DECODE for malformed wire bytes");
}

// ===========================================================================
// 4. encode() -- ReplyEnvelope{ok/err/tlm} and the standalone
//    TelemetrySecondary codec, hand-parsed byte-for-byte (or via the
//    generic parseFields() scanner for the larger Telemetry frame).
// ===========================================================================

void scenarioEncodeAckHandParsed() {
  beginScenario("encode(): ReplyEnvelope{ok=Ack{q,rem,t}} -- hand-parsed byte-for-byte");
  msg::ReplyEnvelope reply;
  reply.corr_id = 9;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::OK;
  reply.body.ok.q = 5;
  reply.body.ok.rem = 12.5f;
  reply.body.ok.t = 4242;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds (n > 0)");

  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "corr_id tag decodes");
  checkU64Eq(fieldNumber, 1, "first field is corr_id (1)");
  uint64_t corrId = 0;
  checkTrue(WireRuntime::decodeVarint(buf, n, &pos, &corrId), "corr_id value decodes");
  checkU64Eq(corrId, 9, "corr_id round-trips");

  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "ok-arm tag decodes");
  checkU64Eq(fieldNumber, 2, "second field is the `ok` oneof arm (2)");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "ok-arm payload length decodes");

  auto ackFields = parseFields(buf + pos, payloadLen);
  checkU64Eq(ackFields.size(), 3, "Ack payload has 3 fields (q, rem, t)");
  checkU64Eq(ackFields[0].number, 1, "Ack.q field number is 1");
  checkU64Eq(ackFields[0].varintVal, 5, "Ack.q round-trips");
  checkU64Eq(ackFields[1].number, 2, "Ack.rem field number is 2");
  checkFloatEq(ackFields[1].floatVal, 12.5f, "Ack.rem round-trips");
  checkU64Eq(ackFields[2].number, 3, "Ack.t field number is 3");
  checkU64Eq(ackFields[2].varintVal, 4242, "Ack.t round-trips");
}

void scenarioEncodeErrorHandParsed() {
  beginScenario("encode(): ReplyEnvelope{err=Error{code,field}} -- hand-parsed");
  msg::ReplyEnvelope reply;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::ERR;
  reply.body.err.code = msg::ErrCode::ERR_RANGE;
  reply.body.err.field = 4;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");

  // corr_id == 0 -- implicit presence omits it, so the FIRST field on the
  // wire is the `err` oneof arm (field 3) directly.
  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "err-arm tag decodes");
  checkU64Eq(fieldNumber, 3, "first field is the `err` oneof arm (3) -- corr_id==0 correctly omitted");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "err-arm payload length decodes");

  auto errFields = parseFields(buf + pos, payloadLen);
  checkU64Eq(errFields.size(), 2, "Error payload has 2 fields (code, field)");
  checkU64Eq(errFields[0].varintVal, static_cast<uint64_t>(msg::ErrCode::ERR_RANGE), "Error.code round-trips");
  checkU64Eq(errFields[1].varintVal, 4, "Error.field round-trips");
}

void scenarioEncodeTelemetryAckRingAndBits() {
  beginScenario("encode(): ReplyEnvelope{tlm=Telemetry{acks[3], fault_bits, event_bits, ...}} -- hand-parsed via generic scanner");
  msg::ReplyEnvelope reply;
  reply.corr_id = 11;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::TLM;
  msg::Telemetry& t = reply.body.tlm;
  t.acks_count = 3;
  t.acks_[0] = {101, msg::AckStatus::ACK_STATUS_OK, 0};
  t.acks_[1] = {102, msg::AckStatus::ACK_STATUS_ERR, static_cast<uint32_t>(msg::ErrCode::ERR_RANGE)};
  t.acks_[2] = {103, msg::AckStatus::ACK_STATUS_OK, 0};
  t.now = 5000;
  t.seq = 42;
  t.has_enc = true;
  t.enc_left = 10.0f;
  t.enc_right = -5.0f;
  t.active = true;
  t.conn_left = true;
  t.conn_right = false;  // zero-value -- implicit presence omits it from the wire
  t.fault_bits = 0x1;
  t.event_bits = 0x2;

  uint8_t buf[256] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");
  checkTrue(n <= msg::wire::kReplyEnvelopeMaxEncodedSize, "encoded length stays within kReplyEnvelopeMaxEncodedSize");

  auto topFields = parseFields(buf, n);
  auto tlmArm = fieldsWithNumber(topFields, 4);
  checkU64Eq(tlmArm.size(), 1, "exactly one `tlm` oneof arm (field 4) at the top level");
  checkTrue(!tlmArm.empty() && tlmArm[0].type == WireType::kLengthDelimited, "tlm arm is length-delimited");

  auto tlmFields = tlmArm.empty() ? std::vector<ParsedField>{} : parseFields(tlmArm[0].bytes, tlmArm[0].bytesLen);

  auto acks = fieldsWithNumber(tlmFields, 1);
  checkU64Eq(acks.size(), 3, "ack ring carries exactly 3 entries (depth 3)");
  if (acks.size() == 3) {
    for (size_t i = 0; i < 3; ++i) {
      auto entry = parseFields(acks[i].bytes, acks[i].bytesLen);
      checkTrue(!entry.empty(), "ack ring entry has fields");
    }
    auto entry0 = parseFields(acks[0].bytes, acks[0].bytesLen);
    checkU64Eq(entry0[0].varintVal, 101, "acks[0].corr_id round-trips");
    auto entry1 = parseFields(acks[1].bytes, acks[1].bytesLen);
    checkU64Eq(entry1[0].varintVal, 102, "acks[1].corr_id round-trips");
    checkU64Eq(entry1.size(), 3, "acks[1] carries status+err_code (ACK_STATUS_ERR is nonzero -> present)");
  }

  auto now = fieldsWithNumber(tlmFields, 2);
  checkU64Eq(now.size(), 1, "now (field 2) present");
  if (!now.empty()) checkU64Eq(now[0].varintVal, 5000, "now round-trips");

  auto encLeft = fieldsWithNumber(tlmFields, 6);
  checkU64Eq(encLeft.size(), 1, "enc_left (field 6) present");
  if (!encLeft.empty()) checkFloatEq(encLeft[0].floatVal, 10.0f, "enc_left round-trips");

  auto connRight = fieldsWithNumber(tlmFields, 20);
  checkTrue(connRight.empty(), "conn_right (field 20, false/zero) omitted -- implicit presence");

  auto faultBits = fieldsWithNumber(tlmFields, 21);
  checkU64Eq(faultBits.size(), 1, "fault_bits (field 21) present");
  if (!faultBits.empty()) checkU64Eq(faultBits[0].varintVal, 0x1, "fault_bits round-trips");

  auto eventBits = fieldsWithNumber(tlmFields, 22);
  checkU64Eq(eventBits.size(), 1, "event_bits (field 22) present");
  if (!eventBits.empty()) checkU64Eq(eventBits[0].varintVal, 0x2, "event_bits round-trips");
}

void scenarioEncodeOversizedBufferReturnsZero() {
  beginScenario("encode(): returns 0 (not a truncated buffer) when cap is too small");
  msg::ReplyEnvelope reply;
  reply.corr_id = 1;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::TLM;
  msg::Telemetry& t = reply.body.tlm;
  t.acks_count = 3;
  t.acks_[0] = {1, msg::AckStatus::ACK_STATUS_OK, 0};
  t.acks_[1] = {2, msg::AckStatus::ACK_STATUS_ERR, 3};
  t.acks_[2] = {3, msg::AckStatus::ACK_STATUS_OK, 0};
  t.has_pose = true;
  t.has_otos = true;
  t.otos_connected = true;

  // A ring-populated Telemetry frame needs well over a handful of bytes --
  // 4 is nowhere near enough.
  uint8_t tinyBuf[4] = {0xAA, 0xAA, 0xAA, 0xAA};
  uint16_t n = msg::wire::encode(reply, tinyBuf, sizeof(tinyBuf));
  checkU64Eq(n, 0, "encode returns 0 for a too-small destination buffer");

  // Zero-capacity buffer, as a boundary case.
  uint16_t n0 = msg::wire::encode(reply, tinyBuf, 0);
  checkU64Eq(n0, 0, "encode returns 0 for cap==0");
}

void scenarioEncodeTelemetrySecondary() {
  beginScenario("encode(): TelemetrySecondary -- own independently-armored codec (Decision 3), hand-parsed");
  msg::TelemetrySecondary sec;
  sec.now = 6000;
  sec.has_cmd_vel = true;
  sec.cmd_vel_left = 120.0f;
  sec.cmd_vel_right = -120.0f;
  sec.acc_left = 3.5f;
  sec.acc_right = -1.25f;
  sec.glitch_left = 2;
  sec.glitch_right = 0;
  sec.ts_left = 7000;
  sec.ts_right = 7001;

  uint8_t buf[128] = {};
  uint16_t n = msg::wire::encode(sec, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");
  checkTrue(n <= msg::wire::kTelemetrySecondaryMaxEncodedSize,
            "encoded length stays within kTelemetrySecondaryMaxEncodedSize");

  auto fields = parseFields(buf, n);
  auto now = fieldsWithNumber(fields, 1);
  checkU64Eq(now.size(), 1, "now (field 1) present");
  if (!now.empty()) checkU64Eq(now[0].varintVal, 6000, "now round-trips");

  auto cmdVelLeft = fieldsWithNumber(fields, 3);
  checkU64Eq(cmdVelLeft.size(), 1, "cmd_vel_left (field 3) present");
  if (!cmdVelLeft.empty()) checkFloatEq(cmdVelLeft[0].floatVal, 120.0f, "cmd_vel_left round-trips");

  auto glitchRight = fieldsWithNumber(fields, 8);
  checkTrue(glitchRight.empty(), "glitch_right (field 8, zero) omitted -- implicit presence");

  auto tsRight = fieldsWithNumber(fields, 10);
  checkU64Eq(tsRight.size(), 1, "ts_right (field 10) present");
  if (!tsRight.empty()) checkU64Eq(tsRight[0].varintVal, 7001, "ts_right round-trips");
}

}  // namespace

int main() {
  scenarioRoundTripTwist();
  scenarioRoundTripStop();
  scenarioRoundTripConfigDrivetrainPatch();
  scenarioRoundTripConfigWatchdog();
  scenarioUnknownFieldSkipped();
  scenarioMalformedBufferRejected();
  scenarioEncodeAckHandParsed();
  scenarioEncodeErrorHandParsed();
  scenarioEncodeTelemetryAckRingAndBits();
  scenarioEncodeOversizedBufferReturnsZero();
  scenarioEncodeTelemetrySecondary();

  if (g_failureCount == 0) {
    std::printf("OK: all wire codec scenarios passed\n");
    return 0;
  }
  std::printf("FAILED: %d assertion(s) across the wire codec scenarios\n", g_failureCount);
  return 1;
}
