// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
//
// bridges.h — compile-time compatibility checks between the generated
// message headers (source/messages/*.h) and the existing HAL types.
//
// Usage in firmware TUs:
//   Include this file AFTER the subsystem message headers. It assumes the
//   generated message types are already visible (via messages/common.h etc.)
//   and checks size/layout compatibility with hal/capability/Pose2D.h types.
//
// At ticket 002 the checks are trivially true; they bind tighter in ticket 003
// once the naming is resolved and full static_assert coverage is added.
#pragma once
#include "hal/capability/Pose2D.h"

// The HAL Pose2D struct must remain 3 floats (x, y, h).
static_assert(sizeof(::Pose2D) == sizeof(float) * 3,
              "HAL Pose2D must be 3 floats {x,y,h} — check hal/capability/Pose2D.h");

// The HAL BodyTwist3 struct must remain 3 floats (vx, vy, omega).
static_assert(sizeof(::BodyTwist3) == sizeof(float) * 3,
              "HAL BodyTwist3 must be 3 floats {vx,vy,omega} — check hal/capability/Pose2D.h");

// TODO (ticket 003): add cross-asserts between generated messages/common.h
// Pose2D and the HAL Pose2D once the naming conflict is resolved.
