// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/config.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class ConfigTarget : uint8_t {
    CONFIG_DRIVETRAIN = 0,
    CONFIG_MOTOR_LEFT = 1,
    CONFIG_MOTOR_RIGHT = 2,
    CONFIG_PLANNER = 3,
    CONFIG_WATCHDOG = 4,
};

enum class BoundMotorSide : uint8_t {
    LEFT = 0,
    RIGHT = 1,
};

// DrivetrainConfigPatch
struct DrivetrainConfigPatch {
    Opt<float> trackwidth = {};
    Opt<float> rotational_slip = {};
    Opt<float> ekf_q_xy = {};
    Opt<float> ekf_q_theta = {};
    Opt<float> ekf_r_otos_xy = {};
    Opt<float> ekf_r_otos_theta = {};

    // --- array / optional-string accessors ---
};

// MotorConfigPatch
struct MotorConfigPatch {
    BoundMotorSide side = static_cast<BoundMotorSide>(0);
    Opt<float> travel_calib = {};
    Opt<float> kp = {};
    Opt<float> ki = {};
    Opt<float> kff = {};
    Opt<float> i_max = {};
    Opt<float> kaw = {};

    // --- array / optional-string accessors ---
};

// PlannerConfigPatch
struct PlannerConfigPatch {
    Opt<float> min_speed = {};

    // --- array / optional-string accessors ---
};

}  // namespace msg

