// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/envelope.proto
#pragma once

#include "messages/common.h"
#include "messages/config.h"
#include "messages/drivetrain.h"
#include "messages/motion.h"
#include "messages/odometer.h"
#include "messages/telemetry.h"


namespace msg {

enum class ErrCode : uint8_t {
    ERR_NONE = 0,
    ERR_UNKNOWN = 1,
    ERR_BADARG = 2,
    ERR_RANGE = 3,
    ERR_FULL = 4,
    ERR_DECODE = 5,
    ERR_UNIMPLEMENTED = 6,
    ERR_OVERSIZE = 7,
};

// Ack
struct Ack {
    uint32_t q = 0;
    float rem = 0.0f;
    uint32_t t = 0;

    // --- array / optional-string accessors ---
};

// Error
struct Error {
    ErrCode code = static_cast<ErrCode>(0);
    uint32_t field = 0;

    // --- array / optional-string accessors ---
};

// Ping
struct Ping {

    // --- array / optional-string accessors ---
};

// Hello
struct Hello {

    // --- array / optional-string accessors ---
};

// Ver
struct Ver {

    // --- array / optional-string accessors ---
};

// Help
struct Help {

    // --- array / optional-string accessors ---
};

// HelpText
struct HelpText {
    char text[64] = {};

    // --- array / optional-string accessors ---
};

// Echo
struct Echo {
    uint8_t payload_[64] = {};
    uint8_t payload_count = 0;

    // --- array / optional-string accessors ---
    const uint8_t* payload() const { return payload_; }
    uint8_t payload_count_val() const { return payload_count; }
};

// ConfigGet
struct ConfigGet {
    Opt<ConfigTarget> target = {};

    // --- array / optional-string accessors ---
};

// StreamControl
struct StreamControl {
    bool binary = false;
    uint32_t period = 0;

    // --- array / optional-string accessors ---
};

// Stop
struct Stop {

    // --- array / optional-string accessors ---
};

// DeviceId
struct DeviceId {
    char model[48] = {};
    char name[48] = {};
    uint32_t serial = 0;
    char fw_version[48] = {};
    uint32_t proto_version = 0;

    // --- array / optional-string accessors ---
};

// ConfigDelta
struct ConfigDelta {
    enum class PatchKind : uint8_t {
        NONE = 0,
        DRIVETRAIN = 1,
        MOTOR = 2,
        PLANNER = 3,
        WATCHDOG = 4,
    };
    PatchKind patch_kind = PatchKind::NONE;
    union {
        DrivetrainConfigPatch drivetrain;
        MotorConfigPatch motor;
        PlannerConfigPatch planner;
        uint32_t watchdog;
    } patch = {};


    // --- array / optional-string accessors ---
};

// ConfigSnapshot
struct ConfigSnapshot {
    enum class PatchKind : uint8_t {
        NONE = 0,
        DRIVETRAIN = 1,
        MOTOR = 2,
        PLANNER = 3,
        WATCHDOG = 4,
    };
    PatchKind patch_kind = PatchKind::NONE;
    union {
        DrivetrainConfigPatch drivetrain;
        MotorConfigPatch motor;
        PlannerConfigPatch planner;
        uint32_t watchdog;
    } patch = {};

    ConfigTarget target = static_cast<ConfigTarget>(0);

    // --- array / optional-string accessors ---
};

// EventNotify
struct EventNotify {

    // --- array / optional-string accessors ---
};

// CommandEnvelope
struct CommandEnvelope {
    enum class CmdKind : uint8_t {
        NONE = 0,
        DRIVE = 1,
        SEGMENT = 2,
        REPLACE = 3,
        CONFIG = 4,
        POSE_FIX = 5,
        OTOS = 6,
        PING = 7,
        ECHO = 8,
        GET = 9,
        STREAM = 10,
        STOP = 11,
        ID = 12,
        HELLO = 13,
        VER = 14,
        HELP = 15,
    };
    CmdKind cmd_kind = CmdKind::NONE;
    union {
        DrivetrainCommand drive;
        MotionSegment segment;
        MotionSegment replace;
        ConfigDelta config;
        PoseFix pose_fix;
        OdometerCommand otos;
        Ping ping;
        Echo echo;
        ConfigGet get;
        StreamControl stream;
        Stop stop;
        DeviceId id;
        Hello hello;
        Ver ver;
        Help help;
    } cmd = {};

    uint32_t corr_id = 0;

    // --- array / optional-string accessors ---
};

// ReplyEnvelope
struct ReplyEnvelope {
    enum class BodyKind : uint8_t {
        NONE = 0,
        OK = 1,
        ERR = 2,
        TLM = 3,
        CFG = 4,
        EVT = 5,
        ID = 6,
        ECHO = 7,
        HELPTEXT = 8,
    };
    BodyKind body_kind = BodyKind::NONE;
    union {
        Ack ok;
        Error err;
        Telemetry tlm;
        ConfigSnapshot cfg;
        EventNotify evt;
        DeviceId id;
        Echo echo;
        HelpText helptext;
    } body = {};

    uint32_t corr_id = 0;

    // --- array / optional-string accessors ---
};

}  // namespace msg

