// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/gripper.proto
#pragma once

#include "messages/common.h"


// GripperCommand
struct GripperCommand {
    Opt<float> angle_deg = {};

    // --- getters ---
    const Opt<float>& get_angle_deg() const { return angle_deg; }

    // --- chainable setters (Command/Config only) ---
    GripperCommand& setAngleDeg(float v) {
        angle_deg.has = true; angle_deg.val = v;
        return *this;
    }
};

// GripperState
struct GripperState {
    Opt<float> angle_deg = {};
    bool connected = false;

    // --- getters ---
    const Opt<float>& get_angle_deg() const { return angle_deg; }
    bool get_connected() const { return connected; }
};

// GripperConfig
struct GripperConfig {
    bool has_gripper = false;
    float gripper_offset_mm = 0.0f;
    float min_deg = 0.0f;
    float max_deg = 0.0f;

    // --- getters ---
    bool get_has_gripper() const { return has_gripper; }
    float get_gripper_offset_mm() const { return gripper_offset_mm; }
    float get_min_deg() const { return min_deg; }
    float get_max_deg() const { return max_deg; }

    // --- chainable setters (Command/Config only) ---
    GripperConfig& setHasGripper(bool v) { has_gripper = v; return *this; }
    GripperConfig& setGripperOffsetMm(float v) { gripper_offset_mm = v; return *this; }
    GripperConfig& setMinDeg(float v) { min_deg = v; return *this; }
    GripperConfig& setMaxDeg(float v) { max_deg = v; return *this; }
};

