// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/motor.proto
#pragma once

#include "messages/common.h"


namespace msg {

// MotorCommand
struct MotorCommand {
    enum class ControlKind : uint8_t {
        NONE = 0,
        DUTY_CYCLE = 1,
        VOLTAGE = 2,
        VELOCITY = 3,
        POSITION = 4,
        NEUTRAL = 5,
    };
    ControlKind control_kind = ControlKind::NONE;
    union {
        float duty_cycle;
        float voltage;
        float velocity;
        float position;
        Neutral neutral;
    } control = {};

    Opt<float> feedforward = {};

    // --- getters ---
    ControlKind get_control_kind() const { return control_kind; }
    const Opt<float>& get_feedforward() const { return feedforward; }

    // --- chainable setters (Command/Config only) ---
    MotorCommand& setDutyCycle(float v) {
        control_kind = ControlKind::DUTY_CYCLE;
        control.duty_cycle = v;
        return *this;
    }
    MotorCommand& setVoltage(float v) {
        control_kind = ControlKind::VOLTAGE;
        control.voltage = v;
        return *this;
    }
    MotorCommand& setVelocity(float v) {
        control_kind = ControlKind::VELOCITY;
        control.velocity = v;
        return *this;
    }
    MotorCommand& setPosition(float v) {
        control_kind = ControlKind::POSITION;
        control.position = v;
        return *this;
    }
    MotorCommand& setNeutral(const Neutral& v) {
        control_kind = ControlKind::NEUTRAL;
        control.neutral = v;
        return *this;
    }
    MotorCommand& setFeedforward(float v) {
        feedforward.has = true; feedforward.val = v;
        return *this;
    }
};

// MotorState
struct MotorState {
    bool connected = false;
    Opt<float> position = {};
    Opt<float> velocity = {};
    Opt<float> applied = {};
    Opt<bool> wedged = {};

    // --- getters ---
    bool get_connected() const { return connected; }
    const Opt<float>& get_position() const { return position; }
    const Opt<float>& get_velocity() const { return velocity; }
    const Opt<float>& get_applied() const { return applied; }
    const Opt<bool>& get_wedged() const { return wedged; }
};

// MotorConfig
struct MotorConfig {
    float mm_per_deg = 0.0f;
    int32_t fwd_sign = 0;

    // --- getters ---
    float get_mm_per_deg() const { return mm_per_deg; }
    int32_t get_fwd_sign() const { return fwd_sign; }

    // --- chainable setters (Command/Config only) ---
    MotorConfig& setMmPerDeg(float v) { mm_per_deg = v; return *this; }
    MotorConfig& setFwdSign(int32_t v) { fwd_sign = v; return *this; }
};

// MotorCapabilities
struct MotorCapabilities {
    bool onboard_position = false;
    bool has_encoder = false;

    // --- getters ---
    bool get_onboard_position() const { return onboard_position; }
    bool get_has_encoder() const { return has_encoder; }
};

}  // namespace msg

