// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/planner.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class DriveMode : uint8_t {
    IDLE = 0,
    STREAMING = 1,
    TIMED = 2,
    DISTANCE = 3,
    GO_TO = 4,
    VELOCITY = 5,
};

enum class StopStyle : uint8_t {
    SMOOTH = 0,
    ABRUPT = 1,
};

enum class Origin : uint8_t {
    USER = 0,
    AUTONOMOUS = 1,
};

enum class CmpOp : uint8_t {
    LT = 0,
    GT = 1,
    EQ = 2,
};

enum class StopKind : uint8_t {
    STOP_NONE = 0,
    STOP_TIME = 1,
    STOP_DISTANCE = 2,
    STOP_HEADING = 3,
    STOP_POSITION = 4,
    STOP_SENSOR = 5,
    STOP_COLOR = 6,
    STOP_LINE_ANY = 7,
    STOP_ROTATION = 8,
};

// StopCondition
struct StopCondition {
    StopKind kind = static_cast<StopKind>(0);
    float a = 0.0f;
    float b = 0.0f;
    float ax = 0.0f;
    float ay = 0.0f;
    uint32_t sensor = 0;
    CmpOp cmp = static_cast<CmpOp>(0);

    // --- array / optional-string accessors ---
};

// VelocityGoal
struct VelocityGoal {
    float v_x = 0.0f;
    float v_y = 0.0f;
    float omega = 0.0f;
    uint32_t duration = 0;

    // --- array / optional-string accessors ---
};

// GotoGoal
struct GotoGoal {
    float x = 0.0f;
    float y = 0.0f;
    float speed = 0.0f;

    // --- array / optional-string accessors ---
};

// TurnGoal
struct TurnGoal {
    float heading = 0.0f;
    float speed = 0.0f;

    // --- array / optional-string accessors ---
};

// DistanceGoal
struct DistanceGoal {
    float distance = 0.0f;
    float speed = 0.0f;

    // --- array / optional-string accessors ---
};

// TimedGoal
struct TimedGoal {
    float v_x = 0.0f;
    float omega = 0.0f;
    uint32_t duration = 0;

    // --- array / optional-string accessors ---
};

// RotationGoal
struct RotationGoal {
    float angle = 0.0f;
    float speed = 0.0f;

    // --- array / optional-string accessors ---
};

// StreamGoal
struct StreamGoal {
    float v_x = 0.0f;
    float v_y = 0.0f;
    float omega = 0.0f;

    // --- array / optional-string accessors ---
};

// PlannerCommand
struct PlannerCommand {
    enum class GoalKind : uint8_t {
        NONE = 0,
        VELOCITY = 1,
        GOTO_GOAL = 2,
        TURN = 3,
        DISTANCE = 4,
        TIMED = 5,
        ROTATION = 6,
        STREAM = 7,
        STOP = 8,
    };
    GoalKind goal_kind = GoalKind::NONE;
    union {
        VelocityGoal velocity;
        GotoGoal goto_goal;
        TurnGoal turn;
        DistanceGoal distance;
        TimedGoal timed;
        RotationGoal rotation;
        StreamGoal stream;
        uint8_t stop_v;  // bool
    } goal = {};

    StopCondition stops_[4] = {};
    uint8_t stops_count = 0;
    StopStyle style = static_cast<StopStyle>(0);
    Origin origin = static_cast<Origin>(0);
    char corr_id[64] = {};

    // --- array / optional-string accessors ---
    const StopCondition* stops() const { return stops_; }
    uint8_t stops_count_val() const { return stops_count; }

    // --- chainable setters (Command/Config only) ---
    PlannerCommand& setVelocity(const VelocityGoal& v) {
        goal_kind = GoalKind::VELOCITY;
        goal.velocity = v;
        return *this;
    }
    PlannerCommand& setGotoGoal(const GotoGoal& v) {
        goal_kind = GoalKind::GOTO_GOAL;
        goal.goto_goal = v;
        return *this;
    }
    PlannerCommand& setTurn(const TurnGoal& v) {
        goal_kind = GoalKind::TURN;
        goal.turn = v;
        return *this;
    }
    PlannerCommand& setDistance(const DistanceGoal& v) {
        goal_kind = GoalKind::DISTANCE;
        goal.distance = v;
        return *this;
    }
    PlannerCommand& setTimed(const TimedGoal& v) {
        goal_kind = GoalKind::TIMED;
        goal.timed = v;
        return *this;
    }
    PlannerCommand& setRotation(const RotationGoal& v) {
        goal_kind = GoalKind::ROTATION;
        goal.rotation = v;
        return *this;
    }
    PlannerCommand& setStream(const StreamGoal& v) {
        goal_kind = GoalKind::STREAM;
        goal.stream = v;
        return *this;
    }
    PlannerCommand& setStop(bool v) {
        goal_kind = GoalKind::STOP;
        goal.stop_v = v ? 1 : 0;
        return *this;
    }
    PlannerCommand& clearStops() { stops_count = 0; return *this; }
    PlannerCommand& setStyle(StopStyle v) { style = v; return *this; }
    PlannerCommand& setOrigin(Origin v) { origin = v; return *this; }
    // setCorrId: set corr_id[] directly (char array)
};

// PlannerState
struct PlannerState {
    DriveMode mode = static_cast<DriveMode>(0);
    float target_x = 0.0f;
    float target_y = 0.0f;
    float target_speed = 0.0f;
    float distance_target = 0.0f;
    uint32_t deadline = 0;
    BodyTwist3 body_twist = {};
    bool active = false;

    // --- array / optional-string accessors ---
};

// PlannerConfig
struct PlannerConfig {
    float a_max = 0.0f;
    float a_decel = 0.0f;
    float v_body_max = 0.0f;
    float yaw_rate_max = 0.0f;
    float yaw_acc_max = 0.0f;
    float j_max = 0.0f;
    float yaw_jerk_max = 0.0f;
    float arrive_tol = 0.0f;
    float turn_in_place_gate = 0.0f;
    float min_speed = 0.0f;

    // --- array / optional-string accessors ---

    // --- chainable setters (Command/Config only) ---
    PlannerConfig& setAMax(float v) { a_max = v; return *this; }
    PlannerConfig& setADecel(float v) { a_decel = v; return *this; }
    PlannerConfig& setVBodyMax(float v) { v_body_max = v; return *this; }
    PlannerConfig& setYawRateMax(float v) { yaw_rate_max = v; return *this; }
    PlannerConfig& setYawAccMax(float v) { yaw_acc_max = v; return *this; }
    PlannerConfig& setJMax(float v) { j_max = v; return *this; }
    PlannerConfig& setYawJerkMax(float v) { yaw_jerk_max = v; return *this; }
    PlannerConfig& setArriveTol(float v) { arrive_tol = v; return *this; }
    PlannerConfig& setTurnInPlaceGate(float v) { turn_in_place_gate = v; return *this; }
    PlannerConfig& setMinSpeed(float v) { min_speed = v; return *this; }
};

}  // namespace msg

