// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/planner.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class DriveMode : uint8_t {
    IDLE = 0,
    STREAMING = 1,
    DISTANCE = 3,
    GO_TO = 4,
    VELOCITY = 5,
};

enum class StopStyle : uint8_t {
    SMOOTH = 0,
    ABRUPT = 1,
};

enum class Origin : uint8_t {
    USER = 0,
    AUTONOMOUS = 1,
};

enum class CmpOp : uint8_t {
    LT = 0,
    GT = 1,
    EQ = 2,
};

enum class StopKind : uint8_t {
    STOP_NONE = 0,
    STOP_TIME = 1,
    STOP_DISTANCE = 2,
    STOP_HEADING = 3,
    STOP_POSITION = 4,
    STOP_SENSOR = 5,
    STOP_COLOR = 6,
    STOP_LINE_ANY = 7,
    STOP_ROTATION = 8,
};

// StopCondition
struct StopCondition {
    StopKind kind = static_cast<StopKind>(0);
    float a = 0.0f;
    float b = 0.0f;
    float ax = 0.0f;
    float ay = 0.0f;
    uint32_t sensor = 0;
    CmpOp cmp = static_cast<CmpOp>(0);

    // --- getters ---
    StopKind get_kind() const { return kind; }
    float get_a() const { return a; }
    float get_b() const { return b; }
    float get_ax() const { return ax; }
    float get_ay() const { return ay; }
    uint32_t get_sensor() const { return sensor; }
    CmpOp get_cmp() const { return cmp; }
};

// VelocityGoal
struct VelocityGoal {
    float vx_mmps = 0.0f;
    float vy_mmps = 0.0f;
    float omega_rads = 0.0f;
    uint32_t duration_ms = 0;

    // --- getters ---
    float get_vx_mmps() const { return vx_mmps; }
    float get_vy_mmps() const { return vy_mmps; }
    float get_omega_rads() const { return omega_rads; }
    uint32_t get_duration_ms() const { return duration_ms; }
};

// GotoGoal
struct GotoGoal {
    float x_mm = 0.0f;
    float y_mm = 0.0f;
    float speed_mmps = 0.0f;

    // --- getters ---
    float get_x_mm() const { return x_mm; }
    float get_y_mm() const { return y_mm; }
    float get_speed_mmps() const { return speed_mmps; }
};

// TurnGoal
struct TurnGoal {
    float heading_rad = 0.0f;
    float speed_mmps = 0.0f;

    // --- getters ---
    float get_heading_rad() const { return heading_rad; }
    float get_speed_mmps() const { return speed_mmps; }
};

// DistanceGoal
struct DistanceGoal {
    float distance_mm = 0.0f;
    float speed_mmps = 0.0f;

    // --- getters ---
    float get_distance_mm() const { return distance_mm; }
    float get_speed_mmps() const { return speed_mmps; }
};

// TimedGoal
struct TimedGoal {
    float vx_mmps = 0.0f;
    float omega_rads = 0.0f;
    uint32_t duration_ms = 0;

    // --- getters ---
    float get_vx_mmps() const { return vx_mmps; }
    float get_omega_rads() const { return omega_rads; }
    uint32_t get_duration_ms() const { return duration_ms; }
};

// RotationGoal
struct RotationGoal {
    float angle_rad = 0.0f;
    float speed_mmps = 0.0f;

    // --- getters ---
    float get_angle_rad() const { return angle_rad; }
    float get_speed_mmps() const { return speed_mmps; }
};

// StreamGoal
struct StreamGoal {
    float vx_mmps = 0.0f;
    float vy_mmps = 0.0f;
    float omega_rads = 0.0f;

    // --- getters ---
    float get_vx_mmps() const { return vx_mmps; }
    float get_vy_mmps() const { return vy_mmps; }
    float get_omega_rads() const { return omega_rads; }
};

// PlannerCommand
struct PlannerCommand {
    enum class GoalKind : uint8_t {
        NONE = 0,
        VELOCITY = 1,
        GOTO_GOAL = 2,
        TURN = 3,
        DISTANCE = 4,
        TIMED = 5,
        ROTATION = 6,
        STREAM = 7,
        STOP = 8,
    };
    GoalKind goal_kind = GoalKind::NONE;
    union {
        VelocityGoal velocity;
        GotoGoal goto_goal;
        TurnGoal turn;
        DistanceGoal distance;
        TimedGoal timed;
        RotationGoal rotation;
        StreamGoal stream;
        uint8_t stop_v;  // bool
    } goal = {};

    StopCondition stops_[4] = {};
    uint8_t stops_count = 0;
    StopStyle style = static_cast<StopStyle>(0);
    Origin origin = static_cast<Origin>(0);
    char corr_id[64] = {};

    // --- getters ---
    GoalKind get_goal_kind() const { return goal_kind; }
    const StopCondition* stops() const { return stops_; }
    uint8_t stops_count_val() const { return stops_count; }
    StopStyle get_style() const { return style; }
    Origin get_origin() const { return origin; }
    const char* get_corr_id() const { return corr_id; }

    // --- chainable setters (Command/Config only) ---
    PlannerCommand& setVelocity(const VelocityGoal& v) {
        goal_kind = GoalKind::VELOCITY;
        goal.velocity = v;
        return *this;
    }
    PlannerCommand& setGotoGoal(const GotoGoal& v) {
        goal_kind = GoalKind::GOTO_GOAL;
        goal.goto_goal = v;
        return *this;
    }
    PlannerCommand& setTurn(const TurnGoal& v) {
        goal_kind = GoalKind::TURN;
        goal.turn = v;
        return *this;
    }
    PlannerCommand& setDistance(const DistanceGoal& v) {
        goal_kind = GoalKind::DISTANCE;
        goal.distance = v;
        return *this;
    }
    PlannerCommand& setTimed(const TimedGoal& v) {
        goal_kind = GoalKind::TIMED;
        goal.timed = v;
        return *this;
    }
    PlannerCommand& setRotation(const RotationGoal& v) {
        goal_kind = GoalKind::ROTATION;
        goal.rotation = v;
        return *this;
    }
    PlannerCommand& setStream(const StreamGoal& v) {
        goal_kind = GoalKind::STREAM;
        goal.stream = v;
        return *this;
    }
    PlannerCommand& setStop(bool v) {
        goal_kind = GoalKind::STOP;
        goal.stop_v = v ? 1 : 0;
        return *this;
    }
    PlannerCommand& clearStops() { stops_count = 0; return *this; }
    PlannerCommand& setStyle(StopStyle v) { style = v; return *this; }
    PlannerCommand& setOrigin(Origin v) { origin = v; return *this; }
    // setCorrId: set corr_id[] directly (char array)
};

// PlannerState
struct PlannerState {
    DriveMode mode = static_cast<DriveMode>(0);
    float target_x_mm = 0.0f;
    float target_y_mm = 0.0f;
    float target_speed_mms = 0.0f;
    float distance_target_mm = 0.0f;
    uint32_t deadline_ms = 0;
    BodyTwist3 body_twist = {};
    bool active = false;

    // --- getters ---
    DriveMode get_mode() const { return mode; }
    float get_target_x_mm() const { return target_x_mm; }
    float get_target_y_mm() const { return target_y_mm; }
    float get_target_speed_mms() const { return target_speed_mms; }
    float get_distance_target_mm() const { return distance_target_mm; }
    uint32_t get_deadline_ms() const { return deadline_ms; }
    const BodyTwist3& get_body_twist() const { return body_twist; }
    bool get_active() const { return active; }
};

// PlannerConfig
struct PlannerConfig {
    float a_max = 0.0f;
    float a_decel = 0.0f;
    float v_body_max = 0.0f;
    float yaw_rate_max = 0.0f;
    float yaw_acc_max = 0.0f;
    float j_max = 0.0f;
    float yaw_jerk_max = 0.0f;
    float arrive_tol_mm = 0.0f;
    float turn_in_place_gate = 0.0f;
    float turn_threshold_mm = 0.0f;
    float done_tol_mm = 0.0f;
    float min_speed_mms = 0.0f;

    // --- getters ---
    float get_a_max() const { return a_max; }
    float get_a_decel() const { return a_decel; }
    float get_v_body_max() const { return v_body_max; }
    float get_yaw_rate_max() const { return yaw_rate_max; }
    float get_yaw_acc_max() const { return yaw_acc_max; }
    float get_j_max() const { return j_max; }
    float get_yaw_jerk_max() const { return yaw_jerk_max; }
    float get_arrive_tol_mm() const { return arrive_tol_mm; }
    float get_turn_in_place_gate() const { return turn_in_place_gate; }
    float get_turn_threshold_mm() const { return turn_threshold_mm; }
    float get_done_tol_mm() const { return done_tol_mm; }
    float get_min_speed_mms() const { return min_speed_mms; }

    // --- chainable setters (Command/Config only) ---
    PlannerConfig& setAMax(float v) { a_max = v; return *this; }
    PlannerConfig& setADecel(float v) { a_decel = v; return *this; }
    PlannerConfig& setVBodyMax(float v) { v_body_max = v; return *this; }
    PlannerConfig& setYawRateMax(float v) { yaw_rate_max = v; return *this; }
    PlannerConfig& setYawAccMax(float v) { yaw_acc_max = v; return *this; }
    PlannerConfig& setJMax(float v) { j_max = v; return *this; }
    PlannerConfig& setYawJerkMax(float v) { yaw_jerk_max = v; return *this; }
    PlannerConfig& setArriveTolMm(float v) { arrive_tol_mm = v; return *this; }
    PlannerConfig& setTurnInPlaceGate(float v) { turn_in_place_gate = v; return *this; }
    PlannerConfig& setTurnThresholdMm(float v) { turn_threshold_mm = v; return *this; }
    PlannerConfig& setDoneTolMm(float v) { done_tol_mm = v; return *this; }
    PlannerConfig& setMinSpeedMms(float v) { min_speed_mms = v; return *this; }
};

}  // namespace msg

