// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/sensors.proto
#pragma once

#include "messages/common.h"


namespace msg {

// LineSensorState
struct LineSensorState {
    uint32_t raw_[4] = {};
    uint8_t raw_count = 0;
    uint32_t normalized_[4] = {};
    uint8_t normalized_count = 0;
    ValueSet stamp = {};
    bool connected = false;

    // --- getters ---
    const uint32_t* raw() const { return raw_; }
    uint8_t raw_count_val() const { return raw_count; }
    const uint32_t* normalized() const { return normalized_; }
    uint8_t normalized_count_val() const { return normalized_count; }
    const ValueSet& get_stamp() const { return stamp; }
    bool get_connected() const { return connected; }
};

// LineSensorConfig
struct LineSensorConfig {
    uint32_t lag_line = 0;
    uint32_t cal_min_[4] = {};
    uint8_t cal_min_count = 0;
    uint32_t cal_max_[4] = {};
    uint8_t cal_max_count = 0;
    float filt_alpha = 0.0f;

    // --- getters ---
    uint32_t get_lag_line() const { return lag_line; }
    const uint32_t* cal_min() const { return cal_min_; }
    uint8_t cal_min_count_val() const { return cal_min_count; }
    const uint32_t* cal_max() const { return cal_max_; }
    uint8_t cal_max_count_val() const { return cal_max_count; }
    float get_filt_alpha() const { return filt_alpha; }

    // --- chainable setters (Command/Config only) ---
    LineSensorConfig& setLagLine(uint32_t v) { lag_line = v; return *this; }
    LineSensorConfig& clearCalMin() { cal_min_count = 0; return *this; }
    LineSensorConfig& clearCalMax() { cal_max_count = 0; return *this; }
    LineSensorConfig& setFiltAlpha(float v) { filt_alpha = v; return *this; }
};

// ColorSensorState
struct ColorSensorState {
    uint32_t r = 0;
    uint32_t g = 0;
    uint32_t b = 0;
    uint32_t c = 0;
    ValueSet stamp = {};
    bool connected = false;

    // --- getters ---
    uint32_t get_r() const { return r; }
    uint32_t get_g() const { return g; }
    uint32_t get_b() const { return b; }
    uint32_t get_c() const { return c; }
    const ValueSet& get_stamp() const { return stamp; }
    bool get_connected() const { return connected; }
};

// ColorSensorConfig
struct ColorSensorConfig {
    uint32_t lag_color = 0;
    uint32_t integration = 0;
    uint32_t gain = 0;

    // --- getters ---
    uint32_t get_lag_color() const { return lag_color; }
    uint32_t get_integration() const { return integration; }
    uint32_t get_gain() const { return gain; }

    // --- chainable setters (Command/Config only) ---
    ColorSensorConfig& setLagColor(uint32_t v) { lag_color = v; return *this; }
    ColorSensorConfig& setIntegration(uint32_t v) { integration = v; return *this; }
    ColorSensorConfig& setGain(uint32_t v) { gain = v; return *this; }
};

}  // namespace msg

