// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Generated envelope codec implementation (095-005, M4). The FieldKind/
// ScalarType/FieldDesc/MessageTable types and the decodeInto()/
// encodeInto()/encodeNestedMessage() generic walkers below are EMITTED
// VERBATIM by gen_messages.py (identical on every regeneration -- this is
// schema-INDEPENDENT engine code, unlike the per-message kFields_*/kTable_*
// tables further down, which ARE regenerated from the current
// protos/*.proto schema every run). It lives here rather than in
// wire_runtime.{h,cpp} (M3) because M3's own header comment draws the line:
// M3 "knows nothing about field numbers, offsets, or bounds belonging to
// any specific message -- that is M4's job" -- FieldDesc/MessageTable and
// the code that walks them ARE that job, even though the walker's own text
// happens to be schema-agnostic (only the DATA varies per message). See
// wire.h's header comment for the offsetof/C++17-vs-C++11 and
// float-vs-double (Open Question 1) notes.
#include "messages/wire.h"

#include <cstddef>
#include <cstring>

#include "messages/wire_runtime.h"

namespace msg {
namespace wire {

namespace {

// --- Generic field-table types -------------------------------------------

enum class FieldKind : uint8_t {
  kScalar,          // plain (non-oneof, non-Opt) scalar/enum field
  kOpt,             // Opt<T> (proto3 `optional` scalar)
  kOneofScalar,     // scalar/enum member of a real oneof union
  kMessage,         // plain (non-oneof) nested-message field (unreached by
                     // this sprint's schema -- every message-typed field
                     // reachable from CommandEnvelope/ReplyEnvelope is a
                     // oneof member or a repeated element -- kept for
                     // engine completeness/future schema growth)
  kOneofMessage,    // nested-message member of a real oneof union
  kString,          // fixed-capacity char[N] (non-oneof, non-Opt)
  kBytes,           // fixed-capacity uint8_t[N] + count (Echo.payload)
  kRepeatedScalar,  // T[N] + count, PACKED on the wire (unreached by this
                     // sprint's schema -- kept for engine completeness)
  kRepeatedMessage, // T[N] + count, each element separately tagged
                     // (WheelTargets.w -- the repeated field this sprint's
                     // schema actually reaches)
};

enum class ScalarType : uint8_t {
  kNone = 0,
  kFloat,
  kDouble,
  kInt32,
  kInt64,
  kUint32,
  kUint64,
  kBool,
  kEnum,
};

// FieldDesc: one entry per proto field, offsetof-based (see wire.h's header
// comment for the standard-layout/offsetof/C++17 discussion). `minVal`/
// `maxVal`/`absMaxVal` are `float` (Open Question 1). `flags` bits:
// kHasMin=0x01, kHasMax=0x02, kHasAbsMax=0x04, kIsReq=0x08.
struct FieldDesc {
  uint16_t number;
  WireRuntime::WireType wireType;
  FieldKind kind;
  ScalarType scalarType;
  uint16_t offset;         // primary data offset (meaning depends on `kind` -- see decodeInto/encodeInto)
  uint16_t offset2;        // secondary offset: Opt<T>.val / oneof `_kind` discriminator / count field
  uint16_t oneofKindValue; // discriminator value this field's oneof arm sets (kOneofScalar/kOneofMessage only)
  uint16_t cap;            // capacity: char[N]/uint8_t[N] width, or a repeated field's max_count
  uint8_t tableIndex;      // index into kMessageTables[] (kMessage/kOneofMessage/kRepeatedMessage only); 0xFF = n/a
  uint16_t elemStride;     // sizeof(element) for repeated fields; 0 = n/a
  uint8_t flags;
  float minVal;
  float maxVal;
  float absMaxVal;
};

struct MessageTable {
  const FieldDesc* fields;
  uint8_t fieldCount;
};

constexpr uint8_t kHasMin = 0x01;
constexpr uint8_t kHasMax = 0x02;
constexpr uint8_t kHasAbsMax = 0x04;
constexpr uint8_t kIsReq = 0x08;

// Bound sized generously above every struct's actual field count in this
// schema (CommandEnvelope's own table, the largest, has 12 entries) -- used
// to size the decode-time "which fields have we seen" bitmap for the (req)
// completeness check.
constexpr int kMaxFieldsPerMessage = 32;

// --- Scalar read/write/compare helpers ------------------------------------

bool decodeScalarValue(ScalarType type, const uint8_t* buf, size_t len, size_t* pos, void* dst) {
  switch (type) {
    case ScalarType::kFloat: {
      float v;
      if (!WireRuntime::decodeFloat(buf, len, pos, &v)) return false;
      std::memcpy(dst, &v, sizeof(v));
      return true;
    }
    case ScalarType::kDouble:
      // fixed64/double is unreached from CommandEnvelope/ReplyEnvelope in
      // this sprint's schema (every bounded/float field is a protobuf
      // `float`, per wire_runtime.h's own item-3 note) and WireRuntime (M3)
      // has no decodeFixed64 primitive to build on -- reject cleanly rather
      // than mis-decode if a future schema adds a double field before M3
      // grows the primitive.
      return false;
    case ScalarType::kBool:
    case ScalarType::kEnum: {
      uint64_t v;
      if (!WireRuntime::decodeVarint(buf, len, pos, &v)) return false;
      *static_cast<uint8_t*>(dst) = static_cast<uint8_t>(v);
      return true;
    }
    case ScalarType::kInt32: {
      uint64_t v;
      if (!WireRuntime::decodeVarint(buf, len, pos, &v)) return false;
      int32_t sv = static_cast<int32_t>(static_cast<uint32_t>(v));
      std::memcpy(dst, &sv, sizeof(sv));
      return true;
    }
    case ScalarType::kUint32: {
      uint64_t v;
      if (!WireRuntime::decodeVarint(buf, len, pos, &v)) return false;
      uint32_t uv = static_cast<uint32_t>(v);
      std::memcpy(dst, &uv, sizeof(uv));
      return true;
    }
    case ScalarType::kInt64: {
      uint64_t v;
      if (!WireRuntime::decodeVarint(buf, len, pos, &v)) return false;
      int64_t sv = static_cast<int64_t>(v);
      std::memcpy(dst, &sv, sizeof(sv));
      return true;
    }
    case ScalarType::kUint64: {
      uint64_t v;
      if (!WireRuntime::decodeVarint(buf, len, pos, &v)) return false;
      std::memcpy(dst, &v, sizeof(v));
      return true;
    }
    case ScalarType::kNone:
      return false;
  }
  return false;
}

bool encodeScalarValue(ScalarType type, const void* src, uint8_t* buf, size_t cap, size_t* pos) {
  switch (type) {
    case ScalarType::kFloat: {
      float v;
      std::memcpy(&v, src, sizeof(v));
      return WireRuntime::encodeFloat(v, buf, cap, pos);
    }
    case ScalarType::kDouble:
      return false;  // see decodeScalarValue's kDouble note
    case ScalarType::kBool:
    case ScalarType::kEnum: {
      uint8_t v = *static_cast<const uint8_t*>(src);
      return WireRuntime::encodeVarint(v, buf, cap, pos);
    }
    case ScalarType::kInt32: {
      int32_t v;
      std::memcpy(&v, src, sizeof(v));
      // protobuf's own int32 gotcha: a NEGATIVE int32 is sign-extended to
      // 64 bits before varint encoding (unless the field is sint32, which
      // this schema does not use) -- mirrored via the int64 cast.
      return WireRuntime::encodeVarint(static_cast<uint64_t>(static_cast<int64_t>(v)), buf, cap, pos);
    }
    case ScalarType::kUint32: {
      uint32_t v;
      std::memcpy(&v, src, sizeof(v));
      return WireRuntime::encodeVarint(v, buf, cap, pos);
    }
    case ScalarType::kInt64: {
      int64_t v;
      std::memcpy(&v, src, sizeof(v));
      return WireRuntime::encodeVarint(static_cast<uint64_t>(v), buf, cap, pos);
    }
    case ScalarType::kUint64: {
      uint64_t v;
      std::memcpy(&v, src, sizeof(v));
      return WireRuntime::encodeVarint(v, buf, cap, pos);
    }
    case ScalarType::kNone:
      return false;
  }
  return false;
}

// True if `src` holds this scalar type's zero/default value -- proto3
// implicit presence: encodeInto() omits a plain (non-oneof, non-Opt) scalar
// field from the wire when this is true, exactly as a real protobuf encoder
// would (needed for ticket 006's differential fuzz suite to see byte-
// identical output against google.protobuf).
bool scalarIsDefault(ScalarType type, const void* src) {
  switch (type) {
    case ScalarType::kFloat: {
      float v;
      std::memcpy(&v, src, sizeof(v));
      return v == 0.0f;
    }
    case ScalarType::kDouble:
      return true;
    case ScalarType::kBool:
    case ScalarType::kEnum:
      return *static_cast<const uint8_t*>(src) == 0;
    case ScalarType::kInt32: {
      int32_t v;
      std::memcpy(&v, src, sizeof(v));
      return v == 0;
    }
    case ScalarType::kUint32: {
      uint32_t v;
      std::memcpy(&v, src, sizeof(v));
      return v == 0;
    }
    case ScalarType::kInt64: {
      int64_t v;
      std::memcpy(&v, src, sizeof(v));
      return v == 0;
    }
    case ScalarType::kUint64: {
      uint64_t v;
      std::memcpy(&v, src, sizeof(v));
      return v == 0;
    }
    case ScalarType::kNone:
      return true;
  }
  return true;
}

double scalarAsDouble(ScalarType type, const void* src) {
  switch (type) {
    case ScalarType::kFloat: {
      float v;
      std::memcpy(&v, src, sizeof(v));
      return static_cast<double>(v);
    }
    case ScalarType::kDouble: {
      double v;
      std::memcpy(&v, src, sizeof(v));
      return v;
    }
    case ScalarType::kBool:
    case ScalarType::kEnum:
      return static_cast<double>(*static_cast<const uint8_t*>(src));
    case ScalarType::kInt32: {
      int32_t v;
      std::memcpy(&v, src, sizeof(v));
      return static_cast<double>(v);
    }
    case ScalarType::kUint32: {
      uint32_t v;
      std::memcpy(&v, src, sizeof(v));
      return static_cast<double>(v);
    }
    case ScalarType::kInt64: {
      int64_t v;
      std::memcpy(&v, src, sizeof(v));
      return static_cast<double>(v);
    }
    case ScalarType::kUint64: {
      uint64_t v;
      std::memcpy(&v, src, sizeof(v));
      return static_cast<double>(v);
    }
    case ScalarType::kNone:
      return 0.0;
  }
  return 0.0;
}

// Validates (min)/(max)/(abs_max) INLINE during decodeInto()'s single pass
// (no second validation walk) -- returns false on the FIRST bound this
// value violates.
bool validateBounds(const FieldDesc& fd, const void* src) {
  if ((fd.flags & (kHasMin | kHasMax | kHasAbsMax)) == 0) return true;
  const double v = scalarAsDouble(fd.scalarType, src);
  if (fd.flags & kHasAbsMax) {
    const double av = v < 0.0 ? -v : v;
    if (av > static_cast<double>(fd.absMaxVal)) return false;
  }
  if (fd.flags & kHasMin) {
    if (v < static_cast<double>(fd.minVal)) return false;
  }
  if (fd.flags & kHasMax) {
    if (v > static_cast<double>(fd.maxVal)) return false;
  }
  return true;
}

// --- Generated per-message field tables (regenerated from protos/*.proto
// on every run -- everything above this point is fixed engine text,
// everything from here through kMessageTables[] is schema-derived data). --

constexpr FieldDesc kFields_CommandEnvelope[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(CommandEnvelope, corr_id), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // corr_id
    { .number = 6, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(CommandEnvelope, cmd.config), .offset2 = offsetof(CommandEnvelope, cmd_kind), .oneofKindValue = static_cast<uint16_t>(CommandEnvelope::CmdKind::CONFIG), .cap = 0, .tableIndex = 3, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // config
    { .number = 13, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(CommandEnvelope, cmd.stop), .offset2 = offsetof(CommandEnvelope, cmd_kind), .oneofKindValue = static_cast<uint16_t>(CommandEnvelope::CmdKind::STOP), .cap = 0, .tableIndex = 4, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // stop
    { .number = 19, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(CommandEnvelope, cmd.twist), .offset2 = offsetof(CommandEnvelope, cmd_kind), .oneofKindValue = static_cast<uint16_t>(CommandEnvelope::CmdKind::TWIST), .cap = 0, .tableIndex = 5, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // twist
};
constexpr MessageTable kTable_CommandEnvelope = { kFields_CommandEnvelope, 4 };

constexpr FieldDesc kFields_ReplyEnvelope[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(ReplyEnvelope, corr_id), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // corr_id
    { .number = 2, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ReplyEnvelope, body.ok), .offset2 = offsetof(ReplyEnvelope, body_kind), .oneofKindValue = static_cast<uint16_t>(ReplyEnvelope::BodyKind::OK), .cap = 0, .tableIndex = 6, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ok
    { .number = 3, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ReplyEnvelope, body.err), .offset2 = offsetof(ReplyEnvelope, body_kind), .oneofKindValue = static_cast<uint16_t>(ReplyEnvelope::BodyKind::ERR), .cap = 0, .tableIndex = 7, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // err
    { .number = 4, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ReplyEnvelope, body.tlm), .offset2 = offsetof(ReplyEnvelope, body_kind), .oneofKindValue = static_cast<uint16_t>(ReplyEnvelope::BodyKind::TLM), .cap = 0, .tableIndex = 8, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // tlm
};
constexpr MessageTable kTable_ReplyEnvelope = { kFields_ReplyEnvelope, 4 };

constexpr FieldDesc kFields_TelemetrySecondary[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(TelemetrySecondary, now), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // now
    { .number = 2, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(TelemetrySecondary, has_cmd_vel), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_cmd_vel
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(TelemetrySecondary, cmd_vel_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // cmd_vel_left
    { .number = 4, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(TelemetrySecondary, cmd_vel_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // cmd_vel_right
    { .number = 5, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(TelemetrySecondary, acc_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // acc_left
    { .number = 6, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(TelemetrySecondary, acc_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // acc_right
    { .number = 7, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(TelemetrySecondary, glitch_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // glitch_left
    { .number = 8, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(TelemetrySecondary, glitch_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // glitch_right
    { .number = 9, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(TelemetrySecondary, ts_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ts_left
    { .number = 10, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(TelemetrySecondary, ts_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ts_right
};
constexpr MessageTable kTable_TelemetrySecondary = { kFields_TelemetrySecondary, 10 };

constexpr FieldDesc kFields_ConfigDelta[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ConfigDelta, patch.drivetrain), .offset2 = offsetof(ConfigDelta, patch_kind), .oneofKindValue = static_cast<uint16_t>(ConfigDelta::PatchKind::DRIVETRAIN), .cap = 0, .tableIndex = 9, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // drivetrain
    { .number = 2, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ConfigDelta, patch.motor), .offset2 = offsetof(ConfigDelta, patch_kind), .oneofKindValue = static_cast<uint16_t>(ConfigDelta::PatchKind::MOTOR), .cap = 0, .tableIndex = 10, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // motor
    { .number = 3, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kOneofMessage, .scalarType = ScalarType::kNone, .offset = offsetof(ConfigDelta, patch.planner), .offset2 = offsetof(ConfigDelta, patch_kind), .oneofKindValue = static_cast<uint16_t>(ConfigDelta::PatchKind::PLANNER), .cap = 0, .tableIndex = 11, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // planner
    { .number = 4, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kOneofScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(ConfigDelta, patch.watchdog), .offset2 = offsetof(ConfigDelta, patch_kind), .oneofKindValue = static_cast<uint16_t>(ConfigDelta::PatchKind::WATCHDOG), .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // watchdog
};
constexpr MessageTable kTable_ConfigDelta = { kFields_ConfigDelta, 4 };

constexpr MessageTable kTable_Stop = { nullptr, 0 };

constexpr FieldDesc kFields_Twist[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Twist, v_x), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // v_x
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Twist, omega), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // omega
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Twist, duration), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // duration
};
constexpr MessageTable kTable_Twist = { kFields_Twist, 3 };

constexpr FieldDesc kFields_Ack[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Ack, q), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // q
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Ack, rem), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // rem
    { .number = 3, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Ack, t), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // t
};
constexpr MessageTable kTable_Ack = { kFields_Ack, 3 };

constexpr FieldDesc kFields_Error[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kEnum, .offset = offsetof(Error, code), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // code
    { .number = 2, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Error, field), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // field
};
constexpr MessageTable kTable_Error = { kFields_Error, 2 };

constexpr FieldDesc kFields_Telemetry[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kRepeatedMessage, .scalarType = ScalarType::kNone, .offset = offsetof(Telemetry, acks_), .offset2 = offsetof(Telemetry, acks_count), .oneofKindValue = 0, .cap = 3, .tableIndex = 12, .elemStride = sizeof(AckEntry), .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // acks
    { .number = 2, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Telemetry, now), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // now
    { .number = 3, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kEnum, .offset = offsetof(Telemetry, mode), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // mode
    { .number = 4, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Telemetry, seq), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // seq
    { .number = 5, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, has_enc), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_enc
    { .number = 6, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Telemetry, enc_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // enc_left
    { .number = 7, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Telemetry, enc_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // enc_right
    { .number = 8, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, has_vel), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_vel
    { .number = 9, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Telemetry, vel_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // vel_left
    { .number = 10, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Telemetry, vel_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // vel_right
    { .number = 11, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, has_pose), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_pose
    { .number = 12, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kMessage, .scalarType = ScalarType::kNone, .offset = offsetof(Telemetry, pose), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 13, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // pose
    { .number = 13, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, has_otos), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_otos
    { .number = 14, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kMessage, .scalarType = ScalarType::kNone, .offset = offsetof(Telemetry, otos), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 13, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // otos
    { .number = 15, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, otos_connected), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // otos_connected
    { .number = 16, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, has_twist), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // has_twist
    { .number = 17, .wireType = WireRuntime::WireType::kLengthDelimited, .kind = FieldKind::kMessage, .scalarType = ScalarType::kNone, .offset = offsetof(Telemetry, twist), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 14, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // twist
    { .number = 18, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, active), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // active
    { .number = 19, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, conn_left), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // conn_left
    { .number = 20, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kBool, .offset = offsetof(Telemetry, conn_right), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // conn_right
    { .number = 21, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Telemetry, fault_bits), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // fault_bits
    { .number = 22, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(Telemetry, event_bits), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // event_bits
};
constexpr MessageTable kTable_Telemetry = { kFields_Telemetry, 22 };

constexpr FieldDesc kFields_DrivetrainConfigPatch[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, trackwidth.has), .offset2 = offsetof(DrivetrainConfigPatch, trackwidth.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // trackwidth
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, rotational_slip.has), .offset2 = offsetof(DrivetrainConfigPatch, rotational_slip.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // rotational_slip
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_q_xy.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_q_xy.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_q_xy
    { .number = 4, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_q_theta.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_q_theta.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_q_theta
    { .number = 5, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_r_otos_xy.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_r_otos_xy.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_r_otos_xy
    { .number = 6, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_r_otos_theta.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_r_otos_theta.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_r_otos_theta
    { .number = 7, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_r_fix_xy.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_r_fix_xy.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_r_fix_xy
    { .number = 8, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(DrivetrainConfigPatch, ekf_r_fix_theta.has), .offset2 = offsetof(DrivetrainConfigPatch, ekf_r_fix_theta.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ekf_r_fix_theta
};
constexpr MessageTable kTable_DrivetrainConfigPatch = { kFields_DrivetrainConfigPatch, 8 };

constexpr FieldDesc kFields_MotorConfigPatch[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kEnum, .offset = offsetof(MotorConfigPatch, side), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // side
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, travel_calib.has), .offset2 = offsetof(MotorConfigPatch, travel_calib.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // travel_calib
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, kp.has), .offset2 = offsetof(MotorConfigPatch, kp.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // kp
    { .number = 4, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, ki.has), .offset2 = offsetof(MotorConfigPatch, ki.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // ki
    { .number = 5, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, kff.has), .offset2 = offsetof(MotorConfigPatch, kff.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // kff
    { .number = 6, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, i_max.has), .offset2 = offsetof(MotorConfigPatch, i_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // i_max
    { .number = 7, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(MotorConfigPatch, kaw.has), .offset2 = offsetof(MotorConfigPatch, kaw.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // kaw
};
constexpr MessageTable kTable_MotorConfigPatch = { kFields_MotorConfigPatch, 7 };

constexpr FieldDesc kFields_PlannerConfigPatch[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, min_speed.has), .offset2 = offsetof(PlannerConfigPatch, min_speed.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // min_speed
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, heading_kp.has), .offset2 = offsetof(PlannerConfigPatch, heading_kp.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // heading_kp
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, heading_kd.has), .offset2 = offsetof(PlannerConfigPatch, heading_kd.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // heading_kd
    { .number = 4, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, v_wheel_max.has), .offset2 = offsetof(PlannerConfigPatch, v_wheel_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // v_wheel_max
    { .number = 5, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, steer_headroom.has), .offset2 = offsetof(PlannerConfigPatch, steer_headroom.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // steer_headroom
    { .number = 6, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, wheel_step_max.has), .offset2 = offsetof(PlannerConfigPatch, wheel_step_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // wheel_step_max
    { .number = 7, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, track_k_s.has), .offset2 = offsetof(PlannerConfigPatch, track_k_s.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // track_k_s
    { .number = 8, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, track_k_theta.has), .offset2 = offsetof(PlannerConfigPatch, track_k_theta.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // track_k_theta
    { .number = 9, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, track_k_cross.has), .offset2 = offsetof(PlannerConfigPatch, track_k_cross.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // track_k_cross
    { .number = 10, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, trim_v_max.has), .offset2 = offsetof(PlannerConfigPatch, trim_v_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // trim_v_max
    { .number = 11, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, trim_omega_max.has), .offset2 = offsetof(PlannerConfigPatch, trim_omega_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // trim_omega_max
    { .number = 12, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, replan_err_pos.has), .offset2 = offsetof(PlannerConfigPatch, replan_err_pos.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // replan_err_pos
    { .number = 13, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, replan_err_theta.has), .offset2 = offsetof(PlannerConfigPatch, replan_err_theta.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // replan_err_theta
    { .number = 14, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, replan_hold.has), .offset2 = offsetof(PlannerConfigPatch, replan_hold.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // replan_hold
    { .number = 15, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, replan_min_period.has), .offset2 = offsetof(PlannerConfigPatch, replan_min_period.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // replan_min_period
    { .number = 16, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, replan_max.has), .offset2 = offsetof(PlannerConfigPatch, replan_max.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // replan_max
    { .number = 17, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, handoff_tol_pos.has), .offset2 = offsetof(PlannerConfigPatch, handoff_tol_pos.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // handoff_tol_pos
    { .number = 18, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, handoff_tol_v.has), .offset2 = offsetof(PlannerConfigPatch, handoff_tol_v.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // handoff_tol_v
    { .number = 19, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, arrive_vel_tol.has), .offset2 = offsetof(PlannerConfigPatch, arrive_vel_tol.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // arrive_vel_tol
    { .number = 20, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kOpt, .scalarType = ScalarType::kFloat, .offset = offsetof(PlannerConfigPatch, arrive_dwell.has), .offset2 = offsetof(PlannerConfigPatch, arrive_dwell.val), .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // arrive_dwell
};
constexpr MessageTable kTable_PlannerConfigPatch = { kFields_PlannerConfigPatch, 20 };

constexpr FieldDesc kFields_AckEntry[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(AckEntry, corr_id), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // corr_id
    { .number = 2, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kEnum, .offset = offsetof(AckEntry, status), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // status
    { .number = 3, .wireType = WireRuntime::WireType::kVarint, .kind = FieldKind::kScalar, .scalarType = ScalarType::kUint32, .offset = offsetof(AckEntry, err_code), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // err_code
};
constexpr MessageTable kTable_AckEntry = { kFields_AckEntry, 3 };

constexpr FieldDesc kFields_Pose2D[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Pose2D, x), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // x
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Pose2D, y), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // y
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(Pose2D, h), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // h
};
constexpr MessageTable kTable_Pose2D = { kFields_Pose2D, 3 };

constexpr FieldDesc kFields_BodyTwist3[] = {
    { .number = 1, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(BodyTwist3, v_x), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // v_x
    { .number = 2, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(BodyTwist3, v_y), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // v_y
    { .number = 3, .wireType = WireRuntime::WireType::kFixed32, .kind = FieldKind::kScalar, .scalarType = ScalarType::kFloat, .offset = offsetof(BodyTwist3, omega), .offset2 = 0, .oneofKindValue = 0, .cap = 0, .tableIndex = 0xFF, .elemStride = 0, .flags = 0, .minVal = 0.0f, .maxVal = 0.0f, .absMaxVal = 0.0f },  // omega
};
constexpr MessageTable kTable_BodyTwist3 = { kFields_BodyTwist3, 3 };

constexpr MessageTable kMessageTables[] = {
    kTable_CommandEnvelope,  // 0
    kTable_ReplyEnvelope,  // 1
    kTable_TelemetrySecondary,  // 2
    kTable_ConfigDelta,  // 3
    kTable_Stop,  // 4
    kTable_Twist,  // 5
    kTable_Ack,  // 6
    kTable_Error,  // 7
    kTable_Telemetry,  // 8
    kTable_DrivetrainConfigPatch,  // 9
    kTable_MotorConfigPatch,  // 10
    kTable_PlannerConfigPatch,  // 11
    kTable_AckEntry,  // 12
    kTable_Pose2D,  // 13
    kTable_BodyTwist3,  // 14
};

// --- Generic recursive decode/encode walkers ------------------------------
// (fixed engine text again -- kMessageTables[] above is now fully defined,
// so no forward declaration is needed for the mutual nested-message
// recursion below.)

Result decodeInto(void* base, const MessageTable& table, const uint8_t* buf, size_t len, int depth) {
  uint32_t seen = 0;
  uint8_t* const baseBytes = static_cast<uint8_t*>(base);
  size_t pos = 0;

  while (pos < len) {
    uint32_t fieldNumber = 0;
    WireRuntime::WireType wireType = WireRuntime::WireType::kVarint;
    if (!WireRuntime::decodeTag(buf, len, &pos, &fieldNumber, &wireType)) {
      return Result{false, 0, ErrCode::ERR_DECODE};
    }

    const FieldDesc* fd = nullptr;
    int fdIndex = -1;
    for (uint8_t i = 0; i < table.fieldCount; ++i) {
      if (table.fields[i].number == fieldNumber) {
        fd = &table.fields[i];
        fdIndex = static_cast<int>(i);
        break;
      }
    }
    if (fd == nullptr) {
      if (!WireRuntime::skipField(buf, len, &pos, wireType)) return Result{false, 0, ErrCode::ERR_DECODE};
      continue;
    }
    if (fdIndex >= 0 && fdIndex < kMaxFieldsPerMessage) seen |= (1u << fdIndex);

    uint8_t* const fieldPtr = baseBytes + fd->offset;

    switch (fd->kind) {
      case FieldKind::kScalar: {
        if (!decodeScalarValue(fd->scalarType, buf, len, &pos, fieldPtr)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        if (!validateBounds(*fd, fieldPtr)) return Result{false, fd->number, ErrCode::ERR_RANGE};
        break;
      }
      case FieldKind::kOpt: {
        *reinterpret_cast<bool*>(fieldPtr) = true;
        uint8_t* const valPtr = baseBytes + fd->offset2;
        if (!decodeScalarValue(fd->scalarType, buf, len, &pos, valPtr)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        if (!validateBounds(*fd, valPtr)) return Result{false, fd->number, ErrCode::ERR_RANGE};
        break;
      }
      case FieldKind::kOneofScalar: {
        *(baseBytes + fd->offset2) = static_cast<uint8_t>(fd->oneofKindValue);
        if (!decodeScalarValue(fd->scalarType, buf, len, &pos, fieldPtr)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        if (!validateBounds(*fd, fieldPtr)) return Result{false, fd->number, ErrCode::ERR_RANGE};
        break;
      }
      case FieldKind::kMessage:
      case FieldKind::kOneofMessage: {
        if (fd->kind == FieldKind::kOneofMessage) {
          *(baseBytes + fd->offset2) = static_cast<uint8_t>(fd->oneofKindValue);
        }
        size_t payloadLen = 0;
        if (!WireRuntime::beginLengthDelimited(buf, len, &pos, depth, &payloadLen)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        const MessageTable& nested = kMessageTables[fd->tableIndex];
        const Result r = decodeInto(fieldPtr, nested, buf + pos, payloadLen, depth + 1);
        if (!r.ok) return r;
        pos += payloadLen;
        break;
      }
      case FieldKind::kString: {
        size_t payloadLen = 0;
        if (!WireRuntime::beginLengthDelimited(buf, len, &pos, depth, &payloadLen)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        // fd->cap is the array's FULL capacity, including room for the null
        // terminator this decoder always writes.
        if (fd->cap == 0 || payloadLen > static_cast<size_t>(fd->cap) - 1) {
          return Result{false, fd->number, ErrCode::ERR_DECODE};
        }
        std::memcpy(fieldPtr, buf + pos, payloadLen);
        fieldPtr[payloadLen] = '\0';
        pos += payloadLen;
        break;
      }
      case FieldKind::kBytes: {
        size_t payloadLen = 0;
        if (!WireRuntime::beginLengthDelimited(buf, len, &pos, depth, &payloadLen)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        const size_t n = payloadLen < static_cast<size_t>(fd->cap) ? payloadLen : static_cast<size_t>(fd->cap);
        std::memcpy(fieldPtr, buf + pos, n);
        *(baseBytes + fd->offset2) = static_cast<uint8_t>(n);
        pos += payloadLen;
        break;
      }
      case FieldKind::kRepeatedScalar: {
        size_t payloadLen = 0;
        if (!WireRuntime::beginLengthDelimited(buf, len, &pos, depth, &payloadLen)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        uint8_t* const countPtr = baseBytes + fd->offset2;
        size_t outCount = 0;
        const bool ok = (fd->scalarType == ScalarType::kFloat)
                            ? WireRuntime::decodePackedFixed32(buf + pos, payloadLen, reinterpret_cast<float*>(fieldPtr),
                                                                fd->cap, &outCount)
                            : WireRuntime::decodePackedVarint(buf + pos, payloadLen, reinterpret_cast<uint32_t*>(fieldPtr),
                                                               fd->cap, &outCount);
        if (!ok) return Result{false, fd->number, ErrCode::ERR_DECODE};
        *countPtr = static_cast<uint8_t>(outCount);
        pos += payloadLen;
        break;
      }
      case FieldKind::kRepeatedMessage: {
        size_t payloadLen = 0;
        if (!WireRuntime::beginLengthDelimited(buf, len, &pos, depth, &payloadLen)) return Result{false, fd->number, ErrCode::ERR_DECODE};
        uint8_t* const countPtr = baseBytes + fd->offset2;
        const uint8_t count = *countPtr;
        if (count < fd->cap) {
          const MessageTable& nested = kMessageTables[fd->tableIndex];
          uint8_t* const elemPtr = fieldPtr + static_cast<size_t>(count) * fd->elemStride;
          const Result r = decodeInto(elemPtr, nested, buf + pos, payloadLen, depth + 1);
          if (!r.ok) return r;
          *countPtr = static_cast<uint8_t>(count + 1);
        }
        // else: clamped at max_count -- silently dropped, matching
        // WireRuntime's own packed-repeated max_count-clamp convention
        // (095-004). Unlike that packed-scalar reader, a clamped repeated-
        // MESSAGE element's bytes are NOT structurally re-validated here
        // (would need a per-element-type scratch instance the generic
        // offsetof walker does not have) -- a deliberate, documented engine
        // limitation, not an oversight.
        pos += payloadLen;
        break;
      }
    }
  }

  for (uint8_t i = 0; i < table.fieldCount; ++i) {
    if ((table.fields[i].flags & kIsReq) != 0) {
      const bool wasSeen = (i < kMaxFieldsPerMessage) && ((seen >> i) & 1u);
      if (!wasSeen) return Result{false, table.fields[i].number, ErrCode::ERR_BADARG};
    }
  }
  return Result{true, 0, ErrCode::ERR_NONE};
}

// Scratch cap for a nested message's own encoded payload -- comfortably
// above the 186-byte whole-envelope budget (no nested message this schema
// declares can itself approach 186B; the largest, DeviceId, is ~171B and is
// never nested inside another message -- it IS the top-level reply body).
constexpr size_t kEncodeScratchCap = 220;

bool encodeInto(const void* base, const MessageTable& table, uint8_t* buf, size_t cap, size_t* pos);

bool encodeNestedMessage(const FieldDesc& fd, const void* src, uint8_t* buf, size_t cap, size_t* pos) {
  uint8_t scratch[kEncodeScratchCap];
  size_t scratchPos = 0;
  const MessageTable& nested = kMessageTables[fd.tableIndex];
  if (!encodeInto(src, nested, scratch, sizeof(scratch), &scratchPos)) return false;
  if (!WireRuntime::encodeTag(fd.number, WireRuntime::WireType::kLengthDelimited, buf, cap, pos)) return false;
  if (!WireRuntime::encodeVarint(scratchPos, buf, cap, pos)) return false;
  const size_t p = *pos;
  if (cap - p < scratchPos) return false;
  std::memcpy(buf + p, scratch, scratchPos);
  *pos = p + scratchPos;
  return true;
}

bool encodeInto(const void* base, const MessageTable& table, uint8_t* buf, size_t cap, size_t* pos) {
  const uint8_t* const baseBytes = static_cast<const uint8_t*>(base);

  for (uint8_t i = 0; i < table.fieldCount; ++i) {
    const FieldDesc& fd = table.fields[i];
    const uint8_t* const fieldPtr = baseBytes + fd.offset;

    switch (fd.kind) {
      case FieldKind::kScalar: {
        if (scalarIsDefault(fd.scalarType, fieldPtr)) break;  // proto3 implicit presence
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!encodeScalarValue(fd.scalarType, fieldPtr, buf, cap, pos)) return false;
        break;
      }
      case FieldKind::kOpt: {
        if (!*reinterpret_cast<const bool*>(fieldPtr)) break;
        const uint8_t* const valPtr = baseBytes + fd.offset2;
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!encodeScalarValue(fd.scalarType, valPtr, buf, cap, pos)) return false;
        break;
      }
      case FieldKind::kOneofScalar: {
        const uint8_t activeKind = *(baseBytes + fd.offset2);
        if (activeKind != static_cast<uint8_t>(fd.oneofKindValue)) break;
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!encodeScalarValue(fd.scalarType, fieldPtr, buf, cap, pos)) return false;
        break;
      }
      case FieldKind::kOneofMessage: {
        const uint8_t activeKind = *(baseBytes + fd.offset2);
        if (activeKind != static_cast<uint8_t>(fd.oneofKindValue)) break;
        if (!encodeNestedMessage(fd, fieldPtr, buf, cap, pos)) return false;
        break;
      }
      case FieldKind::kMessage: {
        if (!encodeNestedMessage(fd, fieldPtr, buf, cap, pos)) return false;
        break;
      }
      case FieldKind::kString: {
        // 095-006 (SUC-005, differential-suite finding): scan strictly up to
        // `fd.cap - 1`, NEVER `fd.cap` -- the LAST byte of a char[cap] field
        // is reserved for the null terminator by the SAME convention
        // decodeInto()'s own kString case documents and enforces ("fd->cap
        // is the array's FULL capacity, including room for the null
        // terminator"). Scanning through `fd.cap` (the pre-fix bound) reads
        // that reserved byte too: for a MAX-LENGTH string (content ==
        // cap - 1 bytes, e.g. a 47-char DeviceId.model at str_len=48) there
        // is no guaranteed '\0' anywhere in [0, cap), so the scan fell
        // through to the reserved byte and used ITS value -- for a struct
        // that was never round-tripped through decode() (every
        // ReplyEnvelope this sprint IS hand-constructed by firmware code,
        // never decoded; decode() is CommandEnvelope-only per wire.h's own
        // asymmetric API, Decision 4), that reserved byte can be
        // uninitialized (a default-constructed message only zero-initializes
        // the ACTIVE union alternative's own bytes, not a not-yet-active
        // alternative's tail past a smaller sibling -- see decode()'s own
        // 095-006 fix comment above for the general shape of this hazard),
        // leaking 1 byte of stack/heap garbage onto the wire and reporting a
        // length one byte longer than the field's own documented maximum
        // content length. Confirmed via the differential harness: encoding
        // DeviceId{model: 47 'M' characters} emitted a 48-byte string field
        // instead of 47.
        size_t slen = 0;
        while (slen < static_cast<size_t>(fd.cap) - 1 && reinterpret_cast<const char*>(fieldPtr)[slen] != '\0') ++slen;
        if (slen == 0) break;  // proto3 implicit presence
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!WireRuntime::encodeVarint(slen, buf, cap, pos)) return false;
        const size_t p = *pos;
        if (cap - p < slen) return false;
        std::memcpy(buf + p, fieldPtr, slen);
        *pos = p + slen;
        break;
      }
      case FieldKind::kBytes: {
        const uint8_t n = *(baseBytes + fd.offset2);
        if (n == 0) break;  // proto3 implicit presence
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!WireRuntime::encodeVarint(n, buf, cap, pos)) return false;
        const size_t p = *pos;
        if (cap - p < n) return false;
        std::memcpy(buf + p, fieldPtr, n);
        *pos = p + n;
        break;
      }
      case FieldKind::kRepeatedScalar: {
        const uint8_t count = *(baseBytes + fd.offset2);
        if (count == 0) break;
        uint8_t scratch[kEncodeScratchCap];
        size_t scratchPos = 0;
        for (uint8_t e = 0; e < count; ++e) {
          const uint8_t* const elemPtr = fieldPtr + static_cast<size_t>(e) * fd.elemStride;
          if (!encodeScalarValue(fd.scalarType, elemPtr, scratch, sizeof(scratch), &scratchPos)) return false;
        }
        if (!WireRuntime::encodeTag(fd.number, fd.wireType, buf, cap, pos)) return false;
        if (!WireRuntime::encodeVarint(scratchPos, buf, cap, pos)) return false;
        const size_t p = *pos;
        if (cap - p < scratchPos) return false;
        std::memcpy(buf + p, scratch, scratchPos);
        *pos = p + scratchPos;
        break;
      }
      case FieldKind::kRepeatedMessage: {
        const uint8_t count = *(baseBytes + fd.offset2);
        for (uint8_t e = 0; e < count; ++e) {
          const uint8_t* const elemPtr = fieldPtr + static_cast<size_t>(e) * fd.elemStride;
          if (!encodeNestedMessage(fd, elemPtr, buf, cap, pos)) return false;
        }
        break;
      }
    }
  }
  return true;
}

}  // namespace

Result decode(CommandEnvelope& out, const uint8_t* buf, uint16_t len) {
  // 095-006 (SUC-005, differential-suite finding, fixed at the generator so
  // every regeneration carries the fix): `out = CommandEnvelope{}` does NOT
  // zero the whole object. Per the C++ aggregate-init rules for a union
  // data member, `= {}` value-initializes only the union's FIRST named
  // alternative (`cmd.drive`, and recursively `control.twist` inside IT);
  // any union alternative that is not first AND is larger than the first
  // alternative's own size (e.g. `cmd.drive.control.wheels`, a WheelTargets,
  // is far larger than `control`'s first alternative BodyTwist3) has its
  // extra bytes left INDETERMINATE. decodeInto()'s repeated-message clamp
  // (`kRepeatedMessage`) reads that indeterminate byte as the field's
  // starting element COUNT before ever writing to it -- confirmed by the
  // differential harness (095-006) reproducing a decode of a valid 2-element
  // `drive.wheels` envelope that came back with a garbage element count and
  // uninitialized element data, an uninitialized-memory read, not merely a
  // stale-value cosmetic bug. `std::memset` zeroes every byte of `out`
  // (well-defined: CommandEnvelope is standard-layout AND trivially
  // copyable -- ticket 003's day-one gate -- so a full-object memset is the
  // same "zero it all, unconditionally" idiom nanopb/protobuf-c use for the
  // identical union-of-message-types shape), independent of which union
  // alternative ends up decoded. Destination cast to `void*` explicitly:
  // GCC's `-Wclass-memaccess` (part of `-Wall`/`-Wextra`) flags a
  // `memset()`/`memcpy()` whose destination argument's OWN declared type is
  // a non-trivial class -- exactly what CommandEnvelope is, for the same
  // "has default member initializers" reason noted above (ticket 003's own
  // day-one gate: standard-layout AND trivially copyable, but NOT trivial).
  // The warning's usual concern (memset-ing a type with vtables/virtual
  // bases/non-POD members) does not apply here -- ticket 003 already proved
  // this exact property -- but the diagnostic can't see that, only the
  // static type; casting to `void*` states the intent explicitly instead of
  // leaving an unexplained warning at every regeneration.
  std::memset(static_cast<void*>(&out), 0, sizeof(out));
  if (buf == nullptr && len != 0) return Result{false, 0, ErrCode::ERR_DECODE};
  return decodeInto(&out, kTable_CommandEnvelope, buf, static_cast<size_t>(len), 0);
}

uint16_t encode(const ReplyEnvelope& in, uint8_t* buf, uint16_t cap) {
  if (buf == nullptr) return 0;
  size_t pos = 0;
  if (!encodeInto(&in, kTable_ReplyEnvelope, buf, static_cast<size_t>(cap), &pos)) return 0;
  return static_cast<uint16_t>(pos);
}

uint16_t encode(const TelemetrySecondary& in, uint8_t* buf, uint16_t cap) {
  if (buf == nullptr) return 0;
  size_t pos = 0;
  if (!encodeInto(&in, kTable_TelemetrySecondary, buf, static_cast<size_t>(cap), &pos)) return 0;
  return static_cast<uint16_t>(pos);
}

}  // namespace wire
}  // namespace msg
