# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gripper.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gripper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgripper.proto\x12\x05robot\".\n\x0eGripperCommand\x12\x12\n\x05\x61ngle\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_angle\"?\n\x0cGripperState\x12\x12\n\x05\x61ngle\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x11\n\tconnected\x18\x02 \x01(\x08\x42\x08\n\x06_angle\"V\n\rGripperConfig\x12\x13\n\x0bhas_gripper\x18\x01 \x01(\x08\x12\x16\n\x0egripper_offset\x18\x02 \x01(\x02\x12\x0b\n\x03min\x18\x03 \x01(\x02\x12\x0b\n\x03max\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gripper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRIPPERCOMMAND']._serialized_start=24
  _globals['_GRIPPERCOMMAND']._serialized_end=70
  _globals['_GRIPPERSTATE']._serialized_start=72
  _globals['_GRIPPERSTATE']._serialized_end=135
  _globals['_GRIPPERCONFIG']._serialized_start=137
  _globals['_GRIPPERCONFIG']._serialized_end=223
# @@protoc_insertion_point(module_scope)
