# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: odometer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'odometer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eodometer.proto\x12\x05robot\x1a\x0c\x63ommon.proto\"x\n\x0fOdometerCommand\x12\x0e\n\x04init\x18\x01 \x01(\x08H\x00\x12\x0e\n\x04zero\x18\x02 \x01(\x08H\x00\x12\x18\n\x0ereset_tracking\x18\x03 \x01(\x08H\x00\x12!\n\x08set_pose\x18\x04 \x01(\x0b\x32\r.robot.Pose2DH\x00\x42\x08\n\x06\x61\x63tion\"?\n\x0eOdometerConfig\x12\x15\n\rlinear_scalar\x18\x01 \x01(\x02\x12\x16\n\x0e\x61ngular_scalar\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odometer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ODOMETERCOMMAND']._serialized_start=39
  _globals['_ODOMETERCOMMAND']._serialized_end=159
  _globals['_ODOMETERCONFIG']._serialized_start=161
  _globals['_ODOMETERCONFIG']._serialized_end=224
# @@protoc_insertion_point(module_scope)
