#pragma once
// =============================================================================
// SubsystemContract.h — The documented structural convention for all subsystems
//
// C++11 / -fno-rtti / -fno-exceptions / no heap / no STL containers.
// This header is a DOCUMENTATION HEADER only — it defines no compiled symbols.
// Include it in subsystem headers for self-documentation and type aliases.
//
// *** NOT a virtual base class. NOT a C++20 concept. ***
// The constraint is strictly structural: a subsystem that follows the
// convention compiles and works; there is no runtime enforcement.
// (Drive's existing "no virtual dispatch, no SubsystemBase" constraint is
// the canonical source of this decision — see source/subsystems/drive/Drive.h.)
//
// =============================================================================
//
// ## The 3-message / 4-verb contract
//
// Every subsystem S defines three POD message types (generated in namespace
// msg by scripts/gen_messages.py) and exposes four verbs plus capabilities():
//
//   S::Command     // intent   (u) — what to do; staged, not executed
//   S::State       // estimate (x) — what is happening (read-only snapshot)
//   S::Config      // params   (θ) — how to behave; tuning, not wiring
//
//   void            apply(const Command&);     // STAGE only — no execution
//   CommandBatch    tick(uint32_t now);        // ENGINE — per-tick work; ONLY emitter
//   const State&    state() const;             // const-ref to internal State
//   void            configure(const Config&);  // delta-apply params; live-safe
//   Capabilities    capabilities() const;      // declared truth: modes + fields
//
// ### apply() — stage intent, never execute
//
//   apply() writes the desired/pending Command into the subsystem's owned
//   internal command slot and returns nothing. It does NOT touch hardware,
//   does NOT emit to the bus, and does NOT run any control logic. The next
//   tick() reads the staged command, acts on it, and is the ONLY verb that
//   produces outbound commands.
//
// ### tick(now) — the engine; ONLY emitter
//
//   tick(now) does all per-tick work: drives hardware I/O, runs the internal
//   control step, updates the owned State slice and actuator outputs. It
//   returns a CommandBatch — a compact fixed-capacity array of OutCommands
//   addressed to OTHER subsystems. The scheduler drains the returned batch
//   onto the bus and routes it via CommandProcessor. tick() is the ONLY verb
//   that produces outbound commands; apply() never emits anything.
//
// ### state() — const-ref, no I/O, no copy
//
//   state() returns a const reference to the subsystem's internal State,
//   which tick() keeps fresh. No device I/O, no allocation. Callers hold
//   the reference and call getters on it. Pattern: the cached-accessor idiom
//   (IVelocityMotor::position() is the precedent). What tick() *returns*
//   is outbound commands; State is always a getter, never a tick() return.
//
// ### configure(Config) — delta-apply params; live-safe
//
//   configure() applies a Config slice (tuning, mounting offsets, enables).
//   It is safe to call at runtime; the next tick() reads the updated config.
//   Assembly (which devices are wired to which subsystem) is code, not config.
//
// ### capabilities() — declared truth
//
//   Returns the subsystem's declared capability set: which Command modes are
//   accepted, which State fields are populated, holonomic flag, wheel count.
//   For a pure-sensor subsystem (empty command axis) command_modes is empty.
//
// =============================================================================
//
// ## Two-phase Drive / single-phase Sensors
//
// Drive is SPLIT into two phases because I2C is split-phase and the run loop
// must order all sensing BEFORE all actuation:
//
//   void         tickUpdate(uint32_t now);   // SENSE: encoders + OTOS, fusion, refresh State
//   CommandBatch tickAction(uint32_t now);   // ACT:   kinematics → wheel PID → motor outputs
//
// tickAction() carries the CommandBatch return (it is the act/emit phase).
// tickUpdate() only senses and returns void.
//
// This is the same seam AdvantageKit splits into updateInputs/periodic, kept
// under the "tick" name so both halves read as one conceptual verb. The run
// loop calls tickUpdate() early (with all other sensing) and tickAction() late
// (with all actuation).
//
// Sensors is single-phase: tick(now) collects both line and color readings in
// one call. No two-phase split needed — I2C sensor reads are synchronous.
//
// =============================================================================
//
// ## Fluent builder — the primary call-site form
//
// Message types carry chainable setters (generated by gen_messages.py for
// Command and Config types; State types are read-only snapshots). The
// subsystem owns ONE reused internal instance of each Command/Config. The
// primary call-site idiom:
//
//   drive.newCommand().setTwist(vx, vy, omega).apply();
//   sensors.newConfig().setLagMs(20).configure();
//
// newCommand() resets and returns a REFERENCE to the subsystem's internal
// Command instance. Each setX() mutates and returns *this (the generated
// chainable-setter pattern). The terminal apply() commits the staged command.
//
// ONE REUSED INSTANCE, NO ALLOCATION — embedded-friendly. No heap, no RAII,
// no destructor. Suitable for C++11 / -fno-rtti / -fno-exceptions targets.
//
// The underlying data-plane verb apply(const Command&) still exists for
// replayed, logged, or wire-sourced commands (call it directly in those cases).
//
// Usage examples:
//
//   // Drive two-phase tick + state read:
//   drive.tickUpdate(now);
//   drive.tickAction(now);
//   float vx = drive.state().get_fused().get_twist().get_vx_mmps();
//
//   // Fluent command — set a twist:
//   drive.newCommand()
//        .setTwist({10.0f, 0.0f, 0.0f})
//        .apply();
//
//   // Direct apply from a wire-sourced command:
//   drive.apply(cmd);
//
//   // Sensors (read-only, no Command):
//   sensors.tick(now);
//   bool line_connected = sensors.state().line.get_connected();
//
// =============================================================================
//
// ## FluentBuilder<Derived, Msg> — reusable internal-instance helper
//
// Subsystem implementations (tickets 003, 004) inherit from this template to
// acquire newCommand() and newConfig() without repeating the idiom each time.
//
// Usage (in the subsystem implementation header):
//
//   class MySub : public FluentBuilder<MySub, msg::MyCommand,
//                                              msg::MyConfig> { ... };
//
//   // Then call sites work as documented above:
//   mySub.newCommand().setX(v).apply();
//   mySub.newConfig().setY(v).configure();
//
// The Derived CRTP parameter is used to return *this as Derived& from apply()
// and configure(), so the caller receives the subsystem back for any further
// chaining (though the contract does not require that).
//
// =============================================================================

#include "messages/common.h"  // msg::CommandBatch, msg::Capabilities

namespace subsystems {

// ---------------------------------------------------------------------------
// FluentBuilder<Derived, CmdMsg, CfgMsg>
//
// CRTP mixin that provides newCommand() / newConfig() idiom over a single
// reused internal instance of each message type.
//
// Requirements on Derived:
//   void apply(const CmdMsg&)      — the data-plane apply verb
//   void configure(const CfgMsg&)  — the data-plane configure verb
//
// Both are expected to be defined by the concrete subsystem class.
// FluentBuilder does NOT declare them — the linker error on a missing
// definition is the enforcement mechanism (no virtual dispatch).
//
// CmdMsg and CfgMsg must be default-constructible POD types.
// ---------------------------------------------------------------------------
template<class Derived, class CmdMsg, class CfgMsg>
class FluentBuilder {
public:
    // -----------------------------------------------------------------------
    // PendingCommand — proxy returned by newCommand().
    //
    // Resets the internal command slot, then lets the caller chain setters on
    // it. The terminal apply() commits to the subsystem's data-plane verb.
    // The proxy holds a reference to both the message and the Derived
    // subsystem; it does not own either — callers must not store it past the
    // enclosing statement.
    // -----------------------------------------------------------------------
    class PendingCommand {
    public:
        PendingCommand(Derived& sub, CmdMsg& msg) : _sub(sub), _msg(msg) {}

        // Forward any setter that CmdMsg defines, returning *this so chains
        // continue on PendingCommand. Because CmdMsg setters return CmdMsg&,
        // we need a thin forwarder. We use operator-> to expose the raw msg
        // and rely on the fact that all setters return the msg ref — but the
        // simpler approach for C++11 with no variadic magic is to provide
        // direct forwarding of the complete msg via operator*() and
        // specialized apply().
        //
        // To keep the header simple and avoid complex SFINAE, PendingCommand
        // exposes the staged message by reference. Callers chain setters
        // directly on the CmdMsg (which returns CmdMsg&), so the fluent form
        // is:
        //
        //   sub.newCommand().msg().setX(v).setY(v);  // verbose but clear
        //
        // OR — more ergonomically — use the wrapper proxy pattern below where
        // PendingCommand itself delegates unknown calls to the msg. C++11
        // cannot do transparent proxy without inheritance on non-virtual types,
        // so the established convention in this codebase (see generated headers)
        // is: PendingCommand has an explicit apply() terminator and exposes
        // the message as a naked reference for chaining:
        //
        //   sub.newCommand().setTwist(...).apply()
        //
        // We achieve this by having PendingCommand re-expose every setter via
        // delegation, but that defeats the purpose of the helper. The cleanest
        // C++11 approach with ZERO duplication: make PendingCommand derive from
        // CmdMsg by value (copy-on-return) — but that breaks the reuse-instance
        // goal.
        //
        // RESOLUTION: PendingCommand directly IS the CmdMsg reference view.
        // The terminal apply() sends the reused internal instance to Derived.
        // Setters are called on the CmdMsg directly via ref() — which returns
        // the internal instance ref — and then apply() is called:
        //
        //   sub.newCommand().ref().setTwist({10,0,0});
        //   sub.apply(sub.pendingCmd());
        //
        // That is clunky. The BETTER resolution (and what the architecture doc
        // shows) is for PendingCommand to be a thin shim that:
        //   (a) exposes the message by reference (msg()) for direct setter chains, OR
        //   (b) re-exposes each setter with the same name, returning PendingCommand&
        //
        // We choose (b) only for subsystems that have a small, known setter
        // surface (Drive, Sensors — see tickets 003/004). Here in the generic
        // helper we choose (a) — the msg() accessor — and let the concrete
        // subsystem optionally add a thin PendingCommand subclass with typed
        // setter forwarding.
        //
        // FINAL DESIGN (minimal, correct, embedded-friendly):
        //   newCommand() resets _pending_cmd, returns *this PendingCommand.
        //   PendingCommand::apply() calls Derived::apply(_msg).
        //   Caller accesses setters via .msg().setX(...) OR the concrete
        //   subsystem's PendingCommand override adds named forwarders.

        // Access the underlying message for setter chaining.
        CmdMsg& msg() { return _msg; }

        // Terminal verb: commit the staged command to the subsystem.
        Derived& apply() {
            _sub.apply(_msg);
            return _sub;
        }

    private:
        Derived& _sub;
        CmdMsg&  _msg;
    };

    // -----------------------------------------------------------------------
    // PendingConfig — same pattern for configure().
    // -----------------------------------------------------------------------
    class PendingConfig {
    public:
        PendingConfig(Derived& sub, CfgMsg& msg) : _sub(sub), _msg(msg) {}

        CfgMsg& msg() { return _msg; }

        Derived& configure() {
            _sub.configure(_msg);
            return _sub;
        }

    private:
        Derived& _sub;
        CfgMsg&  _msg;
    };

    // -----------------------------------------------------------------------
    // newCommand() — reset internal slot and return a PendingCommand proxy.
    //
    // The internal command is reset to a default-constructed instance so
    // stale fields from a prior call do not bleed through. This is important
    // for tagged-union Command types (e.g. DrivetrainCommand) where control_kind
    // must be reset or the wrong union branch may be read.
    // -----------------------------------------------------------------------
    PendingCommand newCommand() {
        _pending_cmd = CmdMsg{};
        return PendingCommand(static_cast<Derived&>(*this), _pending_cmd);
    }

    // -----------------------------------------------------------------------
    // newConfig() — reset internal config slot and return a PendingConfig.
    // -----------------------------------------------------------------------
    PendingConfig newConfig() {
        _pending_cfg = CfgMsg{};
        return PendingConfig(static_cast<Derived&>(*this), _pending_cfg);
    }

protected:
    CmdMsg _pending_cmd = {};
    CfgMsg _pending_cfg = {};
};

// ---------------------------------------------------------------------------
// SensorFluentBuilder<Derived, CfgMsg>
//
// Variant for pure-sensor subsystems with an EMPTY command axis.
// Provides newConfig() only — no newCommand() / apply() — which correctly
// expresses the "no Command" invariant at the type level without breaking the
// builder idiom.
//
// Usage:
//   class MySensor : public SensorFluentBuilder<MySensor, msg::MyConfig> { ... };
//   mySensor.newConfig().msg().setLagMs(20).configure();
// ---------------------------------------------------------------------------
template<class Derived, class CfgMsg>
class SensorFluentBuilder {
public:
    class PendingConfig {
    public:
        PendingConfig(Derived& sub, CfgMsg& msg) : _sub(sub), _msg(msg) {}

        CfgMsg& msg() { return _msg; }

        Derived& configure() {
            _sub.configure(_msg);
            return _sub;
        }

    private:
        Derived& _sub;
        CfgMsg&  _msg;
    };

    PendingConfig newConfig() {
        _pending_cfg = CfgMsg{};
        return PendingConfig(static_cast<Derived&>(*this), _pending_cfg);
    }

protected:
    CfgMsg _pending_cfg = {};
};

}  // namespace subsystems
