// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/commands.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class Verb : uint8_t {
    VERB_UNSPECIFIED = 0,
    HELLO = 1,
    PING = 2,
    ID = 3,
    VER = 4,
    DEVICE = 5,
    PONG = 6,
    MOVE = 7,
    CONFIG = 8,
    STOP = 9,
    WHEELS = 13,
    ESTOP = 14,
    TLM = 10,
    OK = 11,
    ERR = 12,
};

// VerbEntry -- one row of the closed v5 command-name registry (124-001, sprint 124
// architecture Decision 2): the wire verb name and whether its <data> is binary
// (COBS+CRC-framed) or cleartext. Generated from protos/commands.proto's Verb
// enum + (binary) enum-value option -- the ONE source this table and the host
// wire_commands.py mirror both come from.
struct VerbEntry {
    Verb verb;
    const char* name;
    bool binary;
};

constexpr VerbEntry kVerbTable[14] = {
    { Verb::HELLO, "HELLO", false },
    { Verb::PING, "PING", false },
    { Verb::ID, "ID", false },
    { Verb::VER, "VER", false },
    { Verb::DEVICE, "DEVICE", false },
    { Verb::PONG, "PONG", false },
    { Verb::MOVE, "MOVE", true },
    { Verb::CONFIG, "CONFIG", true },
    { Verb::STOP, "STOP", true },
    { Verb::WHEELS, "WHEELS", true },
    { Verb::ESTOP, "ESTOP", true },
    { Verb::TLM, "TLM", true },
    { Verb::OK, "OK", true },
    { Verb::ERR, "ERR", true },
};
constexpr uint8_t kVerbCount = 14;

}  // namespace msg

