// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/common.proto
#pragma once

#include <stdint.h>

namespace msg {

// Opt<T> — nullable wrapper for proto3 optional fields.
// Replaces std::optional<T> (which requires RTTI / exceptions).
// Target: CODAL C++11, -fno-rtti -fno-exceptions, no heap.
template<class T>
struct Opt { bool has = false; T val{}; };

enum class Neutral : uint8_t {
    BRAKE = 0,
    COAST = 1,
};

// Pose2D
struct Pose2D {
    float x = 0.0f;
    float y = 0.0f;
    float h = 0.0f;

    // --- array / optional-string accessors ---
};

// BodyTwist
struct BodyTwist {
    float v = 0.0f;
    float omega = 0.0f;

    // --- array / optional-string accessors ---
};

// BodyTwist3
struct BodyTwist3 {
    float v_x = 0.0f;
    float v_y = 0.0f;
    float omega = 0.0f;

    // --- array / optional-string accessors ---
};

// BodyAccel
struct BodyAccel {
    float a_x = 0.0f;
    float a_y = 0.0f;

    // --- array / optional-string accessors ---
};

// ValueSet
struct ValueSet {
    uint32_t lag = 0;
    uint32_t last_upd = 0;
    bool valid = false;

    // --- array / optional-string accessors ---
};

// PoseEstimate
struct PoseEstimate {
    Pose2D pose = {};
    BodyTwist3 twist = {};
    ValueSet stamp = {};

    // --- array / optional-string accessors ---
};

// WheelTarget
struct WheelTarget {
    Opt<float> speed = {};
    Opt<float> position = {};

    // --- array / optional-string accessors ---
};

// Gains
struct Gains {
    float kp = 0.0f;
    float ki = 0.0f;
    float kff = 0.0f;
    float i_max = 0.0f;
    float kaw = 0.0f;

    // --- array / optional-string accessors ---
};

// OutCommand
struct OutCommand {
    uint32_t verb_id = 0;
    float args_[4] = {};
    uint8_t args_count = 0;
    uint32_t argc = 0;
    bool priority = false;

    // --- array / optional-string accessors ---
    const float* args() const { return args_; }
    uint8_t args_count_val() const { return args_count; }
};

// CommandBatch
struct CommandBatch {
    OutCommand cmds_[8] = {};
    uint8_t cmds_count = 0;
    uint32_t count = 0;

    // --- array / optional-string accessors ---
    const OutCommand* cmds() const { return cmds_; }
    uint8_t cmds_count_val() const { return cmds_count; }
};

// Capabilities
struct Capabilities {
    uint32_t command_modes_[8] = {};
    uint8_t command_modes_count = 0;
    uint32_t state_fields_[16] = {};
    uint8_t state_fields_count = 0;
    bool holonomic = false;
    bool onboard_position = false;
    uint32_t wheel_count = 0;

    // --- array / optional-string accessors ---
    const uint32_t* command_modes() const { return command_modes_; }
    uint8_t command_modes_count_val() const { return command_modes_count; }
    const uint32_t* state_fields() const { return state_fields_; }
    uint8_t state_fields_count_val() const { return state_fields_count; }
};

}  // namespace msg

