// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/envelope.proto
#pragma once

#include "messages/common.h"
#include "messages/config.h"
#include "messages/telemetry.h"


namespace msg {

enum class ErrCode : uint8_t {
    ERR_NONE = 0,
    ERR_UNKNOWN = 1,
    ERR_BADARG = 2,
    ERR_RANGE = 3,
    ERR_FULL = 4,
    ERR_DECODE = 5,
    ERR_UNIMPLEMENTED = 6,
    ERR_OVERSIZE = 7,
    ERR_NOT_CONFIGURED = 8,
};

// Ack
struct Ack {
    uint32_t q = 0;
    float rem = 0.0f;
    uint32_t t = 0;

    // --- array / optional-string accessors ---
};

// Error
struct Error {
    ErrCode code = static_cast<ErrCode>(0);
    uint32_t field = 0;

    // --- array / optional-string accessors ---
};

// Stop
struct Stop {

    // --- array / optional-string accessors ---
};

// MoveTwist
struct MoveTwist {
    float v_x = 0.0f;
    float v_y = 0.0f;
    float omega = 0.0f;

    // --- array / optional-string accessors ---
};

// MoveWheels
struct MoveWheels {
    float v_left = 0.0f;
    float v_right = 0.0f;

    // --- array / optional-string accessors ---
};

// Move
struct Move {
    enum class VelocityKind : uint8_t {
        NONE = 0,
        TWIST = 1,
        WHEELS = 2,
    };
    VelocityKind velocity_kind = VelocityKind::NONE;
    union {
        MoveTwist twist;
        MoveWheels wheels;
    } velocity = {};

    enum class StopKind : uint8_t {
        NONE = 0,
        TIME = 1,
        DISTANCE = 2,
        ANGLE = 3,
    };
    StopKind stop_kind = StopKind::NONE;
    union {
        float time;
        float distance;
        float angle;
    } stop = {};

    float timeout = 0.0f;
    bool replace = false;
    uint32_t id = 0;

    // --- array / optional-string accessors ---
};

// ConfigDelta
struct ConfigDelta {
    enum class PatchKind : uint8_t {
        NONE = 0,
        DRIVETRAIN = 1,
        MOTOR = 2,
        OTOS = 3,
    };
    PatchKind patch_kind = PatchKind::NONE;
    union {
        DrivetrainConfigPatch drivetrain;
        MotorConfigPatch motor;
        OtosConfigPatch otos;
    } patch = {};


    // --- array / optional-string accessors ---
};

// CommandEnvelope
struct CommandEnvelope {
    enum class CmdKind : uint8_t {
        NONE = 0,
        CONFIG = 1,
        STOP = 2,
        MOVE = 3,
    };
    CmdKind cmd_kind = CmdKind::NONE;
    union {
        ConfigDelta config;
        Stop stop;
        Move move;
    } cmd = {};

    uint32_t corr_id = 0;

    // --- array / optional-string accessors ---
};

// ReplyEnvelope
struct ReplyEnvelope {
    enum class BodyKind : uint8_t {
        NONE = 0,
        OK = 1,
        ERR = 2,
        TLM = 3,
    };
    BodyKind body_kind = BodyKind::NONE;
    union {
        Ack ok;
        Error err;
        Telemetry tlm;
    } body = {};

    uint32_t corr_id = 0;

    // --- array / optional-string accessors ---
};

}  // namespace msg

