// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/robot_config.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class ConfigGroupTarget : uint8_t {
    CONFIG_GROUP_UNSPECIFIED = 0,
    GEOMETRY = 1,
    MOTORS = 2,
    DRIVE = 3,
    WHEEL_CONTROL = 4,
    PLANNER = 5,
    OTOS = 6,
    ESTIMATOR = 7,
    PLANNER_SHAPER = 8,
};

enum class ConfigSource : uint8_t {
    CONFIG_SOURCE_UNSPECIFIED = 0,
    CONFIG_SOURCE_BAKED = 1,
    CONFIG_SOURCE_LIVE = 2,
    CONFIG_SOURCE_PERSISTED = 3,
};

// Geometry
struct Geometry {
    float trackwidth = 0.0f;
    float rotational_slip = 0.0f;
    float rotation_gain_pos = 0.0f;
    float rotation_offset = 0.0f;
    float rotation_gain_neg = 0.0f;
    float rotation_offset_neg = 0.0f;

    // --- array / optional-string accessors ---
};

// Motors
struct Motors {
    float travel_calib_left = 0.0f;
    float travel_calib_right = 0.0f;
    int32_t fwd_sign_left = 0;
    int32_t fwd_sign_right = 0;
    float output_deadband = 0.0f;
    float reversal_dwell = 0.0f;
    float vel_kp = 0.0f;
    float vel_ki = 0.0f;
    float vel_kff = 0.0f;
    float vel_i_max = 0.0f;
    float vel_kaw = 0.0f;
    float vel_filt_alpha = 0.0f;

    // --- array / optional-string accessors ---
};

// Drive
struct Drive {
    float duty_per_speed_left = 0.0f;
    float duty_per_speed_right = 0.0f;
    float crawl_pulse = 0.0f;
    float wheel_gain_left_accel = 0.0f;
    float wheel_intercept_left_accel = 0.0f;
    float wheel_gain_left_decel = 0.0f;
    float wheel_intercept_left_decel = 0.0f;
    float wheel_gain_right_accel = 0.0f;
    float wheel_intercept_right_accel = 0.0f;
    float wheel_gain_right_decel = 0.0f;
    float wheel_intercept_right_decel = 0.0f;

    // --- array / optional-string accessors ---
};

// WheelControl
struct WheelControl {
    float v_min = 0.0f;
    float bias_max = 0.0f;
    float tau_adapt = 0.0f;
    float a_steady = 0.0f;
    float deficit_threshold = 0.0f;
    float deficit_window = 0.0f;
    float pid_kp = 0.0f;
    float pid_ki = 0.0f;
    float pid_i_max = 0.0f;
    float pid_kaff = 0.0f;
    float pid_max = 0.0f;
    float pos_err_max = 0.0f;

    // --- array / optional-string accessors ---
};

// Planner
struct Planner {
    float v_max = 0.0f;
    float omega_max = 0.0f;
    float control_period = 0.0f;
    float actuation_delay = 0.0f;
    float settle_rest_velocity = 0.0f;
    float settle_rest_omega = 0.0f;
    float settle_epsilon_linear = 0.0f;
    float settle_epsilon_angular = 0.0f;
    float heading_hold_gain = 0.0f;
    float decel_plan_fraction = 0.0f;

    // --- array / optional-string accessors ---
};

// PlannerShaper
struct PlannerShaper {
    float a_max = 0.0f;
    float a_decel = 0.0f;
    float alpha_max = 0.0f;
    float alpha_decel = 0.0f;
    float jerk_max = 0.0f;
    float yaw_jerk_max = 0.0f;

    // --- array / optional-string accessors ---
};

// Otos
struct Otos {
    float offset_x = 0.0f;
    float offset_y = 0.0f;
    float offset_yaw = 0.0f;
    float linear_scale = 0.0f;
    float angular_scale = 0.0f;

    // --- array / optional-string accessors ---
};

// Estimator
struct Estimator {
    float weight_heading_otos = 0.0f;
    float weight_omega_otos = 0.0f;
    uint32_t staleness = 0;

    // --- array / optional-string accessors ---
};

// SetConfigGroup
struct SetConfigGroup {
    ConfigGroupTarget target = static_cast<ConfigGroupTarget>(0);
    uint8_t body_[140] = {};
    uint8_t body_count = 0;

    // --- array / optional-string accessors ---
    const uint8_t* body() const { return body_; }
    uint8_t body_count_val() const { return body_count; }
};

// GetConfig
struct GetConfig {
    ConfigGroupTarget target = static_cast<ConfigGroupTarget>(0);

    // --- array / optional-string accessors ---
};

// ConfigSnapshot
struct ConfigSnapshot {
    ConfigGroupTarget target = static_cast<ConfigGroupTarget>(0);
    uint8_t body_[140] = {};
    uint8_t body_count = 0;
    ConfigSource source = static_cast<ConfigSource>(0);

    // --- array / optional-string accessors ---
    const uint8_t* body() const { return body_; }
    uint8_t body_count_val() const { return body_count; }
};

// SetConfigField
struct SetConfigField {
    ConfigGroupTarget target = static_cast<ConfigGroupTarget>(0);
    uint32_t field = 0;
    float value = 0.0f;

    // --- array / optional-string accessors ---
};

}  // namespace msg

