// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/telemetry.proto
#pragma once

#include "messages/common.h"


namespace msg {

enum class DriveMode : uint8_t {
    IDLE = 0,
    STREAMING = 1,
    TIMED = 2,
    DISTANCE = 3,
    GO_TO = 4,
    VELOCITY = 5,
};

// EncoderReading
struct EncoderReading {
    int32_t position = 0;
    int32_t velocity = 0;
    uint32_t age = 0;
    uint32_t position_epoch = 0;

    static constexpr float kPositionScale = 1.0f;  // real = raw * scale
    static int32_t packPosition(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kPositionScale + 0.5f) : (value / kPositionScale - 0.5f));
    }
    static float unpackPosition(int32_t raw) { return static_cast<float>(raw) * kPositionScale; }

    static constexpr float kVelocityScale = 0.1f;  // real = raw * scale
    static int32_t packVelocity(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kVelocityScale + 0.5f) : (value / kVelocityScale - 0.5f));
    }
    static float unpackVelocity(int32_t raw) { return static_cast<float>(raw) * kVelocityScale; }

    // --- array / optional-string accessors ---
};

// OtosReading
struct OtosReading {
    int32_t x = 0;
    int32_t y = 0;
    int32_t heading = 0;
    int32_t v_x = 0;
    int32_t v_y = 0;
    int32_t omega = 0;
    uint32_t age = 0;

    static constexpr float kXScale = 1.0f;  // real = raw * scale
    static int32_t packX(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kXScale + 0.5f) : (value / kXScale - 0.5f));
    }
    static float unpackX(int32_t raw) { return static_cast<float>(raw) * kXScale; }

    static constexpr float kYScale = 1.0f;  // real = raw * scale
    static int32_t packY(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kYScale + 0.5f) : (value / kYScale - 0.5f));
    }
    static float unpackY(int32_t raw) { return static_cast<float>(raw) * kYScale; }

    static constexpr float kHeadingScale = 0.001f;  // real = raw * scale
    static int32_t packHeading(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kHeadingScale + 0.5f) : (value / kHeadingScale - 0.5f));
    }
    static float unpackHeading(int32_t raw) { return static_cast<float>(raw) * kHeadingScale; }

    static constexpr float kVXScale = 0.1f;  // real = raw * scale
    static int32_t packVX(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kVXScale + 0.5f) : (value / kVXScale - 0.5f));
    }
    static float unpackVX(int32_t raw) { return static_cast<float>(raw) * kVXScale; }

    static constexpr float kVYScale = 0.1f;  // real = raw * scale
    static int32_t packVY(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kVYScale + 0.5f) : (value / kVYScale - 0.5f));
    }
    static float unpackVY(int32_t raw) { return static_cast<float>(raw) * kVYScale; }

    static constexpr float kOmegaScale = 0.01f;  // real = raw * scale
    static int32_t packOmega(float value) {
        return static_cast<int32_t>(value >= 0.0f ? (value / kOmegaScale + 0.5f) : (value / kOmegaScale - 0.5f));
    }
    static float unpackOmega(int32_t raw) { return static_cast<float>(raw) * kOmegaScale; }

    // --- array / optional-string accessors ---
};

// Telemetry
struct Telemetry {
    uint32_t now = 0;
    uint32_t seq = 0;
    DriveMode mode = static_cast<DriveMode>(0);
    uint32_t flags = 0;
    EncoderReading enc_left = {};
    EncoderReading enc_right = {};
    OtosReading otos = {};
    Pose2D pose = {};
    BodyTwist3 twist = {};
    uint32_t line = 0;
    uint32_t color = 0;
    uint32_t acks_[12] = {};
    uint8_t acks_count = 0;
    uint32_t cycle_busy = 0;
    uint32_t cycle_period = 0;

    // --- array / optional-string accessors ---
    const uint32_t* acks() const { return acks_; }
    uint8_t acks_count_val() const { return acks_count; }
};

}  // namespace msg

