"""Compiled protobuf Python bindings for protos/*.proto (095-002, M7 Host
Codec Mirror).

GENERATED by scripts/gen_pb2.py via ``grpc_tools.protoc --python_out`` —
NEVER hand-edited (mirrors source/messages/*.h's "generated, not
hand-authored" contract on the firmware side). Re-run
``python3 scripts/gen_pb2.py`` (or ``just build``/``just build-sim``/
``python3 build.py``, which already call it) after editing any
protos/*.proto file.

Flat-import shim: protoc's Python codegen, run flat (-I protos, no nested
output tree matching this package's own dotted path), emits each
``*_pb2.py``'s cross-file references as a bare top-level import (e.g.
``envelope_pb2.py`` contains ``import drivetrain_pb2 as drivetrain__pb2``)
rather than a relative or ``robot_radio.robot.pb2``-qualified import. Such a
bare import only resolves via sys.path — Python 3 has no implicit
relative-package import — so it does NOT resolve merely because a caller
does ``from robot_radio.robot.pb2 import envelope_pb2``. Inserting this
package's own directory onto sys.path here, once, at package-import time,
is the standard/conventional fix for this well-known grpc_tools.protoc
flat-output limitation: it runs before any ``*_pb2`` submodule is imported,
since Python always imports and executes a package's __init__.py before any
of its submodules.
"""
import os
import sys

_here = os.path.dirname(os.path.abspath(__file__))
if _here not in sys.path:
    sys.path.insert(0, _here)
