# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x05robot\"\xa1\x02\n\x15\x44rivetrainConfigPatch\x12\x17\n\ntrackwidth\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x1c\n\x0frotational_slip\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x15\n\x08\x65kf_q_xy\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x18\n\x0b\x65kf_q_theta\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x1a\n\rekf_r_otos_xy\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1d\n\x10\x65kf_r_otos_theta\x18\x06 \x01(\x02H\x05\x88\x01\x01\x42\r\n\x0b_trackwidthB\x12\n\x10_rotational_slipB\x0b\n\t_ekf_q_xyB\x0e\n\x0c_ekf_q_thetaB\x10\n\x0e_ekf_r_otos_xyB\x13\n\x11_ekf_r_otos_theta\"\xe5\x01\n\x10MotorConfigPatch\x12#\n\x04side\x18\x01 \x01(\x0e\x32\x15.robot.BoundMotorSide\x12\x19\n\x0ctravel_calib\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x0f\n\x02kp\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x0f\n\x02ki\x18\x04 \x01(\x02H\x02\x88\x01\x01\x12\x10\n\x03kff\x18\x05 \x01(\x02H\x03\x88\x01\x01\x12\x12\n\x05i_max\x18\x06 \x01(\x02H\x04\x88\x01\x01\x12\x10\n\x03kaw\x18\x07 \x01(\x02H\x05\x88\x01\x01\x42\x0f\n\r_travel_calibB\x05\n\x03_kpB\x05\n\x03_kiB\x06\n\x04_kffB\x08\n\x06_i_maxB\x06\n\x04_kaw\":\n\x12PlannerConfigPatch\x12\x16\n\tmin_speed\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x0c\n\n_min_speed*}\n\x0c\x43onfigTarget\x12\x15\n\x11\x43ONFIG_DRIVETRAIN\x10\x00\x12\x15\n\x11\x43ONFIG_MOTOR_LEFT\x10\x01\x12\x16\n\x12\x43ONFIG_MOTOR_RIGHT\x10\x02\x12\x12\n\x0e\x43ONFIG_PLANNER\x10\x03\x12\x13\n\x0f\x43ONFIG_WATCHDOG\x10\x04*%\n\x0e\x42oundMotorSide\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGTARGET']._serialized_start=607
  _globals['_CONFIGTARGET']._serialized_end=732
  _globals['_BOUNDMOTORSIDE']._serialized_start=734
  _globals['_BOUNDMOTORSIDE']._serialized_end=771
  _globals['_DRIVETRAINCONFIGPATCH']._serialized_start=24
  _globals['_DRIVETRAINCONFIGPATCH']._serialized_end=313
  _globals['_MOTORCONFIGPATCH']._serialized_start=316
  _globals['_MOTORCONFIGPATCH']._serialized_end=545
  _globals['_PLANNERCONFIGPATCH']._serialized_start=547
  _globals['_PLANNERCONFIGPATCH']._serialized_end=605
# @@protoc_insertion_point(module_scope)
