# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: options.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12\x05robot\x1a google/protobuf/descriptor.proto:1\n\x05units\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\t\x88\x01\x01:5\n\tmax_count\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\r\x88\x01\x01:/\n\x03min\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x01\x88\x01\x01:/\n\x03max\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\x01\x88\x01\x01:3\n\x07\x61\x62s_max\x12\x1d.google.protobuf.FieldOptions\x18\xd4\x86\x03 \x01(\x01\x88\x01\x01:/\n\x03req\x12\x1d.google.protobuf.FieldOptions\x18\xd5\x86\x03 \x01(\x08\x88\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
