# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensors.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import options_pb2 as options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsensors.proto\x12\x05robot\x1a\x0c\x63ommon.proto\x1a\roptions.proto\"q\n\x0fLineSensorState\x12\x11\n\x03raw\x18\x01 \x03(\rB\x04\x88\xb5\x18\x04\x12\x18\n\nnormalized\x18\x02 \x03(\rB\x04\x88\xb5\x18\x04\x12\x1e\n\x05stamp\x18\x03 \x01(\x0b\x32\x0f.robot.ValueSet\x12\x11\n\tconnected\x18\x04 \x01(\x08\"f\n\x10LineSensorConfig\x12\x10\n\x08lag_line\x18\x01 \x01(\r\x12\x15\n\x07\x63\x61l_min\x18\x02 \x03(\rB\x04\x88\xb5\x18\x04\x12\x15\n\x07\x63\x61l_max\x18\x03 \x03(\rB\x04\x88\xb5\x18\x04\x12\x12\n\nfilt_alpha\x18\x04 \x01(\x02\"q\n\x10\x43olorSensorState\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\x12\t\n\x01\x63\x18\x04 \x01(\r\x12\x1e\n\x05stamp\x18\x05 \x01(\x0b\x32\x0f.robot.ValueSet\x12\x11\n\tconnected\x18\x06 \x01(\x08\"I\n\x11\x43olorSensorConfig\x12\x11\n\tlag_color\x18\x01 \x01(\r\x12\x13\n\x0bintegration\x18\x02 \x01(\r\x12\x0c\n\x04gain\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINESENSORSTATE'].fields_by_name['raw']._loaded_options = None
  _globals['_LINESENSORSTATE'].fields_by_name['raw']._serialized_options = b'\210\265\030\004'
  _globals['_LINESENSORSTATE'].fields_by_name['normalized']._loaded_options = None
  _globals['_LINESENSORSTATE'].fields_by_name['normalized']._serialized_options = b'\210\265\030\004'
  _globals['_LINESENSORCONFIG'].fields_by_name['cal_min']._loaded_options = None
  _globals['_LINESENSORCONFIG'].fields_by_name['cal_min']._serialized_options = b'\210\265\030\004'
  _globals['_LINESENSORCONFIG'].fields_by_name['cal_max']._loaded_options = None
  _globals['_LINESENSORCONFIG'].fields_by_name['cal_max']._serialized_options = b'\210\265\030\004'
  _globals['_LINESENSORSTATE']._serialized_start=53
  _globals['_LINESENSORSTATE']._serialized_end=166
  _globals['_LINESENSORCONFIG']._serialized_start=168
  _globals['_LINESENSORCONFIG']._serialized_end=270
  _globals['_COLORSENSORSTATE']._serialized_start=272
  _globals['_COLORSENSORSTATE']._serialized_end=385
  _globals['_COLORSENSORCONFIG']._serialized_start=387
  _globals['_COLORSENSORCONFIG']._serialized_end=460
# @@protoc_insertion_point(module_scope)
