# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2
import common_pb2 as common__pb2
import planner_pb2 as planner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x05robot\x1a\roptions.proto\x1a\x0c\x63ommon.proto\x1a\rplanner.proto\"O\n\x08\x41\x63kEntry\x12\x0f\n\x07\x63orr_id\x18\x01 \x01(\r\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.robot.AckStatus\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\r\"\xe0\x03\n\tTelemetry\x12#\n\x04\x61\x63ks\x18\x01 \x03(\x0b\x32\x0f.robot.AckEntryB\x04\x88\xb5\x18\x03\x12\x0b\n\x03now\x18\x02 \x01(\r\x12\x1e\n\x04mode\x18\x03 \x01(\x0e\x32\x10.robot.DriveMode\x12\x0b\n\x03seq\x18\x04 \x01(\r\x12\x0f\n\x07has_enc\x18\x05 \x01(\x08\x12\x10\n\x08\x65nc_left\x18\x06 \x01(\x02\x12\x11\n\tenc_right\x18\x07 \x01(\x02\x12\x0f\n\x07has_vel\x18\x08 \x01(\x08\x12\x10\n\x08vel_left\x18\t \x01(\x02\x12\x11\n\tvel_right\x18\n \x01(\x02\x12\x10\n\x08has_pose\x18\x0b \x01(\x08\x12\x1b\n\x04pose\x18\x0c \x01(\x0b\x32\r.robot.Pose2D\x12\x10\n\x08has_otos\x18\r \x01(\x08\x12\x1b\n\x04otos\x18\x0e \x01(\x0b\x32\r.robot.Pose2D\x12\x16\n\x0eotos_connected\x18\x0f \x01(\x08\x12\x11\n\thas_twist\x18\x10 \x01(\x08\x12 \n\x05twist\x18\x11 \x01(\x0b\x32\x11.robot.BodyTwist3\x12\x0e\n\x06\x61\x63tive\x18\x12 \x01(\x08\x12\x11\n\tconn_left\x18\x13 \x01(\x08\x12\x12\n\nconn_right\x18\x14 \x01(\x08\x12\x12\n\nfault_bits\x18\x15 \x01(\r\x12\x12\n\nevent_bits\x18\x16 \x01(\r\"\xd6\x01\n\x12TelemetrySecondary\x12\x0b\n\x03now\x18\x01 \x01(\r\x12\x13\n\x0bhas_cmd_vel\x18\x02 \x01(\x08\x12\x14\n\x0c\x63md_vel_left\x18\x03 \x01(\x02\x12\x15\n\rcmd_vel_right\x18\x04 \x01(\x02\x12\x10\n\x08\x61\x63\x63_left\x18\x05 \x01(\x02\x12\x11\n\tacc_right\x18\x06 \x01(\x02\x12\x13\n\x0bglitch_left\x18\x07 \x01(\r\x12\x14\n\x0cglitch_right\x18\x08 \x01(\r\x12\x0f\n\x07ts_left\x18\t \x01(\r\x12\x10\n\x08ts_right\x18\n \x01(\r*2\n\tAckStatus\x12\x11\n\rACK_STATUS_OK\x10\x00\x12\x12\n\x0e\x41\x43K_STATUS_ERR\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRY'].fields_by_name['acks']._loaded_options = None
  _globals['_TELEMETRY'].fields_by_name['acks']._serialized_options = b'\210\265\030\003'
  _globals['_ACKSTATUS']._serialized_start=851
  _globals['_ACKSTATUS']._serialized_end=901
  _globals['_ACKENTRY']._serialized_start=70
  _globals['_ACKENTRY']._serialized_end=149
  _globals['_TELEMETRY']._serialized_start=152
  _globals['_TELEMETRY']._serialized_end=632
  _globals['_TELEMETRYSECONDARY']._serialized_start=635
  _globals['_TELEMETRYSECONDARY']._serialized_end=849
# @@protoc_insertion_point(module_scope)
