// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/gripper.proto
#pragma once

#include "messages/common.h"


namespace msg {

// GripperCommand
struct GripperCommand {
    Opt<float> angle = {};

    // --- getters ---
    const Opt<float>& get_angle() const { return angle; }

    // --- chainable setters (Command/Config only) ---
    GripperCommand& setAngle(float v) {
        angle.has = true; angle.val = v;
        return *this;
    }
};

// GripperState
struct GripperState {
    Opt<float> angle = {};
    bool connected = false;

    // --- getters ---
    const Opt<float>& get_angle() const { return angle; }
    bool get_connected() const { return connected; }
};

// GripperConfig
struct GripperConfig {
    bool has_gripper = false;
    float gripper_offset = 0.0f;
    float min = 0.0f;
    float max = 0.0f;

    // --- getters ---
    bool get_has_gripper() const { return has_gripper; }
    float get_gripper_offset() const { return gripper_offset; }
    float get_min() const { return min; }
    float get_max() const { return max; }

    // --- chainable setters (Command/Config only) ---
    GripperConfig& setHasGripper(bool v) { has_gripper = v; return *this; }
    GripperConfig& setGripperOffset(float v) { gripper_offset = v; return *this; }
    GripperConfig& setMin(float v) { min = v; return *this; }
    GripperConfig& setMax(float v) { max = v; return *this; }
};

}  // namespace msg

