// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_boot_config.py before each firmware build.
// Source: data/robots/tovez.json
//
// The whole file is the robot's boot configuration: the per-port
// msg::MotorConfig defaults and the msg::DrivetrainConfig default, with
// per-robot calibration baked in from the robot JSON above. main.cpp calls
// these; it never hardcodes calibration. See src/firm/config/boot_config.h.

#include "config/boot_config.h"

namespace Config {

// kRobotProfileName — see boot_config.h's own doc comment (sprint 124
// architecture Decision 4, `ID:`'s calibration-profile field). Baked from
// this generator's own source robot JSON path, above.
const char kRobotProfileName[] = "tovez";

// kDrivetrainType — see boot_config.h's own doc comment (sprint 124
// architecture Decision 4, `ID:`'s drivetrain-type field). Baked from
// identity.drivetrain_type (robot JSON), defaulting to "differential"
// per the schema's own documented default.
const char kDrivetrainType[] = "differential";

void defaultMotorConfigs(msg::MotorConfig* out) {
    // Velocity PID gains — baked from the robot JSON's control.vel_* keys
    // (093: now in the NezhaMotor duty [-1,1] plant scale, see the JSON's
    // control._vel_gains_domain marker), falling back to bench-tuned firmware
    // defaults when absent. Live-correctable per motor via `DEV M <n> CFG`.
    msg::Gains velGains;
    velGains.kp = 0.0016f;
    velGains.ki = 0.005f;
    velGains.kff = 0.0008f;
    velGains.i_max = 0.3f;
    velGains.kaw = 20.0f;   // anti-windup back-calculation (velocity_pid.cpp; 0 = off)

    for (uint32_t i = 0; i < kMotorConfigCount; ++i) {
        out[i] = msg::MotorConfig();
        out[i].setPort(i + 1);
        out[i].setVelGains(velGains);
        // EMA coeff — from control.vel_filt (fallback default); a=0 would pin
        // reported velocity at 0 forever regardless of real motion.
        out[i].setVelFiltAlpha(0.3f);
        // Write-shaping floor/hold — baked from the robot JSON's
        // control.output_deadband/control.reversal_dwell_ms (sprint 114
        // ticket 003, config-as-truth completion). REQUIRED as of this
        // ticket: Devices::NezhaMotor no longer substitutes a ship default
        // when these arrive unset, so every build must emit a real value.
        out[i].setOutputDeadband(0.03f);   // [-1,1] fraction
        out[i].setReversalDwell(100.0f);   // [ms]
    }

    // Per-port forward-sign — baked from the robot JSON's calibration.
    // fwd_sign_{left,right} for the drive-pair ports
    // (ports 1/2); other ports use the bench placeholder
    // (1). The drive pair is mirror-mounted, so left/right are
    // expected to differ in sign (088-002 —
    // clasi/issues/tovez-drive-motor-reversed-fwd-sign.md).
    out[0].setFwdSign(1);   // port 1
    out[1].setFwdSign(-1);   // port 2
    out[2].setFwdSign(1);   // port 3
    out[3].setFwdSign(1);   // port 4

    // Per-port encoder travel calibration — baked from the robot JSON's
    // calibration.mm_per_wheel_deg_{left,right} for the drive-pair ports
    // (ports 1/2); other ports use the bench placeholder.
    out[0].setTravelCalib(0.7165f);   // [mm/deg] port 1
    out[1].setTravelCalib(0.7077f);   // [mm/deg] port 2
    out[2].setTravelCalib(0.487f);   // [mm/deg] port 3
    out[3].setTravelCalib(0.487f);   // [mm/deg] port 4

    // Per-port I2C flip-flop poll-schedule membership (091-002) — true for
    // the drive-pair ports (1/2), false otherwise. Not
    // robot-JSON-configurable (a firmware-scheduling fact, not per-robot
    // calibration); live-adjustable via `DEV M <n> CFG polled=true` for a
    // bench rig's own non-drive-pair port (docs/protocol-v2.md §16).
    out[0].setPolled(true);   // port 1
    out[1].setPolled(true);   // port 2
    out[2].setPolled(false);   // port 3
    out[3].setPolled(false);   // port 4
}

msg::DrivetrainConfig defaultDrivetrainConfig() {
    msg::DrivetrainConfig cfg;
    cfg.setTrackwidth(128.0f);   // [mm] baked from robot geometry
    cfg.setRotationalSlip(0.9117f);   // scrub: actual/ideal rotation, 0 = uncalibrated
    // Turn calibration: actual = gain*commanded + offset[deg], per direction.
    cfg.setRotationGainPos(1.061f);
    cfg.setRotationOffset(-5.54f);
    cfg.setRotationGainNeg(1.071f);
    cfg.setRotationOffsetNeg(-7.04f);
    // The drive-pair port binding lives in DrivetrainConfig (the robot's
    // normal drive pair); the coupled bench rig re-binds via `DEV DT PORTS`.
    cfg.setLeftPort(1);
    cfg.setRightPort(2);
    return cfg;
}

OtosBootConfig defaultOtosBootConfig() {
    // 086-005 — additive to defaultMotorConfigs()/defaultDrivetrainConfig()
    // above; no existing mapping touched. Baked from the robot JSON's
    // geometry.odometry_offset_mm (x/y/yaw_rad) and calibration.
    // otos_linear_scale/otos_angular_scale where present; identity defaults
    // (zero offset, 1.0 scale) otherwise. Boot-time-baked only -- see
    // OtosBootConfig's own doc comment (src/firm/config/boot_config.h) for why
    // this is never a live SET/wire surface.
    OtosBootConfig cfg;
    cfg.offsetX = -47.7f;        // [mm]
    cfg.offsetY = 3.5f;        // [mm]
    cfg.offsetYaw = 0.0f;    // [rad]
    cfg.linearScale = 1.0275f;
    cfg.angularScale = 0.987f;
    return cfg;
}

EstimatorBootConfig defaultEstimatorConfig() {
    // 117 (predict-to-now estimator v1) — fail-closed baked from the robot
    // JSON's estimator.weight_heading_otos/weight_omega_otos/staleness_ms
    // (data/robots/robot_config.schema.json). Encoder-only v1 (stakeholder
    // decision): both blend weights are committed 0.0 in every robot JSON
    // this sprint -- see that JSON's own inline comment for the
    // staleness_ms reasoning. NOT a live SET/wire surface itself -- see
    // EstimatorBootConfig's own doc comment (src/firm/config/boot_config.h)
    // for the separate, volatile ESTIMATOR group live-tuning path
    // (robot_config.proto's `Estimator`, decodes correctly but reaches no
    // consumer -- Configurator::install(ESTIMATOR) permanently returns
    // ERR_UNIMPLEMENTED, 132-010/132-013).
    EstimatorBootConfig cfg;
    cfg.headingOtos = 0.0f;
    cfg.omegaOtos = 0.0f;
    cfg.staleness = 60u;   // [ms]
    return cfg;
}

ShaperBootConfig defaultShaperConfig() {
    // Decel-into-the-goal campaign -- fail-closed baked from the robot
    // JSON's control.a_max/a_decel/alpha_max/alpha_decel/j_max/
    // yaw_jerk_max (data/robots/robot_config.schema.json). a_max/a_decel/
    // j_max/yaw_jerk_max are the deleted msg::PlannerConfig's own former
    // fields, orphaned by 115-003 and read again here into a velocity-
    // shaping consumer that has SINCE ALSO been deleted, as dead code, in
    // sprint 128 ticket 014 (zero callers, superseded by Motion::Planner's
    // own hand-baked PlannerLimits) -- this whole struct is currently
    // unread by anything; alpha_max/alpha_decel are new (a_max/a_decel's
    // own angular sibling -- yaw_jerk_max already covered the angular
    // jerk slot). NOT a live SET/wire surface itself -- see the ESTIMATOR
    // group's own a_max/a_decel/alpha_max/alpha_decel/j_max/yaw_jerk_max
    // fields (robot_config.proto's `Estimator`) for the separate, volatile
    // live-tuning path (mirrors OtosBootConfig/EstimatorBootConfig's own
    // "boot bake vs. live wire push" split -- same permanently-unconsumed
    // status as the comment above).
    ShaperBootConfig cfg;
    cfg.aMax = 800.0f;                  // [mm/s^2]
    cfg.aDecel = 800.0f;               // [mm/s^2]
    cfg.alphaMax = 7.0f;           // [rad/s^2]
    cfg.alphaDecel = 7.0f;       // [rad/s^2]
    cfg.jMax = 5000.0f;                   // [mm/s^3]
    cfg.yawJerkMax = 100.0f;      // [rad/s^3]
    return cfg;
}

DriveBootConfig defaultDriveConfig() {
    // command-ingestion-ring-buffered-comms-subsystem-routing-two-stops.md
    // §6 -- fail-closed baked from the robot JSON's
    // control.duty_per_speed_left/duty_per_speed_right/crawl_pulse
    // (data/robots/robot_config.schema.json). These were hard-coded in C++
    // before that change (the duty pair as App::Drive member initializers,
    // the crawl amplitude as a bare main.cpp setCrawlPulse() call); see
    // gen_boot_config.py's drive_config_for_config() for why that was
    // wrong. NOT a live SET/wire surface itself -- the `kff` CONFIG key
    // still retargets the duty scale at runtime, but it sets BOTH wheels
    // to one value, which is exactly why the per-wheel split has to be
    // baked here rather than left to it.
    DriveBootConfig cfg;
    cfg.dutyPerSpeedLeft = 0.001182f;    // [duty/(mm/s)]
    cfg.dutyPerSpeedRight = 0.001182f;  // [duty/(mm/s)]
    cfg.crawlPulse = 0.0f;                  // [-1,1]; 0 = off
    cfg.gainLeftAccel = 1.0f;
    cfg.interceptLeftAccel = 0.0f;   // [mm/s]
    cfg.gainLeftDecel = 1.0f;
    cfg.interceptLeftDecel = 0.0f;   // [mm/s]
    cfg.gainRightAccel = 1.0f;
    cfg.interceptRightAccel = 0.0f;   // [mm/s]
    cfg.gainRightDecel = 1.0f;
    cfg.interceptRightDecel = 0.0f;   // [mm/s]
    return cfg;
}

WheelControllerBootConfig defaultWheelControllerConfig() {
    // 130-004 (wheel-speed-controller-moves-into-drive.md Phase 2) --
    // fail-closed baked from the robot JSON's control.wheel_*/
    // control.wheel_pid_*/control.wheel_deficit_* keys
    // (data/robots/robot_config.schema.json). See
    // WheelControllerBootConfig's own doc comment (config/boot_config.h)
    // for the full field-for-field mapping and why 0 is a safe,
    // meaningful "this stage is disabled" value here.
    WheelControllerBootConfig cfg;
    cfg.vMin = 99.7f;                        // [mm/s]
    cfg.biasMax = 23.8f;                  // [mm/s]
    cfg.tauAdapt = 30.0f;                // [s]
    cfg.aSteady = 30.0f;                  // [mm/s^2]
    cfg.deficitThreshold = 0.0f;  // [mm/s]
    cfg.deficitWindow = 0.0f;      // [ms]
    cfg.kp = 0.0f;        // [1]
    cfg.ki = 0.0f;        // [1/s]
    cfg.iMax = 0.0f;    // [mm/s]
    cfg.kaff = 0.0f;    // [s]
    cfg.pidMax = 0.0f;  // [mm/s]
    return cfg;
}

PlannerBootConfig defaultPlannerLimits() {
    // 129-009 (config consolidation), field set reduced 130-009 -- fail-
    // closed baked from the robot JSON's `planner` block
    // (data/robots/robot_config.schema.json). See PlannerBootConfig's own
    // doc comment (src/firm/config/boot_config.h) for the current field
    // list and what was cut.
    PlannerBootConfig cfg;
    cfg.vMax = 400.0f;              // [mm/s]
    cfg.aMax = 300.0f;              // [mm/s^2]
    cfg.aDecel = 250.0f;          // [mm/s^2]
    cfg.omegaMax = 3.0f;      // [rad/s]
    cfg.alphaMax = 6.0f;      // [rad/s^2]
    cfg.alphaDecel = 5.0f;  // [rad/s^2]
    cfg.jerkMax = 1500.0f;        // [mm/s^3]
    cfg.yawJerkMax = 30.0f;  // [rad/s^3]

    cfg.controlPeriod = 50.0f;    // [ms]
    cfg.actuationDelay = 50.0f;  // [ms]

    cfg.settleRestVelocity = 10.0f;    // [mm/s]
    cfg.settleRestOmega = 0.16f;          // [rad/s]
    cfg.settleEpsilonLinear = 4.0f;  // [mm]
    cfg.settleEpsilonAngular = 0.035f;  // [rad]
    cfg.headingHoldGain = 0.0f;  // [1/s]

    cfg.decelPlanFraction = 0.4f;  // [1]
    return cfg;
}

// ---------------------------------------------------------------------------
// Config::Robot group defaults (132-005, sprint 132 "configuration
// discipline: one owned object..." -- retarget baking).
//
// Seven new no-argument functions, one per msg::ConfigGroupTarget
// (src/firm/messages/robot_config.h, generated by ticket 002 from
// src/protos/robot_config.proto): the SAME robot-JSON `_require()`/`_get()`
// call sites as the functions above, retargeted onto the NEW generated
// msg::Geometry/Motors/Drive/WheelControl/Planner/Otos/Estimator group
// structs instead of the old hand-declared boot_config.h ones.
//
// ADDITIVE for this ticket, not a replacement -- see gen_boot_config.py's
// own module docstring for why the functions above stay untouched (ticket
// 006, "Configurator owns Config::Robot", is what retargets RobotGraph's
// composition root onto Configurator::loadBaked(), which is the first
// thing to actually call these).
// ---------------------------------------------------------------------------

msg::Geometry defaultGeometryGroup() {
    // geometry.trackwidth, calibration.rotational_slip/rotation_gain*/
    // rotation_offset*_deg -- see trackwidth_for_config()/
    // rotational_slip_for_config()/rotation_calibration_for_config() above.
    msg::Geometry cfg;
    cfg.trackwidth = 128.0f;                  // [mm]
    cfg.rotational_slip = 0.9117f;                // scrub: actual/ideal rotation, 0 = uncalibrated
    cfg.rotation_gain_pos = 1.061f;
    cfg.rotation_offset = -5.54f;              // [deg]
    cfg.rotation_gain_neg = 1.071f;
    cfg.rotation_offset_neg = -7.04f;          // [deg]
    return cfg;
}

msg::Motors defaultMotorsGroup() {
    // Drive-pair-only slice of travel_calib_for_ports()/fwd_sign_for_ports()
    // (ports 1/2 only -- Config::Robot's schema has no
    // per-port array, see this file's own comment above) plus
    // control.vel_*/output_deadband/reversal_dwell_ms, shared by both bound
    // motors (vel_gains_for_config()/output_deadband_for_config()/
    // reversal_dwell_for_config() above).
    msg::Motors cfg;
    cfg.travel_calib_left = 0.7165f;    // [mm/deg]
    cfg.travel_calib_right = 0.7077f;  // [mm/deg]
    cfg.fwd_sign_left = 1;
    cfg.fwd_sign_right = -1;
    cfg.output_deadband = 0.03f;         // [-1,1] fraction
    cfg.reversal_dwell = 100.0f;            // [ms]
    cfg.vel_kp = 0.0016f;
    cfg.vel_ki = 0.005f;
    cfg.vel_kff = 0.0008f;
    cfg.vel_i_max = 0.3f;
    cfg.vel_kaw = 20.0f;                          // anti-windup back-calculation; 0 = off
    cfg.vel_filt_alpha = 0.3f;
    return cfg;
}

msg::Drive defaultDriveGroup() {
    // control.duty_per_speed_left/right/crawl_pulse (drive_config_for_config()
    // above) plus the Stage-A per-wheel commanded->actual correction
    // (wheel_correction_for_config() above) -- this sprint's headline
    // per-wheel drive calibration surface (SUC-006).
    msg::Drive cfg;
    cfg.duty_per_speed_left = 0.001182f;    // [duty/(mm/s)]
    cfg.duty_per_speed_right = 0.001182f;  // [duty/(mm/s)]
    cfg.crawl_pulse = 0.0f;                    // [-1,1]; 0 = off
    cfg.wheel_gain_left_accel = 1.0f;
    cfg.wheel_intercept_left_accel = 0.0f;      // [mm/s]
    cfg.wheel_gain_left_decel = 1.0f;
    cfg.wheel_intercept_left_decel = 0.0f;      // [mm/s]
    cfg.wheel_gain_right_accel = 1.0f;
    cfg.wheel_intercept_right_accel = 0.0f;     // [mm/s]
    cfg.wheel_gain_right_decel = 1.0f;
    cfg.wheel_intercept_right_decel = 0.0f;     // [mm/s]
    return cfg;
}

msg::WheelControl defaultWheelControlGroup() {
    // control.wheel_*/wheel_pid_*/wheel_deficit_* --
    // wheel_controller_config_for_config() above.
    msg::WheelControl cfg;
    cfg.v_min = 99.7f;                       // [mm/s]
    cfg.bias_max = 23.8f;                 // [mm/s]
    cfg.tau_adapt = 30.0f;                // [s]
    cfg.a_steady = 30.0f;                  // [mm/s^2]
    cfg.deficit_threshold = 0.0f;  // [mm/s]
    cfg.deficit_window = 0.0f;      // [ms]
    cfg.pid_kp = 0.0f;        // [1]
    cfg.pid_ki = 0.0f;        // [1/s]
    cfg.pid_i_max = 0.0f;    // [mm/s]
    cfg.pid_kaff = 0.0f;    // [s]
    cfg.pid_max = 0.0f;    // [mm/s]
    return cfg;
}

msg::Planner defaultPlannerGroup() {
    // planner.* (planner_config_for_config() above) plus the DEAD
    // shaper_* fields (control.a_max/a_decel/alpha_max/alpha_decel/j_max/
    // yaw_jerk_max, shaper_config_for_config() above) -- see
    // robot_config.proto's own header checklist for why the dead fields
    // are declared here at all (ticket-015 deletion, not this ticket's).
    msg::Planner cfg;
    cfg.v_max = 400.0f;                          // [mm/s]
    cfg.a_max = 300.0f;                          // [mm/s^2]
    cfg.a_decel = 250.0f;                      // [mm/s^2]
    cfg.omega_max = 3.0f;                  // [rad/s]
    cfg.alpha_max = 6.0f;                  // [rad/s^2]
    cfg.alpha_decel = 5.0f;              // [rad/s^2]
    cfg.jerk_max = 1500.0f;                    // [mm/s^3]
    cfg.yaw_jerk_max = 30.0f;              // [rad/s^3]
    cfg.control_period = 50.0f;        // [ms]
    cfg.actuation_delay = 50.0f;      // [ms]
    cfg.settle_rest_velocity = 10.0f;    // [mm/s]
    cfg.settle_rest_omega = 0.16f;          // [rad/s]
    cfg.settle_epsilon_linear = 4.0f;  // [mm]
    cfg.settle_epsilon_angular = 0.035f;  // [rad]
    cfg.heading_hold_gain = 0.0f;   // [1/s]
    cfg.decel_plan_fraction = 0.4f;  // [1]
    cfg.shaper_a_max = 800.0f;                       // [mm/s^2]
    cfg.shaper_a_decel = 800.0f;                   // [mm/s^2]
    cfg.shaper_alpha_max = 7.0f;               // [rad/s^2]
    cfg.shaper_alpha_decel = 7.0f;           // [rad/s^2]
    cfg.shaper_j_max = 5000.0f;                       // [mm/s^3]
    cfg.shaper_yaw_jerk_max = 100.0f;         // [rad/s^3]
    return cfg;
}

msg::Otos defaultOtosGroup() {
    // geometry.odometry_offset_mm.{x,y,yaw_rad}, calibration.
    // otos_linear_scale/otos_angular_scale -- otos_boot_config_values()
    // above. These are the config MULTIPLIER domain (1.0 = no correction),
    // same as the robot JSON -- App::configureOtos() (app/boot_calibration.
    // cpp) converts through Devices::scaleToRegister() before reaching the
    // chip, the SAME conversion RealOtos::begin() applies to this baked
    // value at boot (132-010 closed the live/boot domain mismatch, trap 3,
    // sprint.md).
    msg::Otos cfg;
    cfg.offset_x = -47.7f;          // [mm]
    cfg.offset_y = 3.5f;          // [mm]
    cfg.offset_yaw = 0.0f;      // [rad]
    cfg.linear_scale = 1.0275f;
    cfg.angular_scale = 0.987f;
    return cfg;
}

msg::Estimator defaultEstimatorGroup() {
    // estimator.weight_heading_otos/weight_omega_otos/staleness_ms --
    // estimator_config_for_config() above.
    msg::Estimator cfg;
    cfg.weight_heading_otos = 0.0f;
    cfg.weight_omega_otos = 0.0f;
    cfg.staleness = 60u;   // [ms]
    return cfg;
}

}  // namespace Config
