// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_boot_config.py before each firmware build.
// Source: data/robots/tovez_nocal.json
//
// The whole file is the robot's boot configuration: the per-port
// msg::MotorConfig defaults and the msg::DrivetrainConfig default, with
// per-robot calibration baked in from the robot JSON above. main.cpp calls
// these; it never hardcodes calibration. See src/firm/config/boot_config.h.

#include "config/boot_config.h"

namespace Config {

void defaultMotorConfigs(msg::MotorConfig* out) {
    // Velocity PID gains — baked from the robot JSON's control.vel_* keys
    // (093: now in the NezhaMotor duty [-1,1] plant scale, see the JSON's
    // control._vel_gains_domain marker), falling back to bench-tuned firmware
    // defaults when absent. Live-correctable per motor via `DEV M <n> CFG`.
    msg::Gains velGains;
    velGains.kp = 0.002f;
    velGains.ki = 0.0f;
    velGains.kff = 0.002f;
    velGains.i_max = 0.0f;
    velGains.kaw = 0.0f;   // anti-windup back-calculation (velocity_pid.cpp; 0 = off)

    // reversal_dwell / output_deadband are left unset (.has == false) on
    // purpose — Hal::Motor::configure() applies the real ship defaults (100 ms
    // / 0.03) whenever a config arrives unset; that is the one place those
    // defaults live.
    for (uint32_t i = 0; i < kMotorConfigCount; ++i) {
        out[i] = msg::MotorConfig();
        out[i].setPort(i + 1);
        out[i].setVelGains(velGains);
        // EMA coeff — from control.vel_filt (fallback default); a=0 would pin
        // reported velocity at 0 forever regardless of real motion.
        out[i].setVelFiltAlpha(1.0f);
    }

    // Per-port forward-sign — baked from the robot JSON's calibration.
    // fwd_sign_{left,right} for the drive-pair ports
    // (ports 1/2); other ports use the bench placeholder
    // (1). The drive pair is mirror-mounted, so left/right are
    // expected to differ in sign (088-002 —
    // clasi/issues/tovez-drive-motor-reversed-fwd-sign.md).
    out[0].setFwdSign(1);   // port 1
    out[1].setFwdSign(-1);   // port 2
    out[2].setFwdSign(1);   // port 3
    out[3].setFwdSign(1);   // port 4

    // Per-port encoder travel calibration — baked from the robot JSON's
    // calibration.mm_per_wheel_deg_{left,right} for the drive-pair ports
    // (ports 1/2); other ports use the bench placeholder.
    out[0].setTravelCalib(0.487f);   // [mm/deg] port 1
    out[1].setTravelCalib(0.487f);   // [mm/deg] port 2
    out[2].setTravelCalib(0.487f);   // [mm/deg] port 3
    out[3].setTravelCalib(0.487f);   // [mm/deg] port 4

    // Per-port I2C flip-flop poll-schedule membership (091-002) — true for
    // the drive-pair ports (1/2), false otherwise. Not
    // robot-JSON-configurable (a firmware-scheduling fact, not per-robot
    // calibration); live-adjustable via `DEV M <n> CFG polled=true` for a
    // bench rig's own non-drive-pair port (docs/protocol-v2.md §16).
    out[0].setPolled(true);   // port 1
    out[1].setPolled(true);   // port 2
    out[2].setPolled(false);   // port 3
    out[3].setPolled(false);   // port 4
}

msg::DrivetrainConfig defaultDrivetrainConfig() {
    msg::DrivetrainConfig cfg;
    cfg.setTrackwidth(128.0f);   // [mm] baked from robot geometry
    // The drive-pair port binding lives in DrivetrainConfig (the robot's
    // normal drive pair); the coupled bench rig re-binds via `DEV DT PORTS`.
    cfg.setLeftPort(1);
    cfg.setRightPort(2);
    return cfg;
}

OtosBootConfig defaultOtosBootConfig() {
    // 086-005 — additive to defaultMotorConfigs()/defaultDrivetrainConfig()
    // above; no existing mapping touched. Baked from the robot JSON's
    // geometry.odometry_offset_mm (x/y/yaw_rad) and calibration.
    // otos_linear_scale/otos_angular_scale where present; identity defaults
    // (zero offset, 1.0 scale) otherwise. Boot-time-baked only -- see
    // OtosBootConfig's own doc comment (src/firm/config/boot_config.h) for why
    // this is never a live SET/wire surface.
    OtosBootConfig cfg;
    cfg.offsetX = -47.7f;        // [mm]
    cfg.offsetY = 3.5f;        // [mm]
    cfg.offsetYaw = 0.0f;    // [rad]
    cfg.linearScale = 1.0f;
    cfg.angularScale = 1.0f;
    return cfg;
}

msg::PlannerConfig defaultPlannerConfig() {
    // 098-001 — the motion-limit fields below are moved verbatim from
    // main.cpp's hand-written defaultMotionConfig() (same numeric values,
    // same units — not renumbered or retuned by this move), the one
    // PlannerConfig boot path that lived OUTSIDE this generator until now.
    // heading_kp/heading_kd are the new outer heading-loop PD gains
    // (architecture-update.md M1/M2), baked from the robot JSON's
    // control.heading_kp/heading_kd, falling back to conservative firmware
    // starting defaults when absent. arrive_tol/turn_in_place_gate are left
    // unset (0.0f default) -- unchanged behavior, main.cpp's old function
    // never set them either (neither has a live consumer). min_speed is NO
    // LONGER left unset (100-007, THE CUTOVER) -- see MIN_SPEED_DEFAULT's
    // own comment above for why 0.0f silently broke pivot-mode detection
    // the moment source/drive/tracker.cpp became this field's first live
    // reader.
    //
    // Fields 15-31 (100-001 — Drive::Limits' wire/config source,
    // architecture-update.md M1/Decision 2): baked from the robot JSON's
    // control.* keys via drive_limits_for_config(), falling back to
    // conservative firmware starting defaults when absent — see this
    // generator's own field-default constants and data/robots/tovez.json's
    // `_drive_limits_note` for the full per-field derivation.
    msg::PlannerConfig cfg;
    cfg.setAMax(800.0f);               // [mm/s^2]
    cfg.setADecel(800.0f);             // [mm/s^2]
    cfg.setVBodyMax(1000.0f);           // [mm/s]
    cfg.setYawRateMax(1.22173f);         // [rad/s] (control.yaw_rate_max [deg/s])
    cfg.setYawAccMax(10.47198f);          // [rad/s^2] (control.max_rot_accel_dps2 [deg/s^2])
    cfg.setJMax(5000.0f);                // [mm/s^3] ~6x a_max -- ~0.16s jerk-limited edges
    cfg.setYawJerkMax(100.0f);         // [rad/s^3] ~5x yaw_acc_max -- ~0.2s
    cfg.setHeadingKp(1.0f);              // [1/s] outer heading-loop proportional gain
    cfg.setHeadingKd(0.0f);              // dimensionless outer heading-loop derivative gain
    cfg.setMinSpeed(16.0f);               // [mm/s] Drive:: tracker pivot-mode threshold (100-007)
    cfg.setVWheelMax(350.0f);              // [mm/s]
    cfg.setSteerHeadroom(20.0f);          // [mm/s]
    cfg.setWheelStepMax(150.0f);          // [mm/s]
    cfg.setTrackKS(2.0f);                // [1/s]
    cfg.setTrackKTheta(6.0f);            // [1/s]
    cfg.setTrackKCross(1.5e-05f);            // [rad/mm^2]
    cfg.setTrimVMax(120.0f);               // [mm/s]
    cfg.setTrimOmegaMax(2.0f);           // [rad/s]
    cfg.setReplanErrPos(40.0f);           // [mm]
    cfg.setReplanErrTheta(0.15f);         // [rad]
    cfg.setReplanHold(0.2f);              // [s]
    cfg.setReplanMinPeriod(0.3f);        // [s]
    cfg.setReplanMax(3.0f);               // dimensionless
    cfg.setHandoffTolPos(40.0f);          // [mm]
    cfg.setHandoffTolV(0.14f);            // [s]
    cfg.setArriveVelTol(15.0f);           // [mm/s]
    cfg.setArriveDwell(0.15f);             // [s]

    // 109-005: App::HeadingSource per-robot policy override + the heading-
    // dwell completion gate. heading_source baked from the robot JSON's
    // control.heading_source ("auto"/"otos"/"encoder"); the dwell
    // tolerance/rate are firmware defaults today (no robot-JSON key yet --
    // see heading_dwell_for_config()'s own comment).
    cfg.setHeadingSource(msg::HeadingSourceMode::HEADING_SOURCE_AUTO);
    cfg.setHeadingDwellTol(0.05235988f);        // [rad]
    cfg.setHeadingDwellRate(0.01745329f);       // [rad/s]

    // 109-010: three independently-tunable lead-compensation Δt's, fitted
    // from the rate-sweep regression -- see planner.proto's own field
    // comments and src/firm/motion/DESIGN.md's "Turn-error characterization"
    // entry for the full derivation.
    cfg.setHeadingLeadBias(-0.05f);        // [s] locus 1
    cfg.setPlanLead(0.2f);                // [s] locus 2
    cfg.setTerminalLead(0.0f);           // [s] locus 3
    return cfg;
}

}  // namespace Config
