// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_default_config.py before each firmware build.
// Source: /Volumes/Proj/proj/RobotProjects/radio-robot-elite/data/robots/tovez.json

#include "../types/Config.h"

RobotConfig defaultRobotConfig() {
    RobotConfig p{};

    // Motor forward-direction signs. fwdSign multiplies BOTH the drive command
    // and the encoder reading (Motor.cpp), so it sets the encoder's forward sense.
    // The robot drove BACKWARD on a forward command (camera-verified 2026-06-16:
    // faces +0deg, a forward D travelled -180deg) — the encoder/drive sense was
    // inverted — so both signs are flipped here. The L/R kinematic roles are
    // swapped in NezhaHAL to keep the encoder-difference heading CCW+.
    p.fwdSignL        = -1;
    p.fwdSignR        = +1;

    // Encoder calibration — baked from robot config
    p.wheelTravelCalibL = 0.7165f;
    p.wheelTravelCalibR = 0.7077f;

    // Feed-forward and motor scale factors
    p.kFF             = 0.15f;
    p.kScaleLF        = 1.0f;
    p.kScaleLB        = 1.0f;
    p.kScaleRF        = 1.0f;
    p.kScaleRB        = 1.0f;

    // Slower-wheel adjustment
    p.kAdjThreshold   = 0.5f;
    p.kAdjGain        = 0.05f;

    // Geometry — baked from robot config
    p.trackwidth      = 128.0f;

    // Wheel saturation ceiling and steering headroom
    p.vWheelMax       = 400.0f;
    p.steerHeadroom   = 20.0f;

    // OTOS complementary fusion
    p.alphaPos        = 0.15f;
    p.alphaYaw        = 0.10f;
    p.otosGate        = 50.0f;

    // EKF sensor fusion
    // N15 fix (030-009): Q values are now per-second spectral densities.
    // EKF::predict() multiplies Q by dt_s before adding to P.  At the default
    // controlPeriod = 10 ms, Q*dt = Q/100 matches the previous per-call values.
    // Q_per_second = Q_old / 0.010 s.
    // 2026-06-16: DISTRUST the encoder predict so the EKF prefers the OTOS
    // (optical-flow) absolute pose — the encoder heading is intrinsically noisy
    // (turn slip) and a diverged predict was gating the good OTOS out mid-turn
    // (fused rode the encoder).  Higher Q grows P faster, so the OTOS gate accepts
    // more AND the OTOS is weighted more (K -> 1).  Heading is the crux (position
    // dead-reckons along it), so Qtheta is pushed hardest (32x original).
    p.ekfQxy         = 800.0f;    // OTOS-preference (was 200; distrust encoder predict)
    p.ekfQtheta      = 4.0f;      // OTOS-preference, heading crux (was 0.5)
    p.ekfROtosXy     = 50.0f;

    // EKF velocity fusion (Sprint 023)
    p.ekfQv          = 5000.0f;   // was 50.0 per-call; 50.0/0.010 = 5000/s
    p.ekfQomega      = 1.0f;      // was 0.01 per-call; 0.01/0.010 = 1.0/s
    p.ekfROtosV      = 200.0f;
    p.ekfREncV       = 100.0f;

    // EKF heading fusion (Sprint 024-004)
    p.ekfROtosTheta  = 0.01f;  // ~(5.7 deg)^2

    // OTOS calibration scalars — baked from robot config.
    // OtosSensor::begin() programs the hardware registers from these
    // values at firmware boot; no host-side OL/OA push required.
    p.otosLinearScale      = 1.067f;
    p.otosAngularScale     = 0.987f;
    p.rotationGainPos      = 0.956f;
    p.rotationGainNeg      = 0.954f;
    p.rotationOffset       = 1.045f;
    p.rotationOffsetNeg    = 1.158f;
    p.rotationalSlip       = 0.92f;
    p.odomOffX             = -47.7f;
    p.odomOffY             = 3.5f;
    p.odomYaw              = 0.0f;
    p.odomUpsideDown       = false;

    // Velocity-loop gains — baked from robot config
    p.velKp           = 0.3f;
    p.velKi           = 0.5f;
    p.velKff          = 0.15f;
    p.minWheelSpeed   = 20.0f;
    p.velIMax         = 20.0f;
    p.velKaw          = 3.0f;
    p.velFiltAlpha    = 0.15f;
    p.syncGain        = 1.0f;

    // Pose-control tunables
    p.aMax            = 300.0f;
    p.aDecel          = 250.0f;
    p.turnInPlaceGate = 35.0f;
    p.arriveTolerance = 25.0f;

    // Body motion limits
    p.vBodyMax        = 400.0f;
    p.yawRateMax      = 70.0f;
    p.yawAccMax       = 720.0f;
    p.jMax            = 0.0f;
    p.yawJerkMax      = 0.0f;

    // Timing
    p.minSpeed        = 50;
    p.tick            = 20;
    p.sTimeout        = 500;
    p.safetyEnabled   = true;
    p.controlPeriod   = 10;
    p.tlmPeriod       = 0;
    p.tlmFields       = TLM_FIELD_ALL;
    p.tlmSnapPending  = false;

    // Sensor lag budgets
    // 2026-06-17: 100ms (10Hz) made the OTOS correct 10x slower than the 100Hz
    // encoder predict, so the encoder dominated between corrections and the OTOS
    // tripped the EKF gate by the time it voted.  10ms (100Hz) gives the OTOS the
    // most say in the fusion and measured the best turn accuracy (~1.5 deg vs the
    // camera).  Instrumented field sweeps showed the TWIM encoder wedge is roughly
    // RATE-INDEPENDENT (4-12% at 25/50/100Hz alike), so it is NOT mitigated by
    // backing the rate off (a pre-write-idle encoder fix was tried and refuted).
    p.lagOtos         = 10;
    p.lagLine         = 50;
    p.lagColor        = 100;
    p.lagPorts        = 50;

    // Sprint 046: mecanum drivetrain fields (baked from identity.drivetrain_type).
    // Differential-only build carries these fields with safe defaults; they are
    // unused unless mecanum kinematics code reads them (retained for future use).
    p.drivetrain      = 0;

    // Mecanum geometry (MEASURE placeholders; default 63.0 mm half-track/wheelbase).
    p.halfTrack       = 63.0f;
    p.halfWheelbase   = 63.0f;

    // Per-wheel encoder calibration (mecanum). Defaults from wheel_diameter_mm.
    p.wheelTravelCalibFR = 0.7048512f;
    p.wheelTravelCalibFL = 0.7048512f;
    p.wheelTravelCalibBR = 0.7048512f;
    p.wheelTravelCalibBL = 0.7048512f;

    // Per-wheel forward signs (mecanum). Bench-confirmed defaults.
    p.fwdSignFR       = -1;
    p.fwdSignFL       = 1;
    p.fwdSignBR       = -1;
    p.fwdSignBL       = 1;

    // Lateral profile limits (mecanum).
    p.vyBodyMax       = 400.0f;
    p.aMaxY           = 800.0f;
    p.jMaxY           = 0.0f;

    // OTOS lateral velocity complementary filter gain (046-006).
    p.otosAlphaVy     = 0.8f;

    return p;
}
