// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_default_config.py before each firmware build.
// Source: /Volumes/Proj/proj/RobotProjects/radio-robot-c/data/robots/tovez.json

#include "../types/Config.h"

RobotConfig defaultRobotConfig() {
    RobotConfig p{};

    // Motor forward-direction signs
    p.fwdSignL        = +1;
    p.fwdSignR        = -1;

    // Encoder calibration — baked from robot config
    p.mmPerDegL       = 0.71659f;
    p.mmPerDegR       = 0.70777f;

    // Feed-forward and motor scale factors
    p.kFF             = 0.15f;
    p.kScaleLF        = 1.0f;
    p.kScaleLB        = 1.0f;
    p.kScaleRF        = 1.0f;
    p.kScaleRB        = 1.0f;

    // Slower-wheel adjustment
    p.kAdjThreshold   = 0.5f;
    p.kAdjGain        = 0.05f;

    // Geometry — baked from robot config
    p.trackwidthMm    = 126.0f;

    // Ratio PID gains
    p.ratioPidKp      = 300.0f;
    p.ratioPidKi      = 0.0f;
    p.ratioPidKd      = 0.0f;
    p.ratioPidMax     = 30.0f;

    // Wheel saturation ceiling and steering headroom
    p.vWheelMax       = 400.0f;
    p.steerHeadroom   = 20.0f;

    // OTOS complementary fusion
    p.alphaPos        = 0.15f;
    p.alphaYaw        = 0.10f;
    p.otosGate        = 50.0f;

    // EKF sensor fusion
    p.ekfQxy         = 2.0f;
    p.ekfQtheta      = 0.005f;
    p.ekfROtosXy     = 50.0f;

    // OTOS calibration scalars — baked from robot config.
    // OtosSensor::begin() programs the hardware registers from these
    // values at firmware boot; no host-side OL/OA push required.
    p.otosLinearScale      = 1.127f;
    p.otosAngularScale     = 0.987f;
    p.rotationGainPos      = 0.956f;
    p.rotationGainNeg      = 0.954f;
    p.rotationOffsetDeg    = 1.045f;
    p.rotationOffsetDegNeg = 1.158f;
    p.rotationalSlip       = 0.74f;
    p.odomOffX             = 0.0f;
    p.odomOffY             = 0.0f;
    p.odomYawDeg           = 0.0f;
    p.odomUpsideDown       = false;

    // Velocity-loop gains — baked from robot config
    p.velKp           = 0.3f;
    p.velKi           = 0.5f;
    p.velKff          = 0.15f;
    p.minWheelMms     = 20.0f;
    p.velIMax         = 20.0f;
    p.velKaw          = 3.0f;
    p.velFiltAlpha    = 0.15f;
    p.syncGain        = 1.0f;

    // Legacy go-to tolerances
    p.turnThresholdMm = 50.0f;
    p.doneTolMm       = 5.0f;

    // Pose-control tunables
    p.aMax            = 300.0f;
    p.aDecel          = 250.0f;
    p.turnInPlaceGate = 45.0f;
    p.arriveTolMm     = 5.0f;

    // Body motion limits
    p.vBodyMax        = 400.0f;
    p.yawRateMax      = 180.0f;
    p.yawAccMax       = 720.0f;
    p.jMax            = 0.0f;
    p.yawJerkMax      = 0.0f;

    // Command scaling
    p.distScale       = 0.94f;
    p.turnScale       = 1.07f;

    // Timing
    p.minSpeedMms     = 50;
    p.tickMs          = 20;
    p.sTimeoutMs      = 500;
    p.controlPeriodMs = 10;
    p.tlmPeriodMs     = 0;
    p.tlmFields       = 0xFF;
    p.tlmSnapPending  = false;

    // Sensor lag budgets
    p.lagOtosMs       = 100;
    p.lagLineMs       = 50;
    p.lagColorMs      = 100;
    p.lagPortsMs      = 50;

    return p;
}
