// wire_codec_harness.cpp -- off-hardware acceptance harness for
// msg::wire::decode()/encode() (src/firm/messages/wire.{h,cpp}, GENERATED by
// scripts/gen_messages.py from the P4-pruned protos/envelope.proto +
// protos/telemetry.proto -- 103-001, SUC-001, architecture-update.md (103)
// Decisions 2/3). CommandEnvelope.cmd is exactly {move, config, stop} (116-001,
// MOVE protocol cutover -- `twist`, arm 19, is deleted/reserved, superseded
// by `move`, a fresh arm 21); ReplyEnvelope.body is exactly {ok, err, tlm};
// TelemetrySecondary is DELETED outright (124-009,
// robot-state-blackboard-...md) -- there is no second top-level wire
// message any more. Telemetry itself is frame v2 (115-009, matching
// 115-003's `telemetry-frame-tightening-
// amendment-to-gut-s1.md` rewrite): one `flags` bit-string (status+fault+
// event) replaces the pre-115 nine standalone bools/`fault_bits`/
// `event_bits`; a single `ack_corr`/`ack_err` slot replaces the depth-3 ack
// ring; per-source timestamped `EncoderReading`/`OtosReading` objects
// replace the flat `enc_left`/`enc_right`/`vel_left`/`vel_right`/bare
// `Pose2D otos` fields.
//
// Every pre-103 arm (drive/segment/replace/pose_fix/otos/ping/echo/get/
// stream/id/hello/ver/help/plan_dump) is GONE from the schema -- scenarios
// that exercised them (and the (req)/(min)/(max)/(abs_max)-validated
// fields that lived only on those removed arms, e.g. ConfigGet.target's
// (req) and MotionSegment's (min)/(max)/(abs_max)) have no field left to
// exercise in the pruned reachable set and are dropped, not ported. The
// generic decodeInto()/encodeInto() engine still supports those flags
// generically (untouched by this prune); this ticket's own real-bytes
// coverage below is the malformed-buffer/unknown-field-skip scenarios
// plus round-trip/encode coverage of every live arm.
//
// This is DISTINCT from the differential-against-google.protobuf suite
// (test_wire_differential.py/_wire_diff_driver.py) -- this harness checks
// the generic engine's OWN behavior in isolation, by hand-building wire
// bytes with WireRuntime's own primitives (the same primitives wire.cpp's
// generated decode()/encode() are built on) and asserting
// msg::wire::decode()'s resulting struct fields, or by hand-parsing
// msg::wire::encode()'s output.
//
// Mirrors wire_runtime_harness.cpp's exact pattern: hand-rolled assertions,
// prints PASS/FAIL, exits nonzero on any failure. Run by test_wire_codec.py
// via subprocess.
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "messages/envelope.h"
#include "messages/wire.h"
#include "messages/wire_runtime.h"

namespace {

using WireRuntime::WireType;

// --- Hand-rolled assertion plumbing (same tiny shape as
// wire_runtime_harness.cpp / runtime_blackboard_harness.cpp). ---

int g_failureCount = 0;
std::string g_scenarioName;

void beginScenario(const std::string& name) {
  g_scenarioName = name;
  std::printf("--- %s\n", name.c_str());
}

void fail(const std::string& what) {
  ++g_failureCount;
  std::printf("  FAIL [%s]: %s\n", g_scenarioName.c_str(), what.c_str());
}

void checkTrue(bool condition, const std::string& what) {
  if (!condition) fail(what + " -- expected true, got false");
}

void checkFalse(bool condition, const std::string& what) {
  if (condition) fail(what + " -- expected false, got true");
}

void checkU64Eq(uint64_t actual, uint64_t expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %llu, got %llu", what.c_str(),
                  static_cast<unsigned long long>(expected), static_cast<unsigned long long>(actual));
    fail(buf);
  }
}

void checkFloatEq(float actual, float expected, const std::string& what) {
  if (actual != expected) {
    char buf[256];
    std::snprintf(buf, sizeof(buf), "%s -- expected %g, got %g", what.c_str(), static_cast<double>(expected),
                  static_cast<double>(actual));
    fail(buf);
  }
}

// --- Hand-rolled wire-byte builder (a tiny buffer + cursor, composed with
// WireRuntime's own primitives -- the SAME primitives wire.cpp's generated
// decode()/encode() are built on) -- lets this harness construct arbitrary
// CommandEnvelope payloads without depending on a generic decode(). ---

struct Buf {
  uint8_t data[256] = {};
  size_t len = 0;
};

bool putVarintField(Buf& b, uint32_t number, uint64_t v) {
  return WireRuntime::encodeTag(number, WireType::kVarint, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeVarint(v, b.data, sizeof(b.data), &b.len);
}

bool putFloatField(Buf& b, uint32_t number, float v) {
  return WireRuntime::encodeTag(number, WireType::kFixed32, b.data, sizeof(b.data), &b.len) &&
         WireRuntime::encodeFloat(v, b.data, sizeof(b.data), &b.len);
}

bool putBytesField(Buf& b, uint32_t number, const uint8_t* payload, size_t payloadLen) {
  if (!WireRuntime::encodeTag(number, WireType::kLengthDelimited, b.data, sizeof(b.data), &b.len)) return false;
  if (!WireRuntime::encodeVarint(payloadLen, b.data, sizeof(b.data), &b.len)) return false;
  if (b.len + payloadLen > sizeof(b.data)) return false;
  std::memcpy(b.data + b.len, payload, payloadLen);
  b.len += payloadLen;
  return true;
}

bool putMessageField(Buf& b, uint32_t number, const Buf& nested) {
  return putBytesField(b, number, nested.data, nested.len);
}

// --- Generic top-level field scanner for the ENCODE-side scenarios below --
// (no generic decode(ReplyEnvelope) exists this sprint -- decode() is
// CommandEnvelope-only, encode() is ReplyEnvelope-only, per wire.h's own
// asymmetric API). Walks every
// top-level field of a length-delimited buffer into a flat list, tolerant
// of field order (the generator's own FieldDesc table order matches proto
// declaration order today, but this scanner does not assume that).

struct ParsedField {
  uint32_t number = 0;
  WireType type = WireType::kVarint;
  uint64_t varintVal = 0;
  float floatVal = 0.0f;
  const uint8_t* bytes = nullptr;
  size_t bytesLen = 0;
};

std::vector<ParsedField> parseFields(const uint8_t* buf, size_t len) {
  std::vector<ParsedField> out;
  size_t pos = 0;
  while (pos < len) {
    ParsedField pf;
    if (!WireRuntime::decodeTag(buf, len, &pos, &pf.number, &pf.type)) break;
    if (pf.type == WireType::kVarint) {
      if (!WireRuntime::decodeVarint(buf, len, &pos, &pf.varintVal)) break;
    } else if (pf.type == WireType::kFixed32) {
      if (!WireRuntime::decodeFloat(buf, len, &pos, &pf.floatVal)) break;
    } else if (pf.type == WireType::kLengthDelimited) {
      size_t plen = 0;
      if (!WireRuntime::beginLengthDelimited(buf, len, &pos, 0, &plen)) break;
      pf.bytes = buf + pos;
      pf.bytesLen = plen;
      pos += plen;
    } else {
      break;  // kFixed64 unreached by this schema
    }
    out.push_back(pf);
  }
  return out;
}

std::vector<ParsedField> fieldsWithNumber(const std::vector<ParsedField>& fields, uint32_t number) {
  std::vector<ParsedField> out;
  for (const auto& f : fields) {
    if (f.number == number) out.push_back(f);
  }
  return out;
}

// ===========================================================================
// 1. decode() round-trip -- every live CommandEnvelope arm (move, config,
//    stop).
// ===========================================================================

// --- Move payload builders, shared by the six velocity-variant x
// stop-kind round-trip scenarios below (116-001, MOVE protocol cutover). ---

Buf buildMoveTwistPayload(float v_x, float v_y, float omega) {
  Buf b;
  putFloatField(b, 1, v_x);
  putFloatField(b, 2, v_y);
  putFloatField(b, 3, omega);
  return b;
}

Buf buildMoveWheelsPayload(float v_left, float v_right) {
  Buf b;
  putFloatField(b, 1, v_left);
  putFloatField(b, 2, v_right);
  return b;
}

// velocityFieldNumber: 1 (twist) or 2 (wheels) -- Move.velocity's own field
// numbers. stopFieldNumber: 3 (time) / 4 (distance) / 5 (angle) -- Move.stop's
// own field numbers.
Buf buildMovePayload(uint32_t velocityFieldNumber, const Buf& velocityPayload, uint32_t stopFieldNumber,
                      float stopValue, float timeout, bool replace, uint32_t id) {
  Buf move;
  putMessageField(move, velocityFieldNumber, velocityPayload);
  putFloatField(move, stopFieldNumber, stopValue);
  putFloatField(move, 6, timeout);
  putVarintField(move, 7, replace ? 1 : 0);
  putVarintField(move, 8, id);
  return move;
}

void scenarioRoundTripMoveTwistTime() {
  beginScenario("decode(): round-trip move arm -- MoveTwist velocity + TIME stop");
  Buf velocity = buildMoveTwistPayload(150.0f, 0.0f, -0.75f);
  Buf move = buildMovePayload(/* twist */ 1, velocity, /* time */ 3, 2000.0f, 5000.0f, true, 42);
  Buf env;
  putVarintField(env, 1, 9);       // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkU64Eq(out.corr_id, 9, "corr_id round-trips");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::TWIST, "velocity_kind == TWIST");
  checkFloatEq(out.cmd.move.velocity.twist.v_x, 150.0f, "twist.v_x round-trips");
  checkFloatEq(out.cmd.move.velocity.twist.v_y, 0.0f, "twist.v_y round-trips (zero, implicit presence)");
  checkFloatEq(out.cmd.move.velocity.twist.omega, -0.75f, "twist.omega round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::TIME, "stop_kind == TIME");
  checkFloatEq(out.cmd.move.stop.time, 2000.0f, "stop.time round-trips");
  checkFloatEq(out.cmd.move.timeout, 5000.0f, "timeout round-trips");
  checkTrue(out.cmd.move.replace, "replace round-trips true");
  checkU64Eq(out.cmd.move.id, 42, "id round-trips");
}

void scenarioRoundTripMoveTwistDistance() {
  beginScenario("decode(): round-trip move arm -- MoveTwist velocity + DISTANCE stop");
  Buf velocity = buildMoveTwistPayload(-80.0f, 0.0f, 0.0f);
  Buf move = buildMovePayload(/* twist */ 1, velocity, /* distance */ 4, 300.0f, 8000.0f, false, 7);
  Buf env;
  putVarintField(env, 1, 11);      // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::TWIST, "velocity_kind == TWIST");
  checkFloatEq(out.cmd.move.velocity.twist.v_x, -80.0f, "twist.v_x round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::DISTANCE, "stop_kind == DISTANCE");
  checkFloatEq(out.cmd.move.stop.distance, 300.0f, "stop.distance round-trips");
  checkFloatEq(out.cmd.move.timeout, 8000.0f, "timeout round-trips");
  checkFalse(out.cmd.move.replace, "replace round-trips false (zero, implicit presence)");
  checkU64Eq(out.cmd.move.id, 7, "id round-trips");
}

void scenarioRoundTripMoveTwistAngle() {
  beginScenario("decode(): round-trip move arm -- MoveTwist velocity + ANGLE stop");
  Buf velocity = buildMoveTwistPayload(0.0f, 0.0f, 1.2f);
  Buf move = buildMovePayload(/* twist */ 1, velocity, /* angle */ 5, 1.5708f, 4000.0f, true, 3);
  Buf env;
  putVarintField(env, 1, 12);      // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::TWIST, "velocity_kind == TWIST");
  checkFloatEq(out.cmd.move.velocity.twist.omega, 1.2f, "twist.omega round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::ANGLE, "stop_kind == ANGLE");
  checkFloatEq(out.cmd.move.stop.angle, 1.5708f, "stop.angle round-trips");
  checkU64Eq(out.cmd.move.id, 3, "id round-trips");
}

void scenarioRoundTripMoveWheelsTime() {
  beginScenario("decode(): round-trip move arm -- MoveWheels velocity + TIME stop");
  Buf velocity = buildMoveWheelsPayload(120.0f, 100.0f);
  Buf move = buildMovePayload(/* wheels */ 2, velocity, /* time */ 3, 1500.0f, 6000.0f, false, 21);
  Buf env;
  putVarintField(env, 1, 13);      // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::WHEELS, "velocity_kind == WHEELS");
  checkFloatEq(out.cmd.move.velocity.wheels.v_left, 120.0f, "wheels.v_left round-trips");
  checkFloatEq(out.cmd.move.velocity.wheels.v_right, 100.0f, "wheels.v_right round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::TIME, "stop_kind == TIME");
  checkFloatEq(out.cmd.move.stop.time, 1500.0f, "stop.time round-trips");
  checkU64Eq(out.cmd.move.id, 21, "id round-trips");
}

void scenarioRoundTripMoveWheelsDistance() {
  beginScenario("decode(): round-trip move arm -- MoveWheels velocity + DISTANCE stop");
  Buf velocity = buildMoveWheelsPayload(-60.0f, -60.0f);
  Buf move = buildMovePayload(/* wheels */ 2, velocity, /* distance */ 4, 500.0f, 9000.0f, true, 99);
  Buf env;
  putVarintField(env, 1, 14);      // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::WHEELS, "velocity_kind == WHEELS");
  checkFloatEq(out.cmd.move.velocity.wheels.v_left, -60.0f, "wheels.v_left round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::DISTANCE, "stop_kind == DISTANCE");
  checkFloatEq(out.cmd.move.stop.distance, 500.0f, "stop.distance round-trips");
  checkU64Eq(out.cmd.move.id, 99, "id round-trips");
}

void scenarioRoundTripMoveWheelsAngle() {
  beginScenario("decode(): round-trip move arm -- MoveWheels velocity + ANGLE stop");
  Buf velocity = buildMoveWheelsPayload(90.0f, -90.0f);
  Buf move = buildMovePayload(/* wheels */ 2, velocity, /* angle */ 5, 3.14159f, 3000.0f, false, 1);
  Buf env;
  putVarintField(env, 1, 15);      // corr_id
  putMessageField(env, 21, move);  // CommandEnvelope.cmd.move, field 21

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::MOVE, "cmd_kind == MOVE");
  checkTrue(out.cmd.move.velocity_kind == msg::Move::VelocityKind::WHEELS, "velocity_kind == WHEELS");
  checkFloatEq(out.cmd.move.velocity.wheels.v_right, -90.0f, "wheels.v_right round-trips");
  checkTrue(out.cmd.move.stop_kind == msg::Move::StopKind::ANGLE, "stop_kind == ANGLE");
  checkFloatEq(out.cmd.move.stop.angle, 3.14159f, "stop.angle round-trips");
  checkU64Eq(out.cmd.move.id, 1, "id round-trips");
}

// Confirms the DELETED twist arm's old field number (19) is now treated
// exactly like any other unrecognized field: skipped by decodeInto()'s
// generic unknown-field path, never decoded into a live oneof arm (116-001,
// MOVE protocol cutover -- see envelope.proto's own reserved-list comment).
void scenarioReservedTwistArmIgnored() {
  beginScenario("decode(): reserved twist arm (field 19) is skipped, not decoded");
  Buf twist;
  putFloatField(twist, 1, 150.0f);
  putFloatField(twist, 2, -0.75f);
  putFloatField(twist, 3, 250.0f);

  Buf env;
  putVarintField(env, 1, 7);        // corr_id
  putMessageField(env, 19, twist);  // the deleted twist arm's old field number -- reserved, not reused

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds -- an unrecognized field number is skipped, not rejected");
  checkU64Eq(out.corr_id, 7, "corr_id (a still-recognized field) is unaffected");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::NONE,
            "cmd_kind stays NONE -- field 19 sets no oneof arm, the schema no longer knows it");
}

void scenarioRoundTripStop() {
  beginScenario("decode(): round-trip stop arm (zero-field)");
  Buf env;
  putVarintField(env, 1, 4);        // corr_id
  putMessageField(env, 13, Buf{});  // CommandEnvelope.cmd.stop, field 13, empty payload

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "stop decode succeeds");
  checkU64Eq(out.corr_id, 4, "corr_id round-trips");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::STOP, "cmd_kind == STOP");
}

// 132-013 (patch-surface retirement): CommandEnvelope.config now carries
// `SetConfigGroup{target, body}` (robot_config.proto), not the deleted
// `ConfigDelta{drivetrain=DrivetrainConfigPatch, ...}` this scenario used
// to round-trip -- see envelope.proto's own `config` arm doc comment for
// the retarget. `body` is itself an opaque encoded group (Configurator::
// applyGroup() decodes it separately, not this generic engine's job to
// interpret) -- this scenario proves the OUTER 2-level nested decode
// (CommandEnvelope.config -> SetConfigGroup.target/body) still works,
// mirroring the pre-132-013 scenario's own "2-level nested" coverage
// intent without asserting anything about a specific group's fields.
void scenarioRoundTripConfigSetGroup() {
  beginScenario("decode(): round-trip config arm -- SetConfigGroup{target, body} (2-level nested)");
  Buf body;
  putFloatField(body, 1, 42.0f);        // one opaque scalar field inside the group body
  Buf config;
  putVarintField(config, 1, 3);         // SetConfigGroup.target, field 1 (e.g. DRIVE == 3)
  putMessageField(config, 2, body);     // SetConfigGroup.body, field 2 (bytes -- same wire type as a message)
  Buf env;
  putMessageField(env, 6, config);      // CommandEnvelope.cmd.config, field 6

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "config (2-level nested) decode succeeds");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::CONFIG, "cmd_kind == CONFIG");
  checkU64Eq(static_cast<uint64_t>(out.cmd.config.target), 3, "target round-trips");
  checkU64Eq(out.cmd.config.body_count, body.len, "body_count matches the encoded body length");
}

// ===========================================================================
// 2. Unknown-field skip -- forward compatibility (still relevant post-prune:
//    a future arm addition must be skippable by an older build).
// ===========================================================================

void scenarioUnknownFieldSkipped() {
  beginScenario("decode(): unknown top-level field number is skipped, not rejected");
  Buf env;
  putVarintField(env, 1, 3);          // corr_id (known)
  putVarintField(env, 99, 123456);    // unknown field number 99 (varint) -- must be skipped
  putMessageField(env, 13, Buf{});    // stop arm (known), AFTER the unknown field

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkTrue(r.ok, "decode succeeds despite the unknown field 99");
  checkU64Eq(out.corr_id, 3, "corr_id (before the unknown field) is unaffected");
  checkTrue(out.cmd_kind == msg::CommandEnvelope::CmdKind::STOP, "cmd_kind == STOP (after the unknown field) is unaffected");
}

// ===========================================================================
// 3. Malformed wire bytes -- decode()'s generic ERR_DECODE path (no
//    (req)/(min)/(max)/(abs_max)-validated field survives the P4 prune to
//    exercise those specific codes; this proves the codec's baseline
//    malformed-input rejection is still intact).
// ===========================================================================

void scenarioMalformedBufferRejected() {
  beginScenario("decode(): truncated wire tag rejected as ERR_DECODE");
  Buf env;
  putVarintField(env, 1, 3);   // corr_id, well-formed
  // Append a truncated varint: the continuation bit (0x80) is set with no
  // following byte, so decodeTag()'s own varint read runs off the buffer.
  env.data[env.len++] = 0x80;

  msg::CommandEnvelope out;
  msg::wire::Result r = msg::wire::decode(out, env.data, static_cast<uint16_t>(env.len));
  checkFalse(r.ok, "decode rejects a truncated wire tag");
  checkTrue(r.code == msg::ErrCode::ERR_DECODE, "ErrCode is ERR_DECODE for malformed wire bytes");
}

// ===========================================================================
// 4. encode() -- ReplyEnvelope{ok/err/tlm} and the standalone
//    TelemetrySecondary codec, hand-parsed byte-for-byte (or via the
//    generic parseFields() scanner for the larger Telemetry frame).
// ===========================================================================

void scenarioEncodeAckHandParsed() {
  beginScenario("encode(): ReplyEnvelope{ok=Ack{q,rem,t}} -- hand-parsed byte-for-byte");
  msg::ReplyEnvelope reply;
  reply.corr_id = 9;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::OK;
  reply.body.ok.q = 5;
  reply.body.ok.rem = 12.5f;
  reply.body.ok.t = 4242;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds (n > 0)");

  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "corr_id tag decodes");
  checkU64Eq(fieldNumber, 1, "first field is corr_id (1)");
  uint64_t corrId = 0;
  checkTrue(WireRuntime::decodeVarint(buf, n, &pos, &corrId), "corr_id value decodes");
  checkU64Eq(corrId, 9, "corr_id round-trips");

  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "ok-arm tag decodes");
  checkU64Eq(fieldNumber, 2, "second field is the `ok` oneof arm (2)");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "ok-arm payload length decodes");

  auto ackFields = parseFields(buf + pos, payloadLen);
  checkU64Eq(ackFields.size(), 3, "Ack payload has 3 fields (q, rem, t)");
  checkU64Eq(ackFields[0].number, 1, "Ack.q field number is 1");
  checkU64Eq(ackFields[0].varintVal, 5, "Ack.q round-trips");
  checkU64Eq(ackFields[1].number, 2, "Ack.rem field number is 2");
  checkFloatEq(ackFields[1].floatVal, 12.5f, "Ack.rem round-trips");
  checkU64Eq(ackFields[2].number, 3, "Ack.t field number is 3");
  checkU64Eq(ackFields[2].varintVal, 4242, "Ack.t round-trips");
}

void scenarioEncodeErrorHandParsed() {
  beginScenario("encode(): ReplyEnvelope{err=Error{code,field}} -- hand-parsed");
  msg::ReplyEnvelope reply;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::ERR;
  reply.body.err.code = msg::ErrCode::ERR_RANGE;
  reply.body.err.field = 4;

  uint8_t buf[64] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");

  // corr_id == 0 -- implicit presence omits it, so the FIRST field on the
  // wire is the `err` oneof arm (field 3) directly.
  size_t pos = 0;
  uint32_t fieldNumber = 0;
  WireType wt = WireType::kVarint;
  checkTrue(WireRuntime::decodeTag(buf, n, &pos, &fieldNumber, &wt), "err-arm tag decodes");
  checkU64Eq(fieldNumber, 3, "first field is the `err` oneof arm (3) -- corr_id==0 correctly omitted");
  size_t payloadLen = 0;
  checkTrue(WireRuntime::beginLengthDelimited(buf, n, &pos, 0, &payloadLen), "err-arm payload length decodes");

  auto errFields = parseFields(buf + pos, payloadLen);
  checkU64Eq(errFields.size(), 2, "Error payload has 2 fields (code, field)");
  checkU64Eq(errFields[0].varintVal, static_cast<uint64_t>(msg::ErrCode::ERR_RANGE), "Error.code round-trips");
  checkU64Eq(errFields[1].varintVal, 4, "Error.field round-trips");
}

// zigzag32() -- test-local mirror of WireRuntime::zigzagEncode32() (124-008)
// used to predict a sint32 field's RAW ON-WIRE varint value from the signed
// int this scenario assigns to it -- `parseFields()` is a generic scanner
// that reports a varint field's raw unsigned value (`varintVal`), never
// zigzag-decoding it (it has no schema knowledge of which varint fields are
// sint32 vs. plain uint32) -- see options.proto's own (scale) doc comment:
// scale is a header-generation-time concept, invisible to the wire engine.
uint64_t zigzag32(int32_t v) {
  return (static_cast<uint32_t>(v) << 1) ^ static_cast<uint32_t>(v >> 31);
}

void scenarioEncodeTelemetryFlagsAckRingAndReadings() {
  beginScenario("encode(): ReplyEnvelope{tlm=Telemetry{flags, packed acks, "
                "EncoderReading, OtosReading, line, color}} -- hand-parsed via generic scanner");
  msg::ReplyEnvelope reply;
  reply.corr_id = 11;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::TLM;
  msg::Telemetry& t = reply.body.tlm;
  // `body`'s own `= {}` default-member-initializer only value-initializes
  // the union's FIRST alternative (`ok`, an `Ack`) -- `tlm` (the THIRD
  // alternative, far larger) is left with INDETERMINATE bytes past
  // wherever `Ack`'s own 12 bytes end (the exact hazard `decode()`'s own
  // `std::memset` fix -- see this file's own `decode(CommandEnvelope&)`
  // engine-code precedent -- exists to close on the decode side; this is
  // the identical hazard on the encode/hand-construct side). Confirmed by
  // ASan (120): an uninitialized `acks_count` produced a garbage loop
  // bound in `encodeInto()`'s `kRepeatedMessage` case, reading past `t`'s
  // own bounds. Plain assignment from a fresh, fully-defaulted temporary
  // (NOT the union's own in-place `{}` init) zeroes every field
  // correctly, sidestepping the union-specific hazard entirely.
  t = msg::Telemetry{};
  t.now = 5000;
  t.seq = 42;
  t.flags = 0x2021;  // arbitrary nonzero bit pattern spanning status/fault/event groups
  // 124-008 (issue §B4): the single "freshest ack" scalar slot (ack_corr/
  // ack_err, fields 5/6) is DELETED -- reserved, not reused. The bounded
  // ack ring (field 14) is packed uint32 (corr_id<<4|err) now, this
  // engine's first real FieldKind::kRepeatedScalar use.
  t.acks_count = 1;
  t.acks_[0] = (77u << 4) | 0u;
  // 124-008 (issue §B3): position/velocity/x/y/heading are sint32 (zigzag)
  // raw wire ints now, not float -- the (scale) conversion is a
  // header-generation-time concept (generated pack*()/unpack*() methods),
  // invisible to the wire engine itself. `time` is RENAMED `age` (field 3);
  // `position_epoch` (field 4) is new (Decision 6).
  t.enc_left.position = 10;
  t.enc_left.velocity = 15;
  t.enc_left.age = 200;
  t.enc_left.position_epoch = 3;
  t.enc_right.position = -5;
  t.enc_right.velocity = -1;
  t.enc_right.age = 200;
  t.otos.x = 1;
  t.otos.y = 2;
  t.otos.heading = 500;
  t.line = 0x01020304;
  t.color = 0x0A0B0C0D;

  uint8_t buf[256] = {};
  uint16_t n = msg::wire::encode(reply, buf, sizeof(buf));
  checkTrue(n > 0, "encode succeeds");
  checkTrue(n <= msg::wire::kReplyEnvelopeMaxEncodedSize, "encoded length stays within kReplyEnvelopeMaxEncodedSize");

  auto topFields = parseFields(buf, n);
  auto tlmArm = fieldsWithNumber(topFields, 4);
  checkU64Eq(tlmArm.size(), 1, "exactly one `tlm` oneof arm (field 4) at the top level");
  checkTrue(!tlmArm.empty() && tlmArm[0].type == WireType::kLengthDelimited, "tlm arm is length-delimited");

  auto tlmFields = tlmArm.empty() ? std::vector<ParsedField>{} : parseFields(tlmArm[0].bytes, tlmArm[0].bytesLen);

  auto now = fieldsWithNumber(tlmFields, 1);
  checkU64Eq(now.size(), 1, "now (field 1) present");
  if (!now.empty()) checkU64Eq(now[0].varintVal, 5000, "now round-trips");

  auto flags = fieldsWithNumber(tlmFields, 4);
  checkU64Eq(flags.size(), 1, "flags (field 4) present");
  if (!flags.empty()) checkU64Eq(flags[0].varintVal, 0x2021, "flags round-trips");

  auto ackCorr = fieldsWithNumber(tlmFields, 5);
  checkTrue(ackCorr.empty(), "ack_corr (field 5) is RESERVED, not reused (124-008, issue §B4)");
  auto ackErr = fieldsWithNumber(tlmFields, 6);
  checkTrue(ackErr.empty(), "ack_err (field 6) is RESERVED, not reused (124-008, issue §B4)");

  auto acks = fieldsWithNumber(tlmFields, 14);
  checkU64Eq(acks.size(), 1, "acks (field 14) present -- packed repeated uint32");
  if (!acks.empty()) {
    checkTrue(acks[0].type == WireType::kLengthDelimited, "packed acks is length-delimited");
    size_t pos = 0;
    uint64_t packed = 0;
    checkTrue(WireRuntime::decodeVarint(acks[0].bytes, acks[0].bytesLen, &pos, &packed),
              "packed acks[0] varint decodes");
    checkU64Eq(packed, (77u << 4) | 0u, "acks[0] == corr_id<<4|err round-trips");
  }

  auto encLeft = fieldsWithNumber(tlmFields, 7);
  checkU64Eq(encLeft.size(), 1, "enc_left (field 7) present -- EncoderReading is an unconditionally-emitted embedded message");
  if (!encLeft.empty()) {
    auto encLeftFields = parseFields(encLeft[0].bytes, encLeft[0].bytesLen);
    auto position = fieldsWithNumber(encLeftFields, 1);
    checkU64Eq(position.size(), 1, "enc_left.position (field 1) present");
    if (!position.empty()) checkU64Eq(position[0].varintVal, zigzag32(10), "enc_left.position round-trips (zigzag)");
    auto velocity = fieldsWithNumber(encLeftFields, 2);
    checkU64Eq(velocity.size(), 1, "enc_left.velocity (field 2) present");
    if (!velocity.empty()) checkU64Eq(velocity[0].varintVal, zigzag32(15), "enc_left.velocity round-trips (zigzag)");
    auto age = fieldsWithNumber(encLeftFields, 3);
    checkU64Eq(age.size(), 1, "enc_left.age (field 3) present");
    if (!age.empty()) checkU64Eq(age[0].varintVal, 200, "enc_left.age round-trips");
    auto epoch = fieldsWithNumber(encLeftFields, 4);
    checkU64Eq(epoch.size(), 1, "enc_left.position_epoch (field 4) present");
    if (!epoch.empty()) checkU64Eq(epoch[0].varintVal, 3, "enc_left.position_epoch round-trips");
  }

  auto otos = fieldsWithNumber(tlmFields, 9);
  checkU64Eq(otos.size(), 1, "otos (field 9) present -- OtosReading is an unconditionally-emitted embedded message");
  if (!otos.empty()) {
    auto otosFields = parseFields(otos[0].bytes, otos[0].bytesLen);
    auto x = fieldsWithNumber(otosFields, 1);
    checkU64Eq(x.size(), 1, "otos.x (field 1) present");
    if (!x.empty()) checkU64Eq(x[0].varintVal, zigzag32(1), "otos.x round-trips (zigzag)");
    auto heading = fieldsWithNumber(otosFields, 3);
    checkU64Eq(heading.size(), 1, "otos.heading (field 3) present");
    if (!heading.empty()) checkU64Eq(heading[0].varintVal, zigzag32(500), "otos.heading round-trips (zigzag)");
  }

  auto line = fieldsWithNumber(tlmFields, 12);
  checkU64Eq(line.size(), 1, "line (field 12) present");
  if (!line.empty()) checkU64Eq(line[0].varintVal, 0x01020304, "line round-trips");

  auto color = fieldsWithNumber(tlmFields, 13);
  checkU64Eq(color.size(), 1, "color (field 13) present");
  if (!color.empty()) checkU64Eq(color[0].varintVal, 0x0A0B0C0D, "color round-trips");
}

void scenarioEncodeOversizedBufferReturnsZero() {
  beginScenario("encode(): returns 0 (not a truncated buffer) when cap is too small");
  msg::ReplyEnvelope reply;
  reply.corr_id = 1;
  reply.body_kind = msg::ReplyEnvelope::BodyKind::TLM;
  msg::Telemetry& t = reply.body.tlm;
  // See scenarioEncodeTelemetryFlagsAckRingAndReadings()'s own comment for
  // why this assignment (not the union's own in-place `= {}` init) is
  // needed before touching any `tlm` field by hand.
  t = msg::Telemetry{};
  t.flags = 0x1;
  t.acks_count = 1;
  t.acks_[0] = (1u << 4) | 0u;
  t.enc_left.position = 1;
  t.enc_right.position = 1;
  t.otos.x = 1;

  // A fully-populated Telemetry frame needs well over a handful of bytes --
  // 4 is nowhere near enough.
  uint8_t tinyBuf[4] = {0xAA, 0xAA, 0xAA, 0xAA};
  uint16_t n = msg::wire::encode(reply, tinyBuf, sizeof(tinyBuf));
  checkU64Eq(n, 0, "encode returns 0 for a too-small destination buffer");

  // Zero-capacity buffer, as a boundary case.
  uint16_t n0 = msg::wire::encode(reply, tinyBuf, 0);
  checkU64Eq(n0, 0, "encode returns 0 for cap==0");
}

// scenarioEncodeTelemetrySecondary() -- DELETED (124-009): TelemetrySecondary
// itself is gone (robot-state-blackboard-...md, issue's own
// "TelemetrySecondary dies"). scenarioNoTelemetrySecondaryWireArm() below is
// this ticket's own regression test in its place -- the "no secondary wire
// arm is ever emitted" acceptance the ticket's Testing section calls for.

// 124-009 regression test (issue's own "TelemetrySecondary dies," this
// ticket's Testing section: "a TelemetrySecondary-removal regression test
// (asserting no secondary wire arm is ever emitted)"). Structural, not
// behavioral -- msg::TelemetrySecondary/msg::wire::encode(TelemetrySecondary&,
// ...)/msg::wire::kTelemetrySecondaryMaxEncodedSize no longer exist AT ALL,
// so there is no runtime call left to make; this scenario's own existence
// (it compiles and links) IS the proof. A future accidental re-introduction
// of the type would make this whole translation unit fail to build long
// before any assertion below could run -- the strongest form of "this can
// never come back" a generated-code deletion can offer.
void scenarioNoTelemetrySecondaryWireArm() {
  beginScenario("TelemetrySecondary is gone -- no wire arm, no encode() overload, no size constant (124-009)");
  checkTrue(true, "this translation unit links with zero references to msg::TelemetrySecondary");
}

}  // namespace

int main() {
  scenarioRoundTripMoveTwistTime();
  scenarioRoundTripMoveTwistDistance();
  scenarioRoundTripMoveTwistAngle();
  scenarioRoundTripMoveWheelsTime();
  scenarioRoundTripMoveWheelsDistance();
  scenarioRoundTripMoveWheelsAngle();
  scenarioReservedTwistArmIgnored();
  scenarioRoundTripStop();
  scenarioRoundTripConfigSetGroup();
  scenarioUnknownFieldSkipped();
  scenarioMalformedBufferRejected();
  scenarioEncodeAckHandParsed();
  scenarioEncodeErrorHandParsed();
  scenarioEncodeTelemetryFlagsAckRingAndReadings();
  scenarioEncodeOversizedBufferReturnsZero();
  scenarioNoTelemetrySecondaryWireArm();

  if (g_failureCount == 0) {
    std::printf("OK: all wire codec scenarios passed\n");
    return 0;
  }
  std::printf("FAILED: %d assertion(s) across the wire codec scenarios\n", g_failureCount);
  return 1;
}
