"""wire_commands.py -- GENERATED command-name registry (124-001).

AUTO-GENERATED by scripts/gen_messages.py -- do not edit by hand.
Source: protos/commands.proto's Verb enum + (binary) enum-value option.

The single source firmware dispatch (src/firm/messages/commands.h's
kVerbTable[]) and this host module are generated from the SAME schema --
see sprint 124 architecture Decision 2 (command-name registry, closing the
firmware/host/doc 3-way drift risk). Adding a future verb means editing
protos/commands.proto and regenerating -- never hand-editing this file.
"""

from __future__ import annotations

from typing import NamedTuple


class VerbEntry(NamedTuple):
    name: str
    binary: bool  # True: COBS+CRC-framed binary <data>; False: cleartext

VERBS: tuple[VerbEntry, ...] = (
    VerbEntry("HELLO", False),
    VerbEntry("PING", False),
    VerbEntry("ID", False),
    VerbEntry("VER", False),
    VerbEntry("DEVICE", False),
    VerbEntry("PONG", False),
    VerbEntry("READY", False),
    VerbEntry("STATUS", False),
    VerbEntry("HELP", False),
    VerbEntry("DBG", False),
    VerbEntry("MOVE", True),
    VerbEntry("CONFIG", True),
    VerbEntry("STOP", True),
    VerbEntry("WHEELS", True),
    VerbEntry("ESTOP", True),
    VerbEntry("TLM", True),
    VerbEntry("OK", True),
    VerbEntry("ERR", True),
    VerbEntry("GET_CONFIG", True),
    VerbEntry("CFG", True),
    VerbEntry("SET_FIELD", True),
    VerbEntry("SEED", False),
    VerbEntry("POSE", False),
    VerbEntry("GO_TO", True),
    VerbEntry("CALIBRATE", True),
)

VERB_BY_NAME: dict[str, VerbEntry] = {v.name: v for v in VERBS}

BINARY_VERBS: frozenset[str] = frozenset(
    v.name for v in VERBS if v.binary
)
CLEARTEXT_VERBS: frozenset[str] = frozenset(
    v.name for v in VERBS if not v.binary
)
