// commands.h -- Rt::PoseResetCommand / Rt::ConfigDelta: lightweight,
// host-safe POD command-plane payload types shared between
// source/runtime/blackboard.h and the subsystems that drain them directly
// (Subsystems::PoseEstimator's poseResetIn parameter, ticket 087-004).
//
// Extracted OUT of blackboard.h (which is where architecture-update-r1.md's
// Reference code originally defined both structs): the boundary rule
// "subsystems never include blackboard.h" (Step 3 / Self-Review of that
// document) means PoseEstimator::tick()'s new
// Rt::WorkQueue<Rt::PoseResetCommand,4>& parameter cannot be typed by naming
// a struct defined INSIDE blackboard.h -- pose_estimator.h would have to
// include blackboard.h to see it, which is exactly the direction the
// boundary rule forbids (subsystems depend on Blackboard's queue/state
// TYPES only, never the aggregate itself -- see that document's Step 4
// dependency graph). Moved here, a lightweight, CODAL-free header both
// blackboard.h and pose_estimator.h can include without either including
// the other -- the SAME pattern Decision 10 (ticket 087-002) already
// established for Subsystems::CommunicatorToCommandProcessorCommand
// (source/subsystems/wire_command.h).
//
// Zero CODAL includes: <cstdint> plus messages/{drivetrain,motor,planner,
// odometer}.h (all auto-generated by scripts/gen_messages.py with zero
// CODAL deps) -- so any host test harness that includes this header (or
// transitively, blackboard.h/pose_estimator.h) never drags in MicroBit.h.
// Mechanical application of Decision 10's "every blackboard payload is a
// host-safe POD in a lightweight header" standing rule to these two types.
#pragma once

#include <cstdint>

#include "messages/drivetrain.h"
#include "messages/motor.h"
#include "messages/odometer.h"
#include "messages/planner.h"

namespace Rt {

// SI/ZERO fan-out consumed by PoseEstimator in its own tick (target-drained
// reset -- Decision 7: entangled-with-integration resets stay owned by the
// target rather than externally applied by the Configurator).
struct PoseResetCommand {
  enum Kind { kSetPose, kResetBaseline } kind;
  msg::SetPose pose;  // valid when kind == kSetPose
};

// MotionCommand (087-006) -- S/T/D/R/TURN/RT/G/STOP's fan-out to the
// loop-owned motion-executor step (drains into Subsystems::Planner::apply(),
// ticket 007), posted to Rt::Blackboard::motionIn (a latest-wins Mailbox --
// mirrors the pre-087 MotionLoopState outbox's own "latest-wins, same as
// every other outbox in this tree" contract exactly). `verb` carries the
// SAME disambiguation the pre-087 MotionLoopState::activeVelocityVerb field
// held: empty for S/T/D/G (Planner's own msg::DriveMode already names the
// verb unambiguously), "R"/"TURN"/"RT" otherwise (all three of which can
// share a msg::DriveMode value with S/T -- see motion_commands.h's own field
// doc comment, ported verbatim). Kept as a small wrapper around
// msg::PlannerCommand (rather than widening that generated type) since verb
// disambiguation is loop/wire bookkeeping, not a Planner-level concept.
struct MotionCommand {
  msg::PlannerCommand command;
  char verb[8] = "";
  // Set ONLY by handleS() (motion_commands.cpp) -- the loop feeds its own
  // loop-owned StreamingDriveWatchdog when it drains a MotionCommand with
  // this flag set (mirrors the pre-087 contract: "sTimeout: fed ONLY by S's
  // own handler -- never by any other command", motion_commands.h). Kept
  // separate from `verb` (which persists across passes as the "currently
  // active goal's verb" bookkeeping) since this is a one-shot, this-dispatch-
  // only signal, true only for the ONE MotionCommand S itself posts.
  bool feedStreamWatchdog = false;
};

// ConfigDelta -- concretized 087-005 (was a target+port placeholder left by
// ticket 087-002/087-004). A target-tagged, FIELD-MASKED PARTIAL config
// delta headed for the Configurator's single bb.configIn queue.
//
// Why field-masked, not a full-struct replace: two SEPARATE ConfigDeltas
// for the SAME target, each built by a caller (a SET/`DEV *CFG` wire
// handler, ticket 006) that only knows about the ONE field it is changing,
// must fold onto the Configurator's own persistent per-target desired
// config WITHOUT clobbering a field the OTHER delta already changed. A
// full-struct-replace delta cannot do this: if delta A sets field X (from
// baseline B) and delta B sets field Y (from the SAME baseline B, because
// B posted before A's effect was published), applying "cfg = A.value" then
// "cfg = B.value" would silently revert field X back to B's original value
// the moment B is applied -- exactly the clobber this ticket's AC-7
// ("two deltas for the same target back-to-back... deterministic FIFO fold
// order") exists to rule out. A field mask lets the Configurator's fold
// (configurator.cpp) copy ONLY the bits a delta actually sets, onto its own
// running per-target copy, so two field-disjoint deltas always compose
// regardless of what baseline the caller used to build either one.
//
// Representation: `mask`'s bit i is 1 iff the i-th field of the
// *ConfigField enum matching `target` (below) is present in this delta's
// value member. Exactly ONE of the four `msg::*Config` value members
// (`drivetrain`/`motor`/`planner`/`odometer`) is meaningful per delta,
// selected by `target` -- mirrors Rt::PoseResetCommand's own "valid when
// kind == kSetPose" convention immediately above, rather than a union: none
// of these four generated msg:: types has a TRIVIAL default constructor
// (each has per-member default initializers), so a raw union of all four
// would need a hand-written default constructor/destructor to stay
// well-formed (msg::DrivetrainCommand's own internal `control` union gets
// away with `= {}` only because one of ITS arms, msg::Neutral, IS a
// trivial enum). Four plain members costs more memory per queued entry
// (WorkQueue<ConfigDelta,16> holds 16 of these) in exchange for zero
// union-special-member hazards -- judged the better trade for a
// mechanism this ticket needs to get exactly right.
//
// Field coverage: every *ConfigField enum below enumerates literally every
// top-level field the matching msg::*Config struct already declares
// (source/messages/{drivetrain,motor,planner,odometer}.h) -- no new
// capability is introduced, only a bit position assigned to each existing
// field, so future wire-routing work (ticket 006) never needs to touch this
// header. MotorConfigField is the one enum that further splits
// vel_gains (a nested msg::Gains) into its five independent members
// (kp/ki/kff/i_max/kaw) -- confirmed by direct read of
// source/commands/dev_commands.cpp's applyMotorCfgKey() that these five are
// ALREADY independently wire-settable today (`DEV M <n> CFG kp=... ki=...`,
// one key at a time), so folding vel_gains as a single opaque field would
// reintroduce the exact same clobber AC-7 rules out. No other struct's
// nested Gains/array field is ever set at sub-field granularity by any
// existing wire path (grep of source/commands/*.cpp), so DrivetrainConfig's
// own vel_gains and both wheel-array fields fold as single whole-field
// bits.
struct ConfigDelta {
  enum Target { kDrivetrain, kMotor, kPlanner, kOdometer };

  Target target = kDrivetrain;
  uint32_t port = 0;   // motor index (Hardware's [1, kPortCount] port
                       // convention) when target == kMotor; ignored otherwise
  uint64_t mask = 0;   // bit i -> field i of the *ConfigField enum matching
                       // `target` is present in the matching value member

  // Exactly one of these four is meaningful per delta -- see class comment.
  msg::DrivetrainConfig drivetrain = {};  // target == kDrivetrain (also re-feeds PoseEstimator, Decision -- see configurator.cpp)
  msg::MotorConfig motor = {};            // target == kMotor
  msg::PlannerConfig planner = {};        // target == kPlanner
  msg::OdometerConfig odometer = {};      // target == kOdometer
};

// One bit position per top-level field of msg::DrivetrainConfig, in the
// struct's own declaration order (source/messages/drivetrain.h). vel_gains,
// travel_calib_wheel_[]/_count, and fwd_sign_wheel_[]/_count each fold as
// ONE field (see ConfigDelta's class comment) -- no existing wire path sets
// any of their sub-elements independently.
enum class DrivetrainConfigField : uint8_t {
  kFwdSignL,
  kFwdSignR,
  kTravelCalibL,
  kTravelCalibR,
  kTrackwidth,
  kHalfTrack,
  kHalfWheelbase,
  kTravelCalibWheel,
  kFwdSignWheel,
  kVWheelMax,
  kSteerHeadroom,
  kVelGains,
  kVelFiltAlpha,
  kSyncGain,
  kMinWheel,
  kAlphaPos,
  kAlphaYaw,
  kOtosGate,
  kOtosLinearScale,
  kOtosAngularScale,
  kRotationGainPos,
  kRotationGainNeg,
  kRotationOffset,
  kRotationOffsetNeg,
  kRotationalSlip,
  kOdomOffX,
  kOdomOffY,
  kOdomYaw,
  kOdomUpsideDown,
  kEkfQXy,
  kEkfQTheta,
  kEkfROtosXy,
  kEkfROtosTheta,
  kEkfQV,
  kEkfQOmega,
  kEkfROtosV,
  kEkfREncV,
  kLagOtos,
  kDrivetrainType,
  kLeftPort,
  kRightPort,
};

// One bit position per top-level field of msg::MotorConfig, EXCEPT `port`
// (addressing metadata, not a configurable value -- ConfigDelta::port
// already carries the addressed motor index). vel_gains is split into its
// five members -- see ConfigDelta's class comment on why.
//
// kPolled (091-002): the I2C flip-flop poll-schedule membership fact --
// see msg::MotorConfig.polled's own doc comment (source/messages/motor.h,
// generated from protos/motor.proto). Folded like every other field
// (configurator.cpp's foldMotor()), but ALSO drives one extra side effect
// no other MotorConfigField bit does: when set, Configurator::applyOne()
// additionally calls Subsystems::Hardware::setPolled() (the Configurator's
// kMotor apply path, source/runtime/configurator.cpp) -- the one door
// through which NezhaHardware's polled_[] mask changes after construction.
enum class MotorConfigField : uint8_t {
  kTravelCalib,
  kFwdSign,
  kVelGainsKp,
  kVelGainsKi,
  kVelGainsKff,
  kVelGainsIMax,
  kVelGainsKaw,
  kVelFiltAlpha,
  kMinDuty,
  kSlewRate,
  kReversalDwell,
  kOutputDeadband,
  kPolled,
};

// One bit position per top-level field of msg::PlannerConfig.
enum class PlannerConfigField : uint8_t {
  kAMax,
  kADecel,
  kVBodyMax,
  kYawRateMax,
  kYawAccMax,
  kJMax,
  kYawJerkMax,
  kArriveTol,
  kTurnInPlaceGate,
  kMinSpeed,
};

// One bit position per top-level field of msg::OdometerConfig.
enum class OdometerConfigField : uint8_t {
  kLinearScalar,
  kAngularScalar,
};

// bitOf() -- the one place a *ConfigField enumerator becomes a `mask` bit.
// A caller building a ConfigDelta (or a fold routine reading one) always
// goes through these, never a raw shift, so the "bit i means field i of the
// enum matching `target`" invariant documented on ConfigDelta above cannot
// drift out of sync with the enums' own declaration order.
constexpr uint64_t bitOf(DrivetrainConfigField field) {
  return uint64_t{1} << static_cast<uint8_t>(field);
}
constexpr uint64_t bitOf(MotorConfigField field) {
  return uint64_t{1} << static_cast<uint8_t>(field);
}
constexpr uint64_t bitOf(PlannerConfigField field) {
  return uint64_t{1} << static_cast<uint8_t>(field);
}
constexpr uint64_t bitOf(OdometerConfigField field) {
  return uint64_t{1} << static_cast<uint8_t>(field);
}

}  // namespace Rt
