"""src/tests/unit/test_gen_boot_config_robot_groups.py -- generator-level
proof for ticket 132-005 (sprint 132 "configuration discipline": retarget
baking -- populate Config::Robot defaults from today's JSON shape).

scripts/gen_boot_config.py gains seven new no-argument
``default*Group()`` functions -- one per ``msg::ConfigGroupTarget``
(Geometry/Motors/Drive/WheelControl/Planner/Otos/Estimator,
src/firm/messages/robot_config.h, generated by ticket 002 from
src/protos/robot_config.proto) -- each reading the SAME ``_require()``/
``_get()`` call sites the pre-existing ``default*Config()``/
``default*BootConfig()`` functions already use (unchanged JSON path,
unchanged fail-closed strictness), but writing into the NEW generated
``msg::Geometry``/``msg::Motors``/``msg::Drive``/``msg::WheelControl``/
``msg::Planner``/``msg::Otos``/``msg::Estimator`` group structs instead of
the old hand-declared boot_config.h ones.

This is ADDITIVE for this ticket, not a replacement -- see
gen_boot_config.py's own module docstring ("132-005") for why: the
pre-existing functions still have live callers (boot_wiring.cpp/
boot_calibration.cpp/main.cpp), so this file also asserts they are still
emitted, unchanged, alongside the seven new ones.

Mirrors src/tests/unit/test_gen_boot_config_otos.py's/
test_gen_boot_config_planner.py's own in-process pattern (invokes the
generator module directly against the real data/robots/tovez.json) rather
than compiling firmware -- gen_boot_config.py's C++ output is a pure
function of (robot JSON, generator code), so proving the generator's
STRING output carries the right literal values is equivalent to proving
the compiled default*Group() function bodies do, and HOST_BUILD compiling
the regenerated boot_config.cpp is verified separately (`just build-sim`).

Collected under src/tests/unit/ (a generator/tooling-level check, not
sim/bench/playfield-scoped -- see tests/CLAUDE.md); pyproject.toml's
testpaths includes tests/unit.
"""

import json
import sys
from pathlib import Path

import pytest

# src/tests/unit/test_gen_boot_config_robot_groups.py -> unit -> tests -> repo root
_REPO_ROOT = Path(__file__).resolve().parents[3]
_SCRIPTS_DIR = _REPO_ROOT / "src" / "scripts"
_TOVEZ_JSON = _REPO_ROOT / "data" / "robots" / "tovez.json"

if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import gen_boot_config as gbc  # noqa: E402  (path must be set up before this import)


def _tovez_cfg() -> dict:
    return json.loads(_TOVEZ_JSON.read_text())


def test_generate_emits_all_seven_group_functions_additively():
    """generate()'s output gains all seven Config::Robot group-default
    functions without disturbing any pre-existing default*Config()/
    default*BootConfig() function (still called by boot_wiring.cpp/
    boot_calibration.cpp/main.cpp today -- deleting them would break
    HOST_BUILD, out of this ticket's scope)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    # Additive: every pre-existing generated function is still emitted.
    assert "void defaultMotorConfigs(msg::MotorConfig* out)" in content
    assert "msg::DrivetrainConfig defaultDrivetrainConfig()" in content
    assert "OtosBootConfig defaultOtosBootConfig()" in content
    assert "EstimatorBootConfig defaultEstimatorConfig()" in content
    assert "ShaperBootConfig defaultShaperConfig()" in content
    assert "DriveBootConfig defaultDriveConfig()" in content
    assert "WheelControllerBootConfig defaultWheelControllerConfig()" in content
    assert "PlannerBootConfig defaultPlannerLimits()" in content

    # New (132-005): one function per msg::ConfigGroupTarget.
    assert "msg::Geometry defaultGeometryGroup()" in content
    assert "msg::Motors defaultMotorsGroup()" in content
    assert "msg::Drive defaultDriveGroup()" in content
    assert "msg::WheelControl defaultWheelControlGroup()" in content
    assert "msg::Planner defaultPlannerGroup()" in content
    assert "msg::Otos defaultOtosGroup()" in content
    assert "msg::Estimator defaultEstimatorGroup()" in content


def test_default_geometry_group_matches_tovez_json():
    """Geometry: geometry.trackwidth, calibration.rotational_slip/
    rotation_gain_pos/rotation_offset_deg -- a representative sample of
    trackwidth_for_config()/rotational_slip_for_config()/
    rotation_calibration_for_config()'s own real tovez.json values."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.trackwidth = 128.0f;" in content
    assert "cfg.rotational_slip = 0.9117f;" in content
    assert "cfg.rotation_gain_pos = 1.061f;" in content
    assert "cfg.rotation_offset = -5.54f;" in content
    assert "cfg.rotation_gain_neg = 1.071f;" in content
    assert "cfg.rotation_offset_neg = -7.04f;" in content


def test_default_motors_group_matches_tovez_json_drive_pair_only():
    """Motors: the drive-pair-only slice of travel_calib_for_ports()/
    fwd_sign_for_ports() (port 1/2, mirror-mounted signs -- 088-002) plus
    the shared vel_*/output_deadband/reversal_dwell fields."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.travel_calib_left = 0.7165f;" in content
    assert "cfg.travel_calib_right = 0.7077f;" in content
    assert "cfg.fwd_sign_left = 1;" in content
    assert "cfg.fwd_sign_right = -1;" in content
    assert "cfg.output_deadband = 0.03f;" in content
    assert "cfg.reversal_dwell = 100.0f;" in content
    assert "cfg.vel_kp = 0.0016f;" in content
    assert "cfg.vel_kff = 0.0008f;" in content
    assert "cfg.vel_filt_alpha = 0.3f;" in content


def test_default_drive_group_matches_tovez_json():
    """Drive: control.duty_per_speed_left/right/crawl_pulse plus the
    Stage-A per-wheel commanded->actual correction (identity on tovez.json
    as of 2026-07-31, see that file's own _wheel_correction_note) -- the
    sprint's headline per-wheel drive-calibration surface (SUC-006)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.duty_per_speed_left = 0.00187325f;" in content
    assert "cfg.duty_per_speed_right = 0.00187325f;" in content
    assert "cfg.crawl_pulse = 0.0f;" in content
    assert "cfg.wheel_gain_left_accel = 1.0f;" in content
    assert "cfg.wheel_intercept_left_accel = 0.0f;" in content
    assert "cfg.wheel_gain_right_decel = 1.0f;" in content
    assert "cfg.wheel_intercept_right_decel = 0.0f;" in content


def test_default_wheel_control_group_matches_tovez_json():
    """WheelControl: Stage C's live population-measured figures (vMin/
    biasMax) plus Stage B/deficit-flag's inert-today (0) fields."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.v_min = 99.7f;" in content
    assert "cfg.bias_max = 23.8f;" in content
    assert "cfg.tau_adapt = 30.0f;" in content
    assert "cfg.a_steady = 30.0f;" in content
    assert "cfg.pid_kp = 0.0f;" in content
    assert "cfg.pid_max = 0.0f;" in content


def test_default_planner_group_matches_tovez_json_including_dead_shaper_fields():
    """Planner: the live planner.* surface plus the DEAD shaper_* fields
    (see robot_config.proto's own header checklist -- ticket-015 deletes
    them from the schema, not this ticket)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.v_max = 400.0f;" in content
    assert "cfg.a_max = 300.0f;" in content
    assert "cfg.control_period = 50.0f;" in content
    assert "cfg.actuation_delay = 50.0f;" in content
    # tovez.json's own planner.heading_hold_gain is 0.0 (130-011 zeroed the
    # limit-cycle-prone gain) -- NOT the stale 2.0 the three pre-existing
    # test_gen_boot_config_planner.py failures still expect.
    assert "cfg.heading_hold_gain = 0.0f;" in content
    assert "cfg.decel_plan_fraction = 0.4f;" in content
    # Dead shaper_* fields -- same source values as defaultShaperConfig()'s
    # own control.a_max/a_decel/alpha_max/alpha_decel/j_max/yaw_jerk_max.
    assert "cfg.shaper_a_max = 800.0f;" in content
    assert "cfg.shaper_a_decel = 800.0f;" in content
    assert "cfg.shaper_alpha_max = 7.0f;" in content
    assert "cfg.shaper_alpha_decel = 7.0f;" in content
    assert "cfg.shaper_j_max = 5000.0f;" in content
    assert "cfg.shaper_yaw_jerk_max = 100.0f;" in content


def test_default_otos_group_matches_tovez_json():
    """Otos: geometry.odometry_offset_mm.{x,y,yaw_rad} + calibration.
    otos_linear_scale/otos_angular_scale -- the config MULTIPLIER domain
    (trap 3, sprint.md), unconverted here (ticket 010's job on the live
    wire path, not this baking function)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.offset_x = -47.7f;" in content
    assert "cfg.offset_y = 3.5f;" in content
    assert "cfg.offset_yaw = 0.0f;" in content
    assert "cfg.linear_scale = 1.0275f;" in content
    assert "cfg.angular_scale = 0.987f;" in content


def test_default_estimator_group_matches_tovez_json():
    """Estimator: estimator.weight_heading_otos/weight_omega_otos/
    staleness_ms -- encoder-only-v1 (both weights committed 0.0)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.weight_heading_otos = 0.0f;" in content
    assert "cfg.weight_omega_otos = 0.0f;" in content
    assert "cfg.staleness = 60u;" in content


def test_group_functions_share_fail_closed_require_call_sites():
    """The new default*Group() functions read the SAME _require() call
    sites as the pre-existing functions -- unchanged fail-closed
    strictness (the ticket's own acceptance criterion): deleting a key one
    of the new functions depends on (planner.v_max, read by both
    planner_config_for_config() -> defaultPlannerLimits() AND
    defaultPlannerGroup()) still raises MissingRobotConfigKeyError from
    generate(), the same as it always has."""
    cfg = _tovez_cfg()
    del cfg["planner"]["v_max"]

    with pytest.raises(gbc.MissingRobotConfigKeyError) as exc_info:
        gbc.generate(cfg, "data/robots/tovez.json")

    assert exc_info.value.key_path == "planner.v_max"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
