"""src/tests/unit/test_gen_boot_config_robot_groups.py -- generator-level
proof for ticket 132-005 (sprint 132 "configuration discipline": retarget
baking -- populate Config::Robot defaults from today's JSON shape).

scripts/gen_boot_config.py gains seven new no-argument
``default*Group()`` functions -- one per ``msg::ConfigGroupTarget``
(Geometry/Motors/Drive/WheelControl/Planner/Otos/Estimator,
src/firm/messages/robot_config.h, generated by ticket 002 from
src/protos/robot_config.proto) -- each reading the SAME ``_require()``/
``_get()`` call sites the pre-existing ``default*Config()``/
``default*BootConfig()`` functions already use (unchanged JSON path,
unchanged fail-closed strictness), but writing into the NEW generated
``msg::Geometry``/``msg::Motors``/``msg::Drive``/``msg::WheelControl``/
``msg::Planner``/``msg::Otos``/``msg::Estimator`` group structs instead of
the old hand-declared boot_config.h ones.

This is ADDITIVE for this ticket, not a replacement -- see
gen_boot_config.py's own module docstring ("132-005") for why: the
pre-existing functions still have live callers (boot_wiring.cpp/
boot_calibration.cpp/main.cpp), so this file also asserts they are still
emitted, unchanged, alongside the seven new ones.

Mirrors src/tests/unit/test_gen_boot_config_otos.py's/
test_gen_boot_config_planner.py's own in-process pattern (invokes the
generator module directly against the real data/robots/tovez.json) rather
than compiling firmware -- gen_boot_config.py's C++ output is a pure
function of (robot JSON, generator code), so proving the generator's
STRING output carries the right literal values is equivalent to proving
the compiled default*Group() function bodies do, and HOST_BUILD compiling
the regenerated boot_config.cpp is verified separately (`just build-sim`).

Collected under src/tests/unit/ (a generator/tooling-level check, not
sim/bench/playfield-scoped -- see tests/CLAUDE.md); pyproject.toml's
testpaths includes tests/unit.

UPDATE (136-001, 2026-08-11): four tests below used to assert against
hardcoded literal snapshots of tovez.json's values, pinned when each test
was written. All four went stale the same way -- the robot was
legitimately re-measured/re-tuned after the snapshot was taken, exactly
the failure mode clasi/issues/later/B-gen-boot-config-parity-tests-
encode-superseded-literals.md names:

  * test_default_geometry_group_matches_tovez_json -- rotational_slip
    moved 0.9117 -> 0.9371 (5cf125f0, re-measured against the v5 MOVE
    angle-stop path). NOT one of the issue's three originally-named
    tests (that measurement landed in the same commit the sprint's own
    baseline was taken from), but the identical pattern -- fixed here
    rather than left for a later ticket to re-discover.
  * test_default_drive_group_matches_tovez_json -- wheel_gain_left_accel/
    wheel_gain_right_decel moved off IDENTITY (1.0) to 132-019's
    bench-fitted 0.9075/0.800. One of the issue's three named tests.
  * test_default_wheel_control_group_matches_tovez_json -- pid_ki/pid_
    i_max/pos_err_max/pid_max moved off Stage-B-inert zeros to 133-004's
    tuned values; this test already tracked that once (see its own
    docstring) but the fix re-pinned a NEW snapshot rather than reading
    the file, so it broke again.
  * test_default_otos_group_matches_tovez_json -- linear_scale moved
    1.0275 -> 1.0188 (2026-08-05, tape-measured).

All four now read tovez.json at test time and assert the generator
faithfully carries THOSE values through, so a legitimate re-measurement
passes and a genuine generator defect (wrong key, dropped field, a
formatting bug) still fails.
"""

import json
import sys
from pathlib import Path

import pytest

# src/tests/unit/test_gen_boot_config_robot_groups.py -> unit -> tests -> repo root
_REPO_ROOT = Path(__file__).resolve().parents[3]
_SCRIPTS_DIR = _REPO_ROOT / "src" / "scripts"
_TOVEZ_JSON = _REPO_ROOT / "data" / "robots" / "tovez.json"

if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import gen_boot_config as gbc  # noqa: E402  (path must be set up before this import)


def _tovez_cfg() -> dict:
    return json.loads(_TOVEZ_JSON.read_text())


def test_generate_emits_all_seven_group_functions_additively():
    """generate()'s output gains all seven Config::Robot group-default
    functions without disturbing any pre-existing default*Config()/
    default*BootConfig() function that STILL has a live caller (still
    called by boot_wiring.cpp/boot_calibration.cpp/main.cpp today --
    deleting one of those would break HOST_BUILD, out of this ticket's
    scope). ShaperBootConfig/defaultShaperConfig(), DriveBootConfig/
    defaultDriveConfig(), and WheelControllerBootConfig/
    defaultWheelControllerConfig() are DELIBERATELY absent below -- 132-015
    (dead-code sweep) confirmed zero remaining callers for all three and
    deleted them; see config/boot_config.h's own note at each struct's
    former declaration site."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    # Additive: every pre-existing, still-LIVE generated function is still
    # emitted.
    assert "void defaultMotorConfigs(msg::MotorConfig* out)" in content
    assert "msg::DrivetrainConfig defaultDrivetrainConfig()" in content
    assert "OtosBootConfig defaultOtosBootConfig()" in content
    assert "EstimatorBootConfig defaultEstimatorConfig()" in content
    assert "PlannerBootConfig defaultPlannerLimits()" in content

    # DELETED, 132-015 -- confirm the FUNCTIONS stay gone, not merely
    # absent by accident (a regression the other direction -- re-adding
    # dead code -- would also be wrong). Checks the function signature,
    # not the bare struct name: the generated banner comment legitimately
    # still mentions these names in past tense (explaining the deletion),
    # so a bare substring check would false-positive on that prose.
    assert "ShaperBootConfig defaultShaperConfig()" not in content
    assert "DriveBootConfig defaultDriveConfig()" not in content
    assert "WheelControllerBootConfig defaultWheelControllerConfig()" not in content

    # New (132-005): one function per msg::ConfigGroupTarget.
    assert "msg::Geometry defaultGeometryGroup()" in content
    assert "msg::Motors defaultMotorsGroup()" in content
    assert "msg::Drive defaultDriveGroup()" in content
    assert "msg::WheelControl defaultWheelControlGroup()" in content
    assert "msg::Planner defaultPlannerGroup()" in content
    # 132-017: PlannerShaper split out of Planner (stakeholder-sanctioned
    # mid-sprint scope addition) -- the six live shaper-ceiling fields get
    # their own default*Group() function.
    assert "msg::PlannerShaper defaultPlannerShaperGroup()" in content
    assert "msg::Otos defaultOtosGroup()" in content
    assert "msg::Estimator defaultEstimatorGroup()" in content


def test_default_geometry_group_matches_tovez_json():
    """Geometry: geometry.trackwidth, calibration.rotational_slip/
    rotation_gain_pos/rotation_offset_deg -- a representative sample of
    trackwidth_for_config()/rotational_slip_for_config()/
    rotation_calibration_for_config()'s own real tovez.json values, read
    at test time (not a historical snapshot -- see this module's own
    dated note above)."""
    cfg = _tovez_cfg()
    content = gbc.generate(cfg, "data/robots/tovez.json")
    geom = cfg["geometry"]

    assert f"cfg.trackwidth = {gbc._f(geom['trackwidth'])};" in content
    assert f"cfg.rotational_slip = {gbc._f(geom['rotational_slip'])};" in content
    assert f"cfg.rotation_gain_pos = {gbc._f(geom['rotation_gain_pos'])};" in content
    assert f"cfg.rotation_offset = {gbc._f(geom['rotation_offset'])};" in content
    assert f"cfg.rotation_gain_neg = {gbc._f(geom['rotation_gain_neg'])};" in content
    assert f"cfg.rotation_offset_neg = {gbc._f(geom['rotation_offset_neg'])};" in content


def test_default_motors_group_matches_tovez_json_drive_pair_only():
    """Motors: the drive-pair-only slice of travel_calib_for_ports()/
    fwd_sign_for_ports() (port 1/2, mirror-mounted signs -- 088-002) plus
    the shared vel_*/output_deadband/reversal_dwell fields."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.travel_calib_left = 0.7165f;" in content
    assert "cfg.travel_calib_right = 0.7077f;" in content
    assert "cfg.fwd_sign_left = 1;" in content
    assert "cfg.fwd_sign_right = -1;" in content
    assert "cfg.output_deadband = 0.03f;" in content
    assert "cfg.reversal_dwell = 100.0f;" in content
    assert "cfg.vel_kp = 0.0016f;" in content
    assert "cfg.vel_kff = 0.0008f;" in content
    assert "cfg.vel_filt_alpha = 0.3f;" in content


def test_default_drive_group_matches_tovez_json():
    """Drive: control.duty_per_speed_left/right/crawl_pulse plus the
    Stage-A per-wheel commanded->actual correction -- the sprint's
    headline per-wheel drive-calibration surface (SUC-006), read at test
    time (not a historical snapshot -- see this module's own dated note
    above: wheel_gain_left_accel/wheel_gain_right_decel moved off
    IDENTITY to 132-019's bench-fitted values, 0.9075/0.800).

    duty_per_speed_left/right corrected 0.00187325 -> 0.001182 (132-009,
    the-configuration-object.md): the JSON field now matches
    Core::DifferentialDrive::kDutyPerSpeed's own measured constant -- the value that has
    actually been running on hardware since 2026-07-31 -- rather than the
    stale figure the-configuration-object.md's Cause section cites as the
    ~1.6x host-vs-firmware disagreement. See tovez.json's own
    _duty_per_speed_correction_note for the full writeup."""
    cfg = _tovez_cfg()
    content = gbc.generate(cfg, "data/robots/tovez.json")
    drive = cfg["drive"]

    assert f"cfg.duty_per_speed_left = {gbc._f(drive['duty_per_speed_left'])};" in content
    assert f"cfg.duty_per_speed_right = {gbc._f(drive['duty_per_speed_right'])};" in content
    assert f"cfg.crawl_pulse = {gbc._f(drive['crawl_pulse'])};" in content
    assert f"cfg.wheel_gain_left_accel = {gbc._f(drive['wheel_gain_left_accel'])};" in content
    assert f"cfg.wheel_intercept_left_accel = {gbc._f(drive['wheel_intercept_left_accel'])};" in content
    assert f"cfg.wheel_gain_right_decel = {gbc._f(drive['wheel_gain_right_decel'])};" in content
    assert f"cfg.wheel_intercept_right_decel = {gbc._f(drive['wheel_intercept_right_decel'])};" in content


def test_default_wheel_control_group_matches_tovez_json():
    """WheelControl: Stage C's live population-measured figures (vMin/
    biasMax) plus Stage B, which is LIVE as of 133-004, plus the
    2026-08-08 stall-detection triple -- all read from tovez.json at test
    time (not a historical snapshot -- see this module's own dated note
    above).

    Stage B was inert (every ``pid_*`` at 0) from 130-004 until 133-004,
    and this test used to assert those zeros as a hardcoded snapshot;
    133-004 is the bench session that tuned it on `tovez` and promoted
    the measured values, and the RE-pinned snapshot broke the same way the
    first one did -- see `data/robots/tovez.json`'s own
    `_stage_b_tuning_note` for the run behind each figure. Two fields are
    genuinely, deliberately zero (not merely untuned) and are still worth
    calling out even though the assertion below no longer hardcodes them:

      * ``pid_kp`` is zero as a MEASURED RESULT (133-004 answered 130-004's
        Open Question 4 with a no -- the velocity-domain P term bought no
        distance fidelity and cost straight-line heading; the position I
        term does the work).
      * ``pid_kaff`` is zero because the ``cmdAccel`` path is still
        unvalidated.
    """
    cfg = _tovez_cfg()
    content = gbc.generate(cfg, "data/robots/tovez.json")
    wc = cfg["wheel_control"]

    assert f"cfg.v_min = {gbc._f(wc['v_min'])};" in content
    assert f"cfg.bias_max = {gbc._f(wc['bias_max'])};" in content
    assert f"cfg.tau_adapt = {gbc._f(wc['tau_adapt'])};" in content
    assert f"cfg.a_steady = {gbc._f(wc['a_steady'])};" in content
    assert f"cfg.pid_kp = {gbc._f(wc['pid_kp'])};" in content
    assert f"cfg.pid_ki = {gbc._f(wc['pid_ki'])};" in content
    assert f"cfg.pid_i_max = {gbc._f(wc['pid_i_max'])};" in content
    assert f"cfg.pos_err_max = {gbc._f(wc['pos_err_max'])};" in content
    assert f"cfg.pid_max = {gbc._f(wc['pid_max'])};" in content
    assert f"cfg.pid_kaff = {gbc._f(wc['pid_kaff'])};" in content
    # 2026-08-08 stall-detection directive (this ticket's own Cluster 1) --
    # tovez.json has carried real, nonzero values for these since that
    # date; asserted here alongside the rest of the group for the same
    # "generator faithfully emits what the JSON says" property.
    assert f"cfg.stall_speed = {gbc._f(wc['stall_speed'])};" in content
    assert f"cfg.stall_demand = {gbc._f(wc['stall_demand'])};" in content
    assert f"cfg.stall_window = {gbc._f(wc['stall_window'])};" in content


def test_default_planner_group_matches_tovez_json():
    """Planner: the BOOT-ONLY planner.* surface -- v_max/omega_max/
    control_period/actuation_delay/settle_*/heading_hold_gain/
    decel_plan_fraction. The six shaper-ceiling fields (a_max/a_decel/
    alpha_max/alpha_decel/jerk_max/yaw_jerk_max) are SPLIT OUT, 132-017
    (JSON reshape ticket, stakeholder-sanctioned mid-sprint scope
    addition) -- see test_default_planner_shaper_group_matches_tovez_json()
    below. The formerly-DEAD shaper_* (prefixed) fields (robot_config.
    proto's own header checklist) are separately DELETED, 132-015 (schema
    fields now `reserved`, C++ struct/generator function gone -- see that
    message's own trailing comment and config/boot_config.h's note at
    ShaperBootConfig's former declaration site) -- NOT the same fields as
    this split, see PlannerShaper's own header comment for the
    distinction."""
    cfg = _tovez_cfg()
    content = gbc.generate(cfg, "data/robots/tovez.json")

    assert "cfg.v_max = 400.0f;" in content
    # control_period/actuation_delay are read FROM tovez.json rather than
    # frozen as literals here. Both are "= Core::RobotLoop::kCycle" by
    # construction (see robot_loop.h's kCycle doc comment), so they move
    # every time the loop period does -- they were 40, then 50, and became
    # 32 on 2026-08-07, and a hardcoded literal turns each of those
    # legitimate changes into a spurious generator failure. This is the fix
    # clasi/issues/later/B-gen-boot-config-parity-tests-encode-superseded-
    # literals.md proposes for this whole family: assert the generator
    # faithfully emits what the JSON says, which is the property this test
    # actually defends.
    assert f"cfg.control_period = {gbc._f(cfg['planner']['control_period'])};" in content
    assert f"cfg.actuation_delay = {gbc._f(cfg['planner']['actuation_delay'])};" in content
    # Derived from the JSON, not pinned to a literal -- this assertion used to
    # hard-code 0.0f (130-011's zeroed gain), which contradicted this test's
    # own stated property two comments up ("the generator faithfully emits what
    # the JSON says") and turned a deliberate re-tune into a test failure. The
    # value moved 0.0 -> 1.0 on 2026-08-13 when heading hold was re-enabled on
    # the OTOS; see tovez.json's planner._settle_note for why 130-011's
    # zeroing rationale no longer applies.
    assert f"cfg.heading_hold_gain = {gbc._f(cfg['planner']['heading_hold_gain'])};" in content
    assert "cfg.decel_plan_fraction = 0.4f;" in content
    # 134-003 terminal fine-align. align_tol is RADIANS -- 0.017453 rad is
    # the bench report's 1.0 DEGREE operating point, converted once in
    # tovez.json. A value near 1.0 here would mean degrees leaked into a
    # radian field (57x), which no downstream check would notice.
    assert "cfg.align_tol = 0.017453f;" in content
    assert "cfg.align_max_nudges = 6;" in content
    # DELETED, 132-015 -- confirm they stay gone.
    assert "shaper_a_max" not in content
    assert "shaper_yaw_jerk_max" not in content
    # SPLIT OUT, 132-017 -- defaultPlannerGroup()'s own output must not
    # carry the shaper-ceiling fields any more (they moved to
    # defaultPlannerShaperGroup(), checked separately below); scoped to
    # this one function's own generated body, not the whole file (the
    # sibling defaultPlannerShaperGroup() legitimately DOES emit
    # "cfg.a_max = ...").
    planner_group_start = content.index("msg::Planner defaultPlannerGroup()")
    planner_group_end = content.index("msg::PlannerShaper defaultPlannerShaperGroup()")
    planner_group_body = content[planner_group_start:planner_group_end]
    assert "cfg.a_max" not in planner_group_body
    assert "cfg.yaw_jerk_max" not in planner_group_body


def test_default_planner_shaper_group_matches_tovez_json():
    """PlannerShaper: the LIVE shaper-ceiling surface split out of Planner
    (132-017) -- a_max/a_decel/alpha_max/alpha_decel/jerk_max/
    yaw_jerk_max, still read from the SAME `planner.*` JSON keys (the
    reshape does not touch the JSON section boundary for these six)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.a_max = 300.0f;" in content
    assert "cfg.a_decel = 250.0f;" in content
    assert "cfg.alpha_max = 6.0f;" in content
    assert "cfg.alpha_decel = 5.0f;" in content
    assert "cfg.jerk_max = 1500.0f;" in content
    assert "cfg.yaw_jerk_max = 30.0f;" in content


def test_default_otos_group_matches_tovez_json():
    """Otos: geometry.odometry_offset_mm.{x,y,yaw_rad} + calibration.
    otos_linear_scale/otos_angular_scale -- the config MULTIPLIER domain
    (trap 3, sprint.md), unconverted here (ticket 010's job on the live
    wire path, not this baking function), read at test time (not a
    historical snapshot -- see this module's own dated note above:
    linear_scale moved 1.0275 -> 1.0188, 2026-08-05 tape measurement)."""
    cfg = _tovez_cfg()
    content = gbc.generate(cfg, "data/robots/tovez.json")
    otos = cfg["otos"]

    assert f"cfg.offset_x = {gbc._f(otos['offset_x'])};" in content
    assert f"cfg.offset_y = {gbc._f(otos['offset_y'])};" in content
    assert f"cfg.offset_yaw = {gbc._f(otos['offset_yaw'])};" in content
    assert f"cfg.linear_scale = {gbc._f(otos['linear_scale'])};" in content
    assert f"cfg.angular_scale = {gbc._f(otos['angular_scale'])};" in content


def test_default_estimator_group_matches_tovez_json():
    """Estimator: estimator.weight_heading_otos/weight_omega_otos/
    staleness_ms -- encoder-only-v1 (both weights committed 0.0)."""
    content = gbc.generate(_tovez_cfg(), "data/robots/tovez.json")

    assert "cfg.weight_heading_otos = 0.0f;" in content
    assert "cfg.weight_omega_otos = 0.0f;" in content
    assert "cfg.staleness = 60u;" in content


def test_group_functions_share_fail_closed_require_call_sites():
    """The new default*Group() functions read the SAME _require() call
    sites as the pre-existing functions -- unchanged fail-closed
    strictness (the ticket's own acceptance criterion): deleting a key one
    of the new functions depends on (planner.v_max, read by both
    planner_config_for_config() -> defaultPlannerLimits() AND
    defaultPlannerGroup()) still raises MissingRobotConfigKeyError from
    generate(), the same as it always has."""
    cfg = _tovez_cfg()
    del cfg["planner"]["v_max"]

    with pytest.raises(gbc.MissingRobotConfigKeyError) as exc_info:
        gbc.generate(cfg, "data/robots/tovez.json")

    assert exc_info.value.key_path == "planner.v_max"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
